/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/addr_decodeTMR.sv                                                      *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:42                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/addr_decode.sv                                                           *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912                           *
 *           Modification time : 2025-12-30 15:56:06.284690                                         *
 *           File Size         : 5019                                                               *
 *           MD5 hash          : 1fe7e879e78f2d7801c786bc06747101                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module addr_decodeTMR #(
  parameter int unsigned NoIndices = 32'd0,
  parameter int unsigned NoRules = 32'd0,
  parameter type addr_t = logic,
  parameter type rule_t = logic,
  parameter bit Napot = 0,
  parameter int unsigned IdxWidth = cf_math_pkg::idx_width(NoIndices),
  parameter type idx_t = logic [IdxWidth-1:0]
) (
  input addr_t addr_iA,
  input addr_t addr_iB,
  input addr_t addr_iC,
  input rule_t [NoRules - 1:0] addr_map_iA,
  input rule_t [NoRules - 1:0] addr_map_iB,
  input rule_t [NoRules - 1:0] addr_map_iC,
  output idx_t idx_oA,
  output idx_t idx_oB,
  output idx_t idx_oC,
  output logic dec_valid_oA,
  output logic dec_valid_oB,
  output logic dec_valid_oC,
  output logic dec_error_oA,
  output logic dec_error_oB,
  output logic dec_error_oC,
  input logic en_default_idx_iA,
  input logic en_default_idx_iB,
  input logic en_default_idx_iC,
  input idx_t default_idx_iA,
  input idx_t default_idx_iB,
  input idx_t default_idx_iC
);

addr_decode_dyncTMR #(.NoIndices(NoIndices), .NoRules(NoRules), .addr_t(addr_t), .rule_t(rule_t), .Napot(Napot)) i_addr_decode_dync (
    .addr_iA(addr_iA),
    .addr_iB(addr_iB),
    .addr_iC(addr_iC),
    .addr_map_iA(addr_map_iA),
    .addr_map_iB(addr_map_iB),
    .addr_map_iC(addr_map_iC),
    .idx_oA(idx_oA),
    .idx_oB(idx_oB),
    .idx_oC(idx_oC),
    .dec_valid_oA(dec_valid_oA),
    .dec_valid_oB(dec_valid_oB),
    .dec_valid_oC(dec_valid_oC),
    .dec_error_oA(dec_error_oA),
    .dec_error_oB(dec_error_oB),
    .dec_error_oC(dec_error_oC),
    .en_default_idx_iA(en_default_idx_iA),
    .en_default_idx_iB(en_default_idx_iB),
    .en_default_idx_iC(en_default_idx_iC),
    .default_idx_iA(default_idx_iA),
    .default_idx_iB(default_idx_iB),
    .default_idx_iC(default_idx_iC),
    .config_ongoing_iA(1'b0),
    .config_ongoing_iB(1'b0),
    .config_ongoing_iC(1'b0)
  );
endmodule

