/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/floo_route_xymaskTMR.sv                                                *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:42                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/floo_route_xymask.sv                                                     *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912                           *
 *           Modification time : 2025-12-30 16:42:21.746148                                         *
 *           File Size         : 4583                                                               *
 *           MD5 hash          : ed3ae8342abee067714d797bf12fe6cb                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_route_xymaskTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 0,
  parameter bit FwdMode = 1'b1,
  parameter type         flit_t        = logic,
  parameter type         id_t          = logic
) (
  input flit_t channel_iA,
  input flit_t channel_iB,
  input flit_t channel_iC,
  input id_t xy_id_iA,
  input id_t xy_id_iB,
  input id_t xy_id_iC,
  output logic [NumRoutes - 1:0] route_sel_oA,
  output logic [NumRoutes - 1:0] route_sel_oB,
  output logic [NumRoutes - 1:0] route_sel_oC
);
logic [NumRoutes - 1:0] route_selA;
logic [NumRoutes - 1:0] route_selB;
logic [NumRoutes - 1:0] route_selC;
id_t dst_idA;
id_t dst_idB;
id_t dst_idC;
id_t mask_inA;
id_t mask_inB;
id_t mask_inC;
id_t src_idA;
id_t src_idB;
id_t src_idC;
id_t dst_id_maxA;
id_t dst_id_maxB;
id_t dst_id_maxC;
id_t dst_id_minA;
id_t dst_id_minB;
id_t dst_id_minC;
logic x_matchedA;
logic x_matchedB;
logic x_matchedC;
logic y_matchedA;
logic y_matchedB;
logic y_matchedC;
assign dst_idA = (FwdMode) ? channel_iA.hdr.dst_id : channel_iA.hdr.src_id;
assign dst_idB = (FwdMode) ? channel_iB.hdr.dst_id : channel_iB.hdr.src_id;
assign dst_idC = (FwdMode) ? channel_iC.hdr.dst_id : channel_iC.hdr.src_id;
assign src_idA = (FwdMode) ? channel_iA.hdr.src_id : channel_iA.hdr.dst_id;
assign src_idB = (FwdMode) ? channel_iB.hdr.src_id : channel_iB.hdr.dst_id;
assign src_idC = (FwdMode) ? channel_iC.hdr.src_id : channel_iC.hdr.dst_id;
assign mask_inA = (FwdMode&&channel_iA.hdr.commtype==ParallelReduction) ? '0 : channel_iA.hdr.mask;
assign mask_inB = (FwdMode&&channel_iB.hdr.commtype==ParallelReduction) ? '0 : channel_iB.hdr.mask;
assign mask_inC = (FwdMode&&channel_iC.hdr.commtype==ParallelReduction) ? '0 : channel_iC.hdr.mask;
assign dst_id_maxA.x = dst_idA.x|mask_inA.x;
assign dst_id_maxB.x = dst_idB.x|mask_inB.x;
assign dst_id_maxC.x = dst_idC.x|mask_inC.x;
assign dst_id_maxA.y = dst_idA.y|mask_inA.y;
assign dst_id_maxB.y = dst_idB.y|mask_inB.y;
assign dst_id_maxC.y = dst_idC.y|mask_inC.y;
assign dst_id_minA.x = dst_idA.x& (~ mask_inA.x ) ;
assign dst_id_minB.x = dst_idB.x& (~ mask_inB.x ) ;
assign dst_id_minC.x = dst_idC.x& (~ mask_inC.x ) ;
assign dst_id_minA.y = dst_idA.y& (~ mask_inA.y ) ;
assign dst_id_minB.y = dst_idB.y& (~ mask_inB.y ) ;
assign dst_id_minC.y = dst_idC.y& (~ mask_inC.y ) ;
assign x_matchedA = & (mask_inA.x|~(xy_id_iA.x^dst_idA.x)) ;
assign x_matchedB = & (mask_inB.x|~(xy_id_iB.x^dst_idB.x)) ;
assign x_matchedC = & (mask_inC.x|~(xy_id_iC.x^dst_idC.x)) ;
assign y_matchedA = & (mask_inA.y|~(xy_id_iA.y^dst_idA.y)) ;
assign y_matchedB = & (mask_inB.y|~(xy_id_iB.y^dst_idB.y)) ;
assign y_matchedC = & (mask_inC.y|~(xy_id_iC.y^dst_idC.y)) ;

always_comb
  begin
    route_selA = '0;
    if (FwdMode)
      begin : gen_out_maskA
        if (x_matchedA&&y_matchedA)
          begin
            route_selA[Eject] = 1;
          end

        if (xy_id_iA.y==src_idA.y)
          begin
            if (xy_id_iA.x>=src_idA.x&&xy_id_iA.x<dst_id_maxA.x)
              begin
                route_selA[East] = 1;
              end

            if (xy_id_iA.x<=src_idA.x&&xy_id_iA.x>dst_id_minA.x)
              begin
                route_selA[West] = 1;
              end

          end

        if (x_matchedA)
          begin
            if (xy_id_iA.y>=src_idA.y&&xy_id_iA.y<dst_id_maxA.y)
              begin
                route_selA[North] = 1;
              end

            if (xy_id_iA.y<=src_idA.y&&xy_id_iA.y>dst_id_minA.y)
              begin
                route_selA[South] = 1;
              end

          end

      end
    else
      begin : gen_in_maskA
        if (x_matchedA&&y_matchedA)
          begin
            route_selA[Eject] = 1;
          end

        if (xy_id_iA.x==src_idA.x)
          begin
            if (xy_id_iA.y>=src_idA.y&&xy_id_iA.y<dst_id_maxA.y)
              begin
                route_selA[North] = 1;
              end

            if (xy_id_iA.y<=src_idA.y&&xy_id_iA.y>dst_id_minA.y)
              begin
                route_selA[South] = 1;
              end

          end

        if (y_matchedA)
          begin
            if (xy_id_iA.x>=src_idA.x&&xy_id_iA.x<dst_id_maxA.x)
              begin
                route_selA[East] = 1;
              end

            if (xy_id_iA.x<=src_idA.x&&xy_id_iA.x>dst_id_minA.x)
              begin
                route_selA[West] = 1;
              end

          end

      end
  end

always_comb
  begin
    route_selB = '0;
    if (FwdMode)
      begin : gen_out_maskB
        if (x_matchedB&&y_matchedB)
          begin
            route_selB[Eject] = 1;
          end

        if (xy_id_iB.y==src_idB.y)
          begin
            if (xy_id_iB.x>=src_idB.x&&xy_id_iB.x<dst_id_maxB.x)
              begin
                route_selB[East] = 1;
              end

            if (xy_id_iB.x<=src_idB.x&&xy_id_iB.x>dst_id_minB.x)
              begin
                route_selB[West] = 1;
              end

          end

        if (x_matchedB)
          begin
            if (xy_id_iB.y>=src_idB.y&&xy_id_iB.y<dst_id_maxB.y)
              begin
                route_selB[North] = 1;
              end

            if (xy_id_iB.y<=src_idB.y&&xy_id_iB.y>dst_id_minB.y)
              begin
                route_selB[South] = 1;
              end

          end

      end
    else
      begin : gen_in_maskB
        if (x_matchedB&&y_matchedB)
          begin
            route_selB[Eject] = 1;
          end

        if (xy_id_iB.x==src_idB.x)
          begin
            if (xy_id_iB.y>=src_idB.y&&xy_id_iB.y<dst_id_maxB.y)
              begin
                route_selB[North] = 1;
              end

            if (xy_id_iB.y<=src_idB.y&&xy_id_iB.y>dst_id_minB.y)
              begin
                route_selB[South] = 1;
              end

          end

        if (y_matchedB)
          begin
            if (xy_id_iB.x>=src_idB.x&&xy_id_iB.x<dst_id_maxB.x)
              begin
                route_selB[East] = 1;
              end

            if (xy_id_iB.x<=src_idB.x&&xy_id_iB.x>dst_id_minB.x)
              begin
                route_selB[West] = 1;
              end

          end

      end
  end

always_comb
  begin
    route_selC = '0;
    if (FwdMode)
      begin : gen_out_maskC
        if (x_matchedC&&y_matchedC)
          begin
            route_selC[Eject] = 1;
          end

        if (xy_id_iC.y==src_idC.y)
          begin
            if (xy_id_iC.x>=src_idC.x&&xy_id_iC.x<dst_id_maxC.x)
              begin
                route_selC[East] = 1;
              end

            if (xy_id_iC.x<=src_idC.x&&xy_id_iC.x>dst_id_minC.x)
              begin
                route_selC[West] = 1;
              end

          end

        if (x_matchedC)
          begin
            if (xy_id_iC.y>=src_idC.y&&xy_id_iC.y<dst_id_maxC.y)
              begin
                route_selC[North] = 1;
              end

            if (xy_id_iC.y<=src_idC.y&&xy_id_iC.y>dst_id_minC.y)
              begin
                route_selC[South] = 1;
              end

          end

      end
    else
      begin : gen_in_maskC
        if (x_matchedC&&y_matchedC)
          begin
            route_selC[Eject] = 1;
          end

        if (xy_id_iC.x==src_idC.x)
          begin
            if (xy_id_iC.y>=src_idC.y&&xy_id_iC.y<dst_id_maxC.y)
              begin
                route_selC[North] = 1;
              end

            if (xy_id_iC.y<=src_idC.y&&xy_id_iC.y>dst_id_minC.y)
              begin
                route_selC[South] = 1;
              end

          end

        if (y_matchedC)
          begin
            if (xy_id_iC.x>=src_idC.x&&xy_id_iC.x<dst_id_maxC.x)
              begin
                route_selC[East] = 1;
              end

            if (xy_id_iC.x<=src_idC.x&&xy_id_iC.x>dst_id_minC.x)
              begin
                route_selC[West] = 1;
              end

          end

      end
  end
assign route_sel_oA = route_selA;
assign route_sel_oB = route_selB;
assign route_sel_oC = route_selC;
endmodule

