/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/floo_routerTMR.sv                                                      *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:41                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/floo_router.sv                                                           *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912                           *
 *           Modification time : 2025-12-30 16:49:00.939944                                         *
 *           File Size         : 14539                                                              *
 *           MD5 hash          : f8ebd3e200fc091f7ad275731c3a5399                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`include "common_cells/assertions.svh"
`include "common_cells/registers.svh"
module floo_routerTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 0,
  parameter int unsigned NumInput = NumRoutes,
  parameter int unsigned NumOutput = NumRoutes,
  parameter int unsigned NumVirtChannels = 0,
  parameter int unsigned NumPhysChannels = 1,
  parameter int unsigned InFifoDepth = 0,
  parameter int unsigned OutFifoDepth = 0,
  parameter route_algo_e RouteAlgo = IdTable,
  parameter int unsigned IdWidth = 0,
  parameter type         id_t             = logic[IdWidth-1:0],
  parameter int unsigned NumAddrRules = 1,
  parameter bit XYRouteOpt = 1'b1,
  parameter bit NoLoopback = 1'b1,
  parameter bit EnMultiCast = 1'b0,
  parameter bit EnReduction = 1'b0,
  parameter type         addr_rule_t      = logic,
  parameter type         flit_t           = logic,
  parameter type         payload_t        = logic,
  parameter payload_t NarrowRspMask = '0,
  parameter payload_t WideRspMask = '0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic test_enable_iA,
  input logic test_enable_iB,
  input logic test_enable_iC,
  input id_t xy_id_iA,
  input id_t xy_id_iB,
  input id_t xy_id_iC,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_iA,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_iB,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_iC,
  input logic [NumInput - 1:0] [NumVirtChannels - 1:0] valid_iA,
  input logic [NumInput - 1:0] [NumVirtChannels - 1:0] valid_iB,
  input logic [NumInput - 1:0] [NumVirtChannels - 1:0] valid_iC,
  output logic [NumInput - 1:0] [NumVirtChannels - 1:0] ready_oA,
  output logic [NumInput - 1:0] [NumVirtChannels - 1:0] ready_oB,
  output logic [NumInput - 1:0] [NumVirtChannels - 1:0] ready_oC,
  input flit_t [NumInput - 1:0] [NumPhysChannels - 1:0] data_iA,
  input flit_t [NumInput - 1:0] [NumPhysChannels - 1:0] data_iB,
  input flit_t [NumInput - 1:0] [NumPhysChannels - 1:0] data_iC,
  output logic [NumOutput - 1:0] [NumVirtChannels - 1:0] valid_oA,
  output logic [NumOutput - 1:0] [NumVirtChannels - 1:0] valid_oB,
  output logic [NumOutput - 1:0] [NumVirtChannels - 1:0] valid_oC,
  input logic [NumOutput - 1:0] [NumVirtChannels - 1:0] ready_iA,
  input logic [NumOutput - 1:0] [NumVirtChannels - 1:0] ready_iB,
  input logic [NumOutput - 1:0] [NumVirtChannels - 1:0] ready_iC,
  output flit_t [NumOutput - 1:0] [NumPhysChannels - 1:0] data_oA,
  output flit_t [NumOutput - 1:0] [NumPhysChannels - 1:0] data_oB,
  output flit_t [NumOutput - 1:0] [NumPhysChannels - 1:0] data_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire past_handshakes_qTmrErrorC;
wire [NumOutput - 1:0] [NumVirtChannels - 1:0] i_wormhole_arbitertmrErrorC;
wire [NumOutput - 1:0] [NumVirtChannels - 1:0] i_stream_fifo2tmrErrorC;
wire [NumOutput - 1:0] i_vc_arbitertmrErrorC;
wire [NumInput - 1:0] [NumVirtChannels - 1:0] i_stream_fifotmrErrorC;
wire [NumInput - 1:0] [NumVirtChannels - 1:0] i_route_selecttmrErrorC;
wire [NumOutput - 1:0] [NumVirtChannels - 1:0] i_output_arbitertmrErrorC;
wire past_handshakes_qTmrErrorB;
wire [NumOutput - 1:0] [NumVirtChannels - 1:0] i_wormhole_arbitertmrErrorB;
wire [NumOutput - 1:0] [NumVirtChannels - 1:0] i_stream_fifo2tmrErrorB;
wire [NumOutput - 1:0] i_vc_arbitertmrErrorB;
wire [NumInput - 1:0] [NumVirtChannels - 1:0] i_stream_fifotmrErrorB;
wire [NumInput - 1:0] [NumVirtChannels - 1:0] i_route_selecttmrErrorB;
wire [NumOutput - 1:0] [NumVirtChannels - 1:0] i_output_arbitertmrErrorB;
wire past_handshakes_qTmrErrorA;
wire [NumOutput - 1:0] [NumVirtChannels - 1:0] i_wormhole_arbitertmrErrorA;
wire [NumOutput - 1:0] [NumVirtChannels - 1:0] i_stream_fifo2tmrErrorA;
wire [NumOutput - 1:0] i_vc_arbitertmrErrorA;
wire [NumInput - 1:0] [NumVirtChannels - 1:0] i_stream_fifotmrErrorA;
wire [NumInput - 1:0] [NumVirtChannels - 1:0] i_route_selecttmrErrorA;
wire [NumOutput - 1:0] [NumVirtChannels - 1:0] i_output_arbitertmrErrorA;
flit_t [NumInput - 1:0] [NumVirtChannels - 1:0] in_dataA;
flit_t [NumInput - 1:0] [NumVirtChannels - 1:0] in_dataB;
flit_t [NumInput - 1:0] [NumVirtChannels - 1:0] in_dataC;
flit_t [NumInput - 1:0] [NumVirtChannels - 1:0] in_routed_dataA;
flit_t [NumInput - 1:0] [NumVirtChannels - 1:0] in_routed_dataB;
flit_t [NumInput - 1:0] [NumVirtChannels - 1:0] in_routed_dataC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] in_validA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] in_validB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] in_validC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] in_readyA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] in_readyB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] in_readyC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] route_maskA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] route_maskB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] route_maskC;
for(genvar in = 0; in<NumInput; in++)
  begin : gen_input
    for(genvar v = 0; v<NumVirtChannels; v++)
          begin : gen_virt_input
logic [cf_math_pkg::idx_width(NumPhysChannels) - 1:0] in_pA;
logic [cf_math_pkg::idx_width(NumPhysChannels) - 1:0] in_pB;
logic [cf_math_pkg::idx_width(NumPhysChannels) - 1:0] in_pC;
        if (NumPhysChannels==1)
                  begin : gen_single_phys
            assign in_pA = '0;
            assign in_pB = '0;
            assign in_pC = '0;
          end

        else
                  if (NumPhysChannels==NumVirtChannels)
                      begin : gen_virt_eq_phys
              assign in_pA = v;
              assign in_pB = v;
              assign in_pC = v;
            end

          else
                      begin : gen_odd_phys
            end

        (* ungroup *) stream_fifo_optimal_wrapTMR #(.Depth(InFifoDepth), .type_t(flit_t)) i_stream_fifo (
            .clk_iA(clk_iA),
            .clk_iB(clk_iB),
            .clk_iC(clk_iC),
            .rst_niA(rst_niA),
            .rst_niB(rst_niB),
            .rst_niC(rst_niC),
            .testmode_iA(test_enable_iA),
            .testmode_iB(test_enable_iB),
            .testmode_iC(test_enable_iC),
            .flush_iA(1'b0),
            .flush_iB(1'b0),
            .flush_iC(1'b0),
            .usage_oA(),
            .usage_oB(),
            .usage_oC(),
            .data_iA(data_iA[in][in_pA]),
            .data_iB(data_iB[in][in_pB]),
            .data_iC(data_iC[in][in_pC]),
            .valid_iA(valid_iA[in][v]),
            .valid_iB(valid_iB[in][v]),
            .valid_iC(valid_iC[in][v]),
            .ready_oA(ready_oA[in][v]),
            .ready_oB(ready_oB[in][v]),
            .ready_oC(ready_oC[in][v]),
            .data_oA(in_dataA[in][v]),
            .data_oB(in_dataB[in][v]),
            .data_oC(in_dataC[in][v]),
            .valid_oA(in_validA[in][v]),
            .valid_oB(in_validB[in][v]),
            .valid_oC(in_validC[in][v]),
            .ready_iA(in_readyA[in][v]),
            .ready_iB(in_readyB[in][v]),
            .ready_iC(in_readyC[in][v]),
            .tmrErrorA(i_stream_fifotmrErrorA[in][v]),
            .tmrErrorB(i_stream_fifotmrErrorB[in][v]),
            .tmrErrorC(i_stream_fifotmrErrorC[in][v])
          );

        floo_route_selectTMR #(.NumRoutes(NumOutput), .flit_t(flit_t), .RouteAlgo(RouteAlgo), .IdWidth(IdWidth), .id_t(id_t), .NumAddrRules(NumAddrRules), .addr_rule_t(addr_rule_t), .EnMultiCast(EnMultiCast)) i_route_select (
            .clk_iA(clk_iA),
            .clk_iB(clk_iB),
            .clk_iC(clk_iC),
            .rst_niA(rst_niA),
            .rst_niB(rst_niB),
            .rst_niC(rst_niC),
            .test_enable_iA(test_enable_iA),
            .test_enable_iB(test_enable_iB),
            .test_enable_iC(test_enable_iC),
            .xy_id_iA(xy_id_iA),
            .xy_id_iB(xy_id_iB),
            .xy_id_iC(xy_id_iC),
            .id_route_map_iA(id_route_map_iA),
            .id_route_map_iB(id_route_map_iB),
            .id_route_map_iC(id_route_map_iC),
            .channel_iA(in_dataA[in][v]),
            .channel_iB(in_dataB[in][v]),
            .channel_iC(in_dataC[in][v]),
            .valid_iA(in_validA[in][v]),
            .valid_iB(in_validB[in][v]),
            .valid_iC(in_validC[in][v]),
            .ready_iA(in_readyA[in][v]),
            .ready_iB(in_readyB[in][v]),
            .ready_iC(in_readyC[in][v]),
            .channel_oA(in_routed_dataA[in][v]),
            .channel_oB(in_routed_dataB[in][v]),
            .channel_oC(in_routed_dataC[in][v]),
            .route_sel_oA(route_maskA[in][v]),
            .route_sel_oB(route_maskB[in][v]),
            .route_sel_oC(route_maskC[in][v]),
            .route_sel_id_oA(),
            .route_sel_id_oB(),
            .route_sel_id_oC(),
            .tmrErrorA(i_route_selecttmrErrorA[in][v]),
            .tmrErrorB(i_route_selecttmrErrorB[in][v]),
            .tmrErrorC(i_route_selecttmrErrorC[in][v])
          );
      end
  end
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_validA;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_validB;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_validC;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_readyA;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_readyB;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_readyC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] masked_valid_transposedA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] masked_valid_transposedB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] masked_valid_transposedC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] masked_ready_transposedA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] masked_ready_transposedB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] masked_ready_transposedC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_qA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_qB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_qC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_dA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_dB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_dC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_qVotedA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_qVotedB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_qVotedC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] current_handshakesA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] current_handshakesB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] current_handshakesC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] all_handshakesA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] all_handshakesB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] all_handshakesC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] ignore_routesA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] ignore_routesB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] ignore_routesC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] expected_handshakesA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] expected_handshakesB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] expected_handshakesC;
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_dataA;
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_dataB;
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_dataC;
for(genvar in = 0; in<NumInput; in++)
  begin : gen_hs_input
    for(genvar v = 0; v<NumVirtChannels; v++)
          begin : gen_hs_virt
        for(genvar out = 0; out<NumOutput; out++)
                  begin : gen_hs_output
            if ((NoLoopback&&(in==out))||((RouteAlgo==XYRouting)&&XYRouteOpt&&(in==South||in==North)&&(out==East||out==West)))
                          begin : gen_no_conn
                assign masked_ready_transposedA[in][v][out] = '0;
                assign masked_ready_transposedB[in][v][out] = '0;
                assign masked_ready_transposedC[in][v][out] = '0;
                assign masked_validA[out][v][in] = '0;
                assign masked_validB[out][v][in] = '0;
                assign masked_validC[out][v][in] = '0;
                assign masked_dataA[out][v][in] = '0;
                assign masked_dataB[out][v][in] = '0;
                assign masked_dataC[out][v][in] = '0;
              end

            else
                          begin : gen_conn
                assign masked_ready_transposedA[in][v][out] = masked_readyA[out][v][in];
                assign masked_ready_transposedB[in][v][out] = masked_readyB[out][v][in];
                assign masked_ready_transposedC[in][v][out] = masked_readyC[out][v][in];
                if (EnMultiCast)
                                  begin
                    assign masked_validA[out][v][in] = in_validA[in][v]&route_maskA[in][v][out]&~past_handshakes_qVotedA[in][v][out];
                    assign masked_validB[out][v][in] = in_validB[in][v]&route_maskB[in][v][out]&~past_handshakes_qVotedB[in][v][out];
                    assign masked_validC[out][v][in] = in_validC[in][v]&route_maskC[in][v][out]&~past_handshakes_qVotedC[in][v][out];
                  end

                else
                                  begin
                    assign masked_validA[out][v][in] = in_validA[in][v]&route_maskA[in][v][out];
                    assign masked_validB[out][v][in] = in_validB[in][v]&route_maskB[in][v][out];
                    assign masked_validC[out][v][in] = in_validC[in][v]&route_maskC[in][v][out];
                  end
                assign masked_dataA[out][v][in] = in_routed_dataA[in][v];
                assign masked_dataB[out][v][in] = in_routed_dataB[in][v];
                assign masked_dataC[out][v][in] = in_routed_dataC[in][v];
              end
            assign masked_valid_transposedA[in][v][out] = masked_validA[out][v][in];
            assign masked_valid_transposedB[in][v][out] = masked_validB[out][v][in];
            assign masked_valid_transposedC[in][v][out] = masked_validC[out][v][in];
          end
        if (!EnMultiCast)
                  begin : gen_unicast
            assign in_readyA[in][v] = | (masked_ready_transposedA[in][v]&route_maskA[in][v]) ;
            assign in_readyB[in][v] = | (masked_ready_transposedB[in][v]&route_maskB[in][v]) ;
            assign in_readyC[in][v] = | (masked_ready_transposedC[in][v]&route_maskC[in][v]) ;
          end

        else
                  begin : gen_multicast
            assign current_handshakesA[in][v] = masked_valid_transposedA[in][v]&masked_ready_transposedA[in][v];
            assign current_handshakesB[in][v] = masked_valid_transposedB[in][v]&masked_ready_transposedB[in][v];
            assign current_handshakesC[in][v] = masked_valid_transposedC[in][v]&masked_ready_transposedC[in][v];
            assign past_handshakes_dA[in][v] = (in_readyA[in][v]&in_validA[in][v]) ? '0 : (past_handshakes_qVotedA[in][v]|current_handshakesA[in][v]);
            assign past_handshakes_dB[in][v] = (in_readyB[in][v]&in_validB[in][v]) ? '0 : (past_handshakes_qVotedB[in][v]|current_handshakesB[in][v]);
            assign past_handshakes_dC[in][v] = (in_readyC[in][v]&in_validC[in][v]) ? '0 : (past_handshakes_qVotedC[in][v]|current_handshakesC[in][v]);
            assign all_handshakesA[in][v] = past_handshakes_qVotedA[in][v]|current_handshakesA[in][v];
            assign all_handshakesB[in][v] = past_handshakes_qVotedB[in][v]|current_handshakesB[in][v];
            assign all_handshakesC[in][v] = past_handshakes_qVotedC[in][v]|current_handshakesC[in][v];
            assign ignore_routesA[in][v] = NoLoopback ? (1<<in) : '0;
            assign ignore_routesB[in][v] = NoLoopback ? (1<<in) : '0;
            assign ignore_routesC[in][v] = NoLoopback ? (1<<in) : '0;
            assign expected_handshakesA[in][v] = route_maskA[in][v]&~ignore_routesA[in][v];
            assign expected_handshakesB[in][v] = route_maskB[in][v]&~ignore_routesB[in][v];
            assign expected_handshakesC[in][v] = route_maskC[in][v]&~ignore_routesC[in][v];
            assign in_readyA[in][v] = & (all_handshakesA[in][v]|~expected_handshakesA[in][v]) ;
            assign in_readyB[in][v] = & (all_handshakesB[in][v]|~expected_handshakesB[in][v]) ;
            assign in_readyC[in][v] = & (all_handshakesC[in][v]|~expected_handshakesC[in][v]) ;
          end
      end
  end
if (EnMultiCast)
  begin : gen_mcast_pasthandshake

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin
        if (!rst_niA)
          begin
            past_handshakes_qA <= '0;
          end
        else
          begin
            past_handshakes_qA <= past_handshakes_dA;
          end
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin
        if (!rst_niB)
          begin
            past_handshakes_qB <= '0;
          end
        else
          begin
            past_handshakes_qB <= past_handshakes_dB;
          end
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin
        if (!rst_niC)
          begin
            past_handshakes_qC <= '0;
          end
        else
          begin
            past_handshakes_qC <= past_handshakes_dC;
          end
      end

    majorityVoter #(.WIDTH( ((((NumInput-1)>0) ? (NumInput-1) : - ( NumInput-1 ) )+1)  *  ((((NumVirtChannels-1)>0) ? (NumVirtChannels-1) : - ( NumVirtChannels-1 ) )+1)  *  ((((NumOutput-1)>0) ? (NumOutput-1) : - ( NumOutput-1 ) )+1) )) past_handshakes_qVoterA (
        .inA(past_handshakes_qA),
        .inB(past_handshakes_qB),
        .inC(past_handshakes_qC),
        .out(past_handshakes_qVotedA),
        .tmrErr(past_handshakes_qTmrErrorA)
      );

    majorityVoter #(.WIDTH( ((((NumInput-1)>0) ? (NumInput-1) : - ( NumInput-1 ) )+1)  *  ((((NumVirtChannels-1)>0) ? (NumVirtChannels-1) : - ( NumVirtChannels-1 ) )+1)  *  ((((NumOutput-1)>0) ? (NumOutput-1) : - ( NumOutput-1 ) )+1) )) past_handshakes_qVoterB (
        .inA(past_handshakes_qA),
        .inB(past_handshakes_qB),
        .inC(past_handshakes_qC),
        .out(past_handshakes_qVotedB),
        .tmrErr(past_handshakes_qTmrErrorB)
      );

    majorityVoter #(.WIDTH( ((((NumInput-1)>0) ? (NumInput-1) : - ( NumInput-1 ) )+1)  *  ((((NumVirtChannels-1)>0) ? (NumVirtChannels-1) : - ( NumVirtChannels-1 ) )+1)  *  ((((NumOutput-1)>0) ? (NumOutput-1) : - ( NumOutput-1 ) )+1) )) past_handshakes_qVoterC (
        .inA(past_handshakes_qA),
        .inB(past_handshakes_qB),
        .inC(past_handshakes_qC),
        .out(past_handshakes_qVotedC),
        .tmrErr(past_handshakes_qTmrErrorC)
      );
  end
else
  begin : gen_no_mcast
    assign past_handshakes_qTmrErrorA = 1'b0;
    assign past_handshakes_qTmrErrorB = 1'b0;
    assign past_handshakes_qTmrErrorC = 1'b0;
  end
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] out_dataA;
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] out_dataB;
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] out_dataC;
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_dataA;
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_dataB;
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_dataC;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_validA;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_validB;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_validC;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_readyA;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_readyB;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_readyC;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_validA;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_validB;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_validC;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_readyA;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_readyB;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_readyC;
for(genvar out = 0; out<NumOutput; out++)
  begin : gen_output
    for(genvar v = 0; v<NumVirtChannels; v++)
          begin : gen_virt_output
        if (!EnReduction)
                  begin : gen_wh_arb

            floo_wormhole_arbiterTMR #(.NumRoutes(NumInput), .flit_t(flit_t)) i_wormhole_arbiter (
                .clk_iA(clk_iA),
                .clk_iB(clk_iB),
                .clk_iC(clk_iC),
                .rst_niA(rst_niA),
                .rst_niB(rst_niB),
                .rst_niC(rst_niC),
                .valid_iA(masked_validA[out][v]),
                .valid_iB(masked_validB[out][v]),
                .valid_iC(masked_validC[out][v]),
                .ready_oA(masked_readyA[out][v]),
                .ready_oB(masked_readyB[out][v]),
                .ready_oC(masked_readyC[out][v]),
                .data_iA(masked_dataA[out][v]),
                .data_iB(masked_dataB[out][v]),
                .data_iC(masked_dataC[out][v]),
                .valid_oA(out_validA[out][v]),
                .valid_oB(out_validB[out][v]),
                .valid_oC(out_validC[out][v]),
                .ready_iA(out_readyA[out][v]),
                .ready_iB(out_readyB[out][v]),
                .ready_iC(out_readyC[out][v]),
                .data_oA(out_dataA[out][v]),
                .data_oB(out_dataB[out][v]),
                .data_oC(out_dataC[out][v]),
                .tmrErrorA(i_wormhole_arbitertmrErrorA[out][v]),
                .tmrErrorB(i_wormhole_arbitertmrErrorB[out][v]),
                .tmrErrorC(i_wormhole_arbitertmrErrorC[out][v])
              );

            assign i_output_arbitertmrErrorA[out][v] = 1'b0;
            assign i_output_arbitertmrErrorB[out][v] = 1'b0;
            assign i_output_arbitertmrErrorC[out][v] = 1'b0;
          end

        else
                  begin : gen_red_arb

            floo_output_arbiterTMR #(.NumRoutes(NumInput), .flit_t(flit_t), .payload_t(payload_t), .NarrowRspMask(NarrowRspMask), .WideRspMask(WideRspMask), .id_t(id_t)) i_output_arbiter (
                .clk_iA(clk_iA),
                .clk_iB(clk_iB),
                .clk_iC(clk_iC),
                .rst_niA(rst_niA),
                .rst_niB(rst_niB),
                .rst_niC(rst_niC),
                .valid_iA(masked_validA[out][v]),
                .valid_iB(masked_validB[out][v]),
                .valid_iC(masked_validC[out][v]),
                .ready_oA(masked_readyA[out][v]),
                .ready_oB(masked_readyB[out][v]),
                .ready_oC(masked_readyC[out][v]),
                .data_iA(masked_dataA[out][v]),
                .data_iB(masked_dataB[out][v]),
                .data_iC(masked_dataC[out][v]),
                .xy_id_iA(xy_id_iA),
                .xy_id_iB(xy_id_iB),
                .xy_id_iC(xy_id_iC),
                .valid_oA(out_validA[out][v]),
                .valid_oB(out_validB[out][v]),
                .valid_oC(out_validC[out][v]),
                .ready_iA(out_readyA[out][v]),
                .ready_iB(out_readyB[out][v]),
                .ready_iC(out_readyC[out][v]),
                .data_oA(out_dataA[out][v]),
                .data_oB(out_dataB[out][v]),
                .data_oC(out_dataC[out][v]),
                .tmrErrorA(i_output_arbitertmrErrorA[out][v]),
                .tmrErrorB(i_output_arbitertmrErrorB[out][v]),
                .tmrErrorC(i_output_arbitertmrErrorC[out][v])
              );

            assign i_wormhole_arbitertmrErrorA[out][v] = 1'b0;
            assign i_wormhole_arbitertmrErrorB[out][v] = 1'b0;
            assign i_wormhole_arbitertmrErrorC[out][v] = 1'b0;
          end
        if (OutFifoDepth>0)
                  begin : gen_out_fifo

            (* ungroup *) stream_fifo_optimal_wrapTMR #(.Depth(OutFifoDepth), .type_t(flit_t)) i_stream_fifo (
                .clk_iA(clk_iA),
                .clk_iB(clk_iB),
                .clk_iC(clk_iC),
                .rst_niA(rst_niA),
                .rst_niB(rst_niB),
                .rst_niC(rst_niC),
                .testmode_iA(test_enable_iA),
                .testmode_iB(test_enable_iB),
                .testmode_iC(test_enable_iC),
                .flush_iA(1'b0),
                .flush_iB(1'b0),
                .flush_iC(1'b0),
                .usage_oA(),
                .usage_oB(),
                .usage_oC(),
                .data_iA(out_dataA[out][v]),
                .data_iB(out_dataB[out][v]),
                .data_iC(out_dataC[out][v]),
                .valid_iA(out_validA[out][v]),
                .valid_iB(out_validB[out][v]),
                .valid_iC(out_validC[out][v]),
                .ready_oA(out_readyA[out][v]),
                .ready_oB(out_readyB[out][v]),
                .ready_oC(out_readyC[out][v]),
                .data_oA(out_buffered_dataA[out][v]),
                .data_oB(out_buffered_dataB[out][v]),
                .data_oC(out_buffered_dataC[out][v]),
                .valid_oA(out_buffered_validA[out][v]),
                .valid_oB(out_buffered_validB[out][v]),
                .valid_oC(out_buffered_validC[out][v]),
                .ready_iA(out_buffered_readyA[out][v]),
                .ready_iB(out_buffered_readyB[out][v]),
                .ready_iC(out_buffered_readyC[out][v]),
                .tmrErrorA(i_stream_fifo2tmrErrorA[out][v]),
                .tmrErrorB(i_stream_fifo2tmrErrorB[out][v]),
                .tmrErrorC(i_stream_fifo2tmrErrorC[out][v])
              );
          end

        else
                  begin : gen_no_out_fifo
            assign out_buffered_dataA[out][v] = out_dataA[out][v];
            assign out_buffered_dataB[out][v] = out_dataB[out][v];
            assign out_buffered_dataC[out][v] = out_dataC[out][v];
            assign out_buffered_validA[out][v] = out_validA[out][v];
            assign out_buffered_validB[out][v] = out_validB[out][v];
            assign out_buffered_validC[out][v] = out_validC[out][v];
            assign out_readyA[out][v] = out_buffered_readyA[out][v];
            assign out_readyB[out][v] = out_buffered_readyB[out][v];
            assign out_readyC[out][v] = out_buffered_readyC[out][v];

            assign i_stream_fifo2tmrErrorA[out][v] = 1'b0;
            assign i_stream_fifo2tmrErrorB[out][v] = 1'b0;
            assign i_stream_fifo2tmrErrorC[out][v] = 1'b0;
          end
      end

    floo_vc_arbiterTMR #(.NumVirtChannels(NumVirtChannels), .flit_t(flit_t), .NumPhysChannels(NumPhysChannels)) i_vc_arbiter (
        .clk_iA(clk_iA),
        .clk_iB(clk_iB),
        .clk_iC(clk_iC),
        .rst_niA(rst_niA),
        .rst_niB(rst_niB),
        .rst_niC(rst_niC),
        .valid_iA(out_buffered_validA[out]),
        .valid_iB(out_buffered_validB[out]),
        .valid_iC(out_buffered_validC[out]),
        .ready_oA(out_buffered_readyA[out]),
        .ready_oB(out_buffered_readyB[out]),
        .ready_oC(out_buffered_readyC[out]),
        .data_iA(out_buffered_dataA[out]),
        .data_iB(out_buffered_dataB[out]),
        .data_iC(out_buffered_dataC[out]),
        .ready_iA(ready_iA[out]),
        .ready_iB(ready_iB[out]),
        .ready_iC(ready_iC[out]),
        .valid_oA(valid_oA[out]),
        .valid_oB(valid_oB[out]),
        .valid_oC(valid_oC[out]),
        .data_oA(data_oA[out]),
        .data_oB(data_oB[out]),
        .data_oC(data_oC[out]),
        .tmrErrorA(i_vc_arbitertmrErrorA[out]),
        .tmrErrorB(i_vc_arbitertmrErrorB[out]),
        .tmrErrorC(i_vc_arbitertmrErrorC[out])
      );
  end

assign tmrErrorA = (|i_output_arbitertmrErrorA)|(|i_route_selecttmrErrorA)|(|i_stream_fifotmrErrorA)|(|i_stream_fifo2tmrErrorA)|(|i_vc_arbitertmrErrorA)|(|i_wormhole_arbitertmrErrorA)|past_handshakes_qTmrErrorA;
assign tmrErrorB = (|i_output_arbitertmrErrorB)|(|i_route_selecttmrErrorB)|(|i_stream_fifotmrErrorB)|(|i_stream_fifo2tmrErrorB)|(|i_vc_arbitertmrErrorB)|(|i_wormhole_arbitertmrErrorB)|past_handshakes_qTmrErrorB;
assign tmrErrorC = (|i_output_arbitertmrErrorC)|(|i_route_selecttmrErrorC)|(|i_stream_fifotmrErrorC)|(|i_stream_fifo2tmrErrorC)|(|i_vc_arbitertmrErrorC)|(|i_wormhole_arbitertmrErrorC)|past_handshakes_qTmrErrorC;
endmodule

