/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/floo_output_arbiterTMR.sv                                              *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:43                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/floo_output_arbiter.sv                                                   *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912                           *
 *           Modification time : 2025-12-30 16:37:07.511178                                         *
 *           File Size         : 3390                                                               *
 *           MD5 hash          : 60caaa2b40a2f1d28640bea87275ce52                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`include "common_cells/assertions.svh"
module floo_output_arbiterTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 1,
  parameter type         flit_t     = logic,
  parameter type         payload_t  = logic,
  parameter payload_t NarrowRspMask = '0,
  parameter payload_t WideRspMask = '0,
  parameter type         id_t       = logic
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input id_t xy_id_iA,
  input id_t xy_id_iB,
  input id_t xy_id_iC,
  input logic [NumRoutes - 1:0] valid_iA,
  input logic [NumRoutes - 1:0] valid_iB,
  input logic [NumRoutes - 1:0] valid_iC,
  output logic [NumRoutes - 1:0] ready_oA,
  output logic [NumRoutes - 1:0] ready_oB,
  output logic [NumRoutes - 1:0] ready_oC,
  input flit_t [NumRoutes - 1:0] data_iA,
  input flit_t [NumRoutes - 1:0] data_iB,
  input flit_t [NumRoutes - 1:0] data_iC,
  output logic valid_oA,
  output logic valid_oB,
  output logic valid_oC,
  input logic ready_iA,
  input logic ready_iB,
  input logic ready_iC,
  output flit_t data_oA,
  output flit_t data_oB,
  output flit_t data_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire i_wormhole_arbitertmrErrorC;
wire i_stream_arbitertmrErrorC;
wire i_wormhole_arbitertmrErrorB;
wire i_stream_arbitertmrErrorB;
wire i_wormhole_arbitertmrErrorA;
wire i_stream_arbitertmrErrorA;
flit_t reduce_data_outA;
flit_t reduce_data_outB;
flit_t reduce_data_outC;
flit_t unicast_data_outA;
flit_t unicast_data_outB;
flit_t unicast_data_outC;
logic [NumRoutes - 1:0] reduce_valid_inA;
logic [NumRoutes - 1:0] reduce_valid_inB;
logic [NumRoutes - 1:0] reduce_valid_inC;
logic [NumRoutes - 1:0] unicast_valid_inA;
logic [NumRoutes - 1:0] unicast_valid_inB;
logic [NumRoutes - 1:0] unicast_valid_inC;
logic [NumRoutes - 1:0] reduce_ready_outA;
logic [NumRoutes - 1:0] reduce_ready_outB;
logic [NumRoutes - 1:0] reduce_ready_outC;
logic [NumRoutes - 1:0] unicast_ready_outA;
logic [NumRoutes - 1:0] unicast_ready_outB;
logic [NumRoutes - 1:0] unicast_ready_outC;
logic reduce_valid_outA;
logic reduce_valid_outB;
logic reduce_valid_outC;
logic unicast_valid_outA;
logic unicast_valid_outB;
logic unicast_valid_outC;
logic reduce_ready_inA;
logic reduce_ready_inB;
logic reduce_ready_inC;
logic unicast_ready_inA;
logic unicast_ready_inB;
logic unicast_ready_inC;
logic [NumRoutes - 1:0] reduce_maskA;
logic [NumRoutes - 1:0] reduce_maskB;
logic [NumRoutes - 1:0] reduce_maskC;
for(genvar i = 0; i<NumRoutes; i++)
  begin : gen_reduce_mask
    assign reduce_maskA[i] =  (data_iA[i].hdr.commtype==ParallelReduction) ;
    assign reduce_maskB[i] =  (data_iB[i].hdr.commtype==ParallelReduction) ;
    assign reduce_maskC[i] =  (data_iC[i].hdr.commtype==ParallelReduction) ;
  end
assign unicast_valid_inA = valid_iA&~reduce_maskA;
assign unicast_valid_inB = valid_iB&~reduce_maskB;
assign unicast_valid_inC = valid_iC&~reduce_maskC;

floo_wormhole_arbiterTMR #(.NumRoutes(NumRoutes), .flit_t(flit_t)) i_wormhole_arbiter (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .data_iA(data_iA),
    .data_iB(data_iB),
    .data_iC(data_iC),
    .valid_iA(unicast_valid_inA),
    .valid_iB(unicast_valid_inB),
    .valid_iC(unicast_valid_inC),
    .ready_oA(unicast_ready_outA),
    .ready_oB(unicast_ready_outB),
    .ready_oC(unicast_ready_outC),
    .valid_oA(unicast_valid_outA),
    .valid_oB(unicast_valid_outB),
    .valid_oC(unicast_valid_outC),
    .ready_iA(unicast_ready_inA),
    .ready_iB(unicast_ready_inB),
    .ready_iC(unicast_ready_inC),
    .data_oA(unicast_data_outA),
    .data_oB(unicast_data_outB),
    .data_oC(unicast_data_outC),
    .tmrErrorA(i_wormhole_arbitertmrErrorA),
    .tmrErrorB(i_wormhole_arbitertmrErrorB),
    .tmrErrorC(i_wormhole_arbitertmrErrorC)
  );
assign reduce_valid_inA = valid_iA&reduce_maskA;
assign reduce_valid_inB = valid_iB&reduce_maskB;
assign reduce_valid_inC = valid_iC&reduce_maskC;

floo_reduction_arbiterTMR #(.NumRoutes(NumRoutes), .flit_t(flit_t), .payload_t(payload_t), .id_t(id_t), .NarrowRspMask(NarrowRspMask), .WideRspMask(WideRspMask)) i_reduction_arbiter (
    .xy_id_iA(xy_id_iA),
    .xy_id_iB(xy_id_iB),
    .xy_id_iC(xy_id_iC),
    .data_iA(data_iA),
    .data_iB(data_iB),
    .data_iC(data_iC),
    .valid_iA(reduce_valid_inA),
    .valid_iB(reduce_valid_inB),
    .valid_iC(reduce_valid_inC),
    .ready_oA(reduce_ready_outA),
    .ready_oB(reduce_ready_outB),
    .ready_oC(reduce_ready_outC),
    .valid_oA(reduce_valid_outA),
    .valid_oB(reduce_valid_outB),
    .valid_oC(reduce_valid_outC),
    .ready_iA(reduce_ready_inA),
    .ready_iB(reduce_ready_inB),
    .ready_iC(reduce_ready_inC),
    .data_oA(reduce_data_outA),
    .data_oB(reduce_data_outB),
    .data_oC(reduce_data_outC)
  );

stream_arbiterTMR #(.N_INP(2), .ARBITER("prio"), .DATA_T(flit_t)) i_stream_arbiter (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .inp_data_iA({unicast_data_outA, reduce_data_outA}),
    .inp_data_iB({unicast_data_outB, reduce_data_outB}),
    .inp_data_iC({unicast_data_outC, reduce_data_outC}),
    .inp_valid_iA({unicast_valid_outA, reduce_valid_outA}),
    .inp_valid_iB({unicast_valid_outB, reduce_valid_outB}),
    .inp_valid_iC({unicast_valid_outC, reduce_valid_outC}),
    .inp_ready_oA({unicast_ready_inA, reduce_ready_inA}),
    .inp_ready_oB({unicast_ready_inB, reduce_ready_inB}),
    .inp_ready_oC({unicast_ready_inC, reduce_ready_inC}),
    .oup_data_oA(data_oA),
    .oup_data_oB(data_oB),
    .oup_data_oC(data_oC),
    .oup_valid_oA(valid_oA),
    .oup_valid_oB(valid_oB),
    .oup_valid_oC(valid_oC),
    .oup_ready_iA(ready_iA),
    .oup_ready_iB(ready_iB),
    .oup_ready_iC(ready_iC),
    .tmrErrorA(i_stream_arbitertmrErrorA),
    .tmrErrorB(i_stream_arbitertmrErrorB),
    .tmrErrorC(i_stream_arbitertmrErrorC)
  );
assign ready_oA = (reduce_valid_outA) ? reduce_ready_outA : unicast_ready_outA;
assign ready_oB = (reduce_valid_outB) ? reduce_ready_outB : unicast_ready_outB;
assign ready_oC = (reduce_valid_outC) ? reduce_ready_outC : unicast_ready_outC;
assign tmrErrorA = i_stream_arbitertmrErrorA|i_wormhole_arbitertmrErrorA;
assign tmrErrorB = i_stream_arbitertmrErrorB|i_wormhole_arbitertmrErrorB;
assign tmrErrorC = i_stream_arbitertmrErrorC|i_wormhole_arbitertmrErrorC;
endmodule

