/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/floo_reduction_syncTMR.sv                                              *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:43                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/floo_reduction_sync.sv                                                   *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912                           *
 *           Modification time : 2025-12-30 16:42:04.704988                                         *
 *           File Size         : 2483                                                               *
 *           MD5 hash          : 6bd073fc9bd6b7ab5b4cafe405521bd7                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_reduction_syncTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 1,
  parameter type         arb_idx_t  = logic,
  parameter type         flit_t     = logic,
  parameter type         id_t       = logic
) (
  input arb_idx_t sel_iA,
  input arb_idx_t sel_iB,
  input arb_idx_t sel_iC,
  input flit_t [NumRoutes - 1:0] data_iA,
  input flit_t [NumRoutes - 1:0] data_iB,
  input flit_t [NumRoutes - 1:0] data_iC,
  input logic [NumRoutes - 1:0] valid_iA,
  input logic [NumRoutes - 1:0] valid_iB,
  input logic [NumRoutes - 1:0] valid_iC,
  input id_t xy_id_iA,
  input id_t xy_id_iB,
  input id_t xy_id_iC,
  output logic valid_oA,
  output logic valid_oB,
  output logic valid_oC,
  output logic [NumRoutes - 1:0] in_route_mask_oA,
  output logic [NumRoutes - 1:0] in_route_mask_oB,
  output logic [NumRoutes - 1:0] in_route_mask_oC
);
logic [NumRoutes - 1:0] compare_sameA;
logic [NumRoutes - 1:0] compare_sameB;
logic [NumRoutes - 1:0] compare_sameC;
logic [NumRoutes - 1:0] same_and_validA;
logic [NumRoutes - 1:0] same_and_validB;
logic [NumRoutes - 1:0] same_and_validC;
logic all_reduction_srcs_validA;
logic all_reduction_srcs_validB;
logic all_reduction_srcs_validC;

floo_route_xymaskTMR #(.NumRoutes(NumRoutes), .flit_t(flit_t), .id_t(id_t), .FwdMode(0)) i_route_xymask (
    .channel_iA(data_iA[sel_iA]),
    .channel_iB(data_iB[sel_iB]),
    .channel_iC(data_iC[sel_iC]),
    .xy_id_iA(xy_id_iA),
    .xy_id_iB(xy_id_iB),
    .xy_id_iC(xy_id_iC),
    .route_sel_oA(in_route_mask_oA),
    .route_sel_oB(in_route_mask_oB),
    .route_sel_oC(in_route_mask_oC)
  );
for(genvar in = 0; in<NumRoutes; in++)
  begin : gen_routes
    assign compare_sameA[in] =  ((data_iA[in].hdr.mask==data_iA[sel_iA].hdr.mask)&&(data_iA[in].hdr.dst_id==data_iA[sel_iA].hdr.dst_id)) ;
    assign compare_sameB[in] =  ((data_iB[in].hdr.mask==data_iB[sel_iB].hdr.mask)&&(data_iB[in].hdr.dst_id==data_iB[sel_iB].hdr.dst_id)) ;
    assign compare_sameC[in] =  ((data_iC[in].hdr.mask==data_iC[sel_iC].hdr.mask)&&(data_iC[in].hdr.dst_id==data_iC[sel_iC].hdr.dst_id)) ;
    assign same_and_validA[in] =  (data_iA[sel_iA].hdr.dst_id==xy_id_iA&&in==Eject) || (compare_sameA[in]&valid_iA[in]) ;
    assign same_and_validB[in] =  (data_iB[sel_iB].hdr.dst_id==xy_id_iB&&in==Eject) || (compare_sameB[in]&valid_iB[in]) ;
    assign same_and_validC[in] =  (data_iC[sel_iC].hdr.dst_id==xy_id_iC&&in==Eject) || (compare_sameC[in]&valid_iC[in]) ;
  end
assign all_reduction_srcs_validA = & (same_and_validA|~in_route_mask_oA) ;
assign all_reduction_srcs_validB = & (same_and_validB|~in_route_mask_oB) ;
assign all_reduction_srcs_validC = & (same_and_validC|~in_route_mask_oC) ;
assign valid_oA = (in_route_mask_oA=='0) ? 1'b0 : (| valid_iA & all_reduction_srcs_validA );
assign valid_oB = (in_route_mask_oB=='0) ? 1'b0 : (| valid_iB & all_reduction_srcs_validB );
assign valid_oC = (in_route_mask_oC=='0) ? 1'b0 : (| valid_iC & all_reduction_srcs_validC );
endmodule

