/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/floo_vc_arbiterTMR.sv                                                  *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:43                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/floo_vc_arbiter.sv                                                       *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912                           *
 *           Modification time : 2025-12-30 17:13:52.504025                                         *
 *           File Size         : 2737                                                               *
 *           MD5 hash          : 3d0986fbe0704aaf9a51ea8d9f96ba87                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_vc_arbiterTMR import floo_pkg::*; #(
  parameter int unsigned NumVirtChannels = 1,
  parameter type         flit_t          = logic,
  parameter int unsigned NumPhysChannels = 1
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic [NumVirtChannels - 1:0] valid_iA,
  input logic [NumVirtChannels - 1:0] valid_iB,
  input logic [NumVirtChannels - 1:0] valid_iC,
  output logic [NumVirtChannels - 1:0] ready_oA,
  output logic [NumVirtChannels - 1:0] ready_oB,
  output logic [NumVirtChannels - 1:0] ready_oC,
  input flit_t [NumVirtChannels - 1:0] data_iA,
  input flit_t [NumVirtChannels - 1:0] data_iB,
  input flit_t [NumVirtChannels - 1:0] data_iC,
  input logic [NumVirtChannels - 1:0] ready_iA,
  input logic [NumVirtChannels - 1:0] ready_iB,
  input logic [NumVirtChannels - 1:0] ready_iC,
  output logic [NumVirtChannels - 1:0] valid_oA,
  output logic [NumVirtChannels - 1:0] valid_oB,
  output logic [NumVirtChannels - 1:0] valid_oC,
  output flit_t [NumPhysChannels - 1:0] data_oA,
  output flit_t [NumPhysChannels - 1:0] data_oB,
  output flit_t [NumPhysChannels - 1:0] data_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire i_rr_vc_arbitertmrErrorC;
wire i_rr_vc_arbitertmrErrorB;
wire i_rr_vc_arbitertmrErrorA;
if (NumVirtChannels==NumPhysChannels)
  begin : gen_virt_eq_phys
    assign valid_oA = valid_iA;
    assign valid_oB = valid_iB;
    assign valid_oC = valid_iC;
    assign ready_oA = ready_iA;
    assign ready_oB = ready_iB;
    assign ready_oC = ready_iC;
    assign data_oA = data_iA;
    assign data_oB = data_iB;
    assign data_oC = data_iC;

    assign i_rr_vc_arbitertmrErrorA = 1'b0;
    assign i_rr_vc_arbitertmrErrorB = 1'b0;
    assign i_rr_vc_arbitertmrErrorC = 1'b0;
  end

else
  if (NumPhysChannels==1)
      begin : gen_single_phys
      typedef logic [$clog2(NumVirtChannels) - 1:0] arb_idx_t;
arb_idx_t vc_arb_idxA;
arb_idx_t vc_arb_idxB;
arb_idx_t vc_arb_idxC;
logic [NumVirtChannels - 1:0] vc_arb_req_inA;
logic [NumVirtChannels - 1:0] vc_arb_req_inB;
logic [NumVirtChannels - 1:0] vc_arb_req_inC;
logic vc_arb_req_outA;
logic vc_arb_req_outB;
logic vc_arb_req_outC;
logic vc_arb_gnt_inA;
logic vc_arb_gnt_inB;
logic vc_arb_gnt_inC;
      assign vc_arb_req_inA = valid_iA&ready_iA;
      assign vc_arb_req_inB = valid_iB&ready_iB;
      assign vc_arb_req_inC = valid_iC&ready_iC;
      assign vc_arb_gnt_inA = ready_iA[vc_arb_idxA];
      assign vc_arb_gnt_inB = ready_iB[vc_arb_idxB];
      assign vc_arb_gnt_inC = ready_iC[vc_arb_idxC];

      always_comb
        begin
          valid_oA = '0;
          valid_oA[vc_arb_idxA] = vc_arb_req_outA;
        end

      always_comb
        begin
          valid_oB = '0;
          valid_oB[vc_arb_idxB] = vc_arb_req_outB;
        end

      always_comb
        begin
          valid_oC = '0;
          valid_oC[vc_arb_idxC] = vc_arb_req_outC;
        end

      rr_arb_treeTMR #(.NumIn(NumVirtChannels), .DataType(flit_t), .AxiVldRdy(1'b0), .LockIn(1'b0)) i_rr_vc_arbiter (
          .clk_iA(clk_iA),
          .clk_iB(clk_iB),
          .clk_iC(clk_iC),
          .rst_niA(rst_niA),
          .rst_niB(rst_niB),
          .rst_niC(rst_niC),
          .flush_iA(1'b0),
          .flush_iB(1'b0),
          .flush_iC(1'b0),
          .rr_iA('0),
          .rr_iB('0),
          .rr_iC('0),
          .req_iA(vc_arb_req_inA),
          .req_iB(vc_arb_req_inB),
          .req_iC(vc_arb_req_inC),
          .gnt_oA(ready_oA),
          .gnt_oB(ready_oB),
          .gnt_oC(ready_oC),
          .data_iA(data_iA),
          .data_iB(data_iB),
          .data_iC(data_iC),
          .req_oA(vc_arb_req_outA),
          .req_oB(vc_arb_req_outB),
          .req_oC(vc_arb_req_outC),
          .gnt_iA(vc_arb_gnt_inA),
          .gnt_iB(vc_arb_gnt_inB),
          .gnt_iC(vc_arb_gnt_inC),
          .data_oA(data_oA),
          .data_oB(data_oB),
          .data_oC(data_oC),
          .idx_oA(vc_arb_idxA),
          .idx_oB(vc_arb_idxB),
          .idx_oC(vc_arb_idxC),
          .tmrErrorA(i_rr_vc_arbitertmrErrorA),
          .tmrErrorB(i_rr_vc_arbitertmrErrorB),
          .tmrErrorC(i_rr_vc_arbitertmrErrorC)
        );
    end
assign tmrErrorA = i_rr_vc_arbitertmrErrorA;
assign tmrErrorB = i_rr_vc_arbitertmrErrorB;
assign tmrErrorC = i_rr_vc_arbitertmrErrorC;
endmodule

