/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/floo_nw_routerTMR.sv                                                   *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:41                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/floo_nw_router.sv                                                        *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912                           *
 *           Modification time : 2025-12-30 16:41:27.297635                                         *
 *           File Size         : 9919                                                               *
 *           MD5 hash          : 66c49153bd7c3b3815d9b2212abec72c                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`include "axi/typedef.svh"
`include "floo_noc/typedef.svh"
`include "common_cells/registers.svh"
module floo_nw_routerTMR #(
  parameter floo_pkg::axi_cfg_t AxiCfgN = '0,
  parameter floo_pkg::axi_cfg_t AxiCfgW = '0,
  parameter floo_pkg::route_algo_e RouteAlgo = floo_pkg::XYRouting,
  parameter int unsigned NumRoutes = 0,
  parameter int unsigned NumInputs = NumRoutes,
  parameter int unsigned NumOutputs = NumRoutes,
  parameter int unsigned InFifoDepth = 0,
  parameter int unsigned OutFifoDepth = 0,
  parameter bit XYRouteOpt = 1'b1,
  parameter bit EnMultiCast = 1'b0,
  parameter type id_t                         = logic,
  parameter type hdr_t                        = logic,
  parameter int unsigned NumAddrRules = 0,
  parameter type addr_rule_t                  = logic,
  parameter type floo_req_t                   = logic,
  parameter type floo_rsp_t                   = logic,
  parameter type floo_wide_t                  = logic
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic test_enable_iA,
  input logic test_enable_iB,
  input logic test_enable_iC,
  input id_t id_iA,
  input id_t id_iB,
  input id_t id_iC,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_iA,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_iB,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_iC,
  input floo_req_t [NumInputs - 1:0] floo_req_iA,
  input floo_req_t [NumInputs - 1:0] floo_req_iB,
  input floo_req_t [NumInputs - 1:0] floo_req_iC,
  input floo_rsp_t [NumOutputs - 1:0] floo_rsp_iA,
  input floo_rsp_t [NumOutputs - 1:0] floo_rsp_iB,
  input floo_rsp_t [NumOutputs - 1:0] floo_rsp_iC,
  output floo_req_t [NumOutputs - 1:0] floo_req_oA,
  output floo_req_t [NumOutputs - 1:0] floo_req_oB,
  output floo_req_t [NumOutputs - 1:0] floo_req_oC,
  output floo_rsp_t [NumInputs - 1:0] floo_rsp_oA,
  output floo_rsp_t [NumInputs - 1:0] floo_rsp_oB,
  output floo_rsp_t [NumInputs - 1:0] floo_rsp_oC,
  input floo_wide_t [NumRoutes - 1:0] floo_wide_iA,
  input floo_wide_t [NumRoutes - 1:0] floo_wide_iB,
  input floo_wide_t [NumRoutes - 1:0] floo_wide_iC,
  output floo_wide_t [NumRoutes - 1:0] floo_wide_oA,
  output floo_wide_t [NumRoutes - 1:0] floo_wide_oB,
  output floo_wide_t [NumRoutes - 1:0] floo_wide_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
typedef logic [AxiCfgN.AddrWidth - 1:0] axi_addr_t;
typedef logic [AxiCfgN.InIdWidth - 1:0] axi_narrow_in_id_t;
typedef logic [AxiCfgN.UserWidth - 1:0] axi_narrow_user_t;
typedef logic [AxiCfgN.DataWidth - 1:0] axi_narrow_data_t;
typedef logic [AxiCfgN.DataWidth / 8 - 1:0] axi_narrow_strb_t;
typedef logic [AxiCfgW.InIdWidth - 1:0] axi_wide_in_id_t;
typedef logic [AxiCfgW.UserWidth - 1:0] axi_wide_user_t;
typedef logic [AxiCfgW.DataWidth - 1:0] axi_wide_data_t;
typedef logic [AxiCfgW.DataWidth / 8 - 1:0] axi_wide_strb_t;
  // (Re-) definitons of `axi_in` and `floo` types, for transport
  `AXI_TYPEDEF_ALL_CT(axi_narrow, axi_narrow_req_t, axi_narrow_rsp_t, axi_addr_t,
      axi_narrow_in_id_t, axi_narrow_data_t, axi_narrow_strb_t, axi_narrow_user_t)
  `AXI_TYPEDEF_ALL_CT(axi_wide, axi_wide_req_t, axi_wide_rsp_t, axi_addr_t,
      axi_wide_in_id_t, axi_wide_data_t, axi_wide_strb_t, axi_wide_user_t)
  `FLOO_TYPEDEF_NW_CHAN_ALL(axi, req, rsp, wide, axi_narrow, axi_wide, AxiCfgN, AxiCfgW, hdr_t)
localparam axi_narrow_b_chan_t NarrowBMask = '{resp: 2'b11, default: '0};
localparam floo_axi_narrow_b_flit_t NarrowBFlitMask = '{payload: NarrowBMask, hdr: '0, rsvd: '0};
localparam axi_narrow_b_chan_t WideBMask = '{resp: 2'b11, default: '0};
localparam floo_axi_wide_b_flit_t WideBFlitMask = '{payload: WideBMask, hdr: '0, rsvd: '0};
wire i_wide_req_floo_routertmrErrorC;
wire i_rsp_floo_routertmrErrorC;
wire i_req_floo_routertmrErrorC;
wire i_wide_req_floo_routertmrErrorB;
wire i_rsp_floo_routertmrErrorB;
wire i_req_floo_routertmrErrorB;
wire i_wide_req_floo_routertmrErrorA;
wire i_rsp_floo_routertmrErrorA;
wire i_req_floo_routertmrErrorA;
floo_req_chan_t [NumInputs - 1:0] req_inA;
floo_req_chan_t [NumInputs - 1:0] req_inB;
floo_req_chan_t [NumInputs - 1:0] req_inC;
floo_rsp_chan_t [NumInputs - 1:0] rsp_outA;
floo_rsp_chan_t [NumInputs - 1:0] rsp_outB;
floo_rsp_chan_t [NumInputs - 1:0] rsp_outC;
floo_req_chan_t [NumOutputs - 1:0] req_outA;
floo_req_chan_t [NumOutputs - 1:0] req_outB;
floo_req_chan_t [NumOutputs - 1:0] req_outC;
floo_rsp_chan_t [NumOutputs - 1:0] rsp_inA;
floo_rsp_chan_t [NumOutputs - 1:0] rsp_inB;
floo_rsp_chan_t [NumOutputs - 1:0] rsp_inC;
floo_wide_chan_t [NumRoutes - 1:0] wide_inA;
floo_wide_chan_t [NumRoutes - 1:0] wide_inB;
floo_wide_chan_t [NumRoutes - 1:0] wide_inC;
floo_wide_chan_t [NumRoutes - 1:0] wide_outA;
floo_wide_chan_t [NumRoutes - 1:0] wide_outB;
floo_wide_chan_t [NumRoutes - 1:0] wide_outC;
logic [NumInputs - 1:0] req_valid_inA;
logic [NumInputs - 1:0] req_valid_inB;
logic [NumInputs - 1:0] req_valid_inC;
logic [NumInputs - 1:0] req_ready_outA;
logic [NumInputs - 1:0] req_ready_outB;
logic [NumInputs - 1:0] req_ready_outC;
logic [NumInputs - 1:0] rsp_valid_outA;
logic [NumInputs - 1:0] rsp_valid_outB;
logic [NumInputs - 1:0] rsp_valid_outC;
logic [NumInputs - 1:0] rsp_ready_inA;
logic [NumInputs - 1:0] rsp_ready_inB;
logic [NumInputs - 1:0] rsp_ready_inC;
logic [NumOutputs - 1:0] req_valid_outA;
logic [NumOutputs - 1:0] req_valid_outB;
logic [NumOutputs - 1:0] req_valid_outC;
logic [NumOutputs - 1:0] req_ready_inA;
logic [NumOutputs - 1:0] req_ready_inB;
logic [NumOutputs - 1:0] req_ready_inC;
logic [NumOutputs - 1:0] rsp_valid_inA;
logic [NumOutputs - 1:0] rsp_valid_inB;
logic [NumOutputs - 1:0] rsp_valid_inC;
logic [NumOutputs - 1:0] rsp_ready_outA;
logic [NumOutputs - 1:0] rsp_ready_outB;
logic [NumOutputs - 1:0] rsp_ready_outC;
logic [NumRoutes - 1:0] wide_valid_inA;
logic [NumRoutes - 1:0] wide_valid_inB;
logic [NumRoutes - 1:0] wide_valid_inC;
logic [NumRoutes - 1:0] wide_valid_outA;
logic [NumRoutes - 1:0] wide_valid_outB;
logic [NumRoutes - 1:0] wide_valid_outC;
logic [NumRoutes - 1:0] wide_ready_inA;
logic [NumRoutes - 1:0] wide_ready_inB;
logic [NumRoutes - 1:0] wide_ready_inC;
logic [NumRoutes - 1:0] wide_ready_outA;
logic [NumRoutes - 1:0] wide_ready_outB;
logic [NumRoutes - 1:0] wide_ready_outC;
for(genvar i = 0; i<NumInputs; i++)
  begin : gen_chimney_req
    assign req_valid_inA[i] = floo_req_iA[i].valid;
    assign req_valid_inB[i] = floo_req_iB[i].valid;
    assign req_valid_inC[i] = floo_req_iC[i].valid;
    assign floo_req_oA[i].ready = req_ready_outA[i];
    assign floo_req_oB[i].ready = req_ready_outB[i];
    assign floo_req_oC[i].ready = req_ready_outC[i];
    assign req_inA[i] = floo_req_iA[i].req;
    assign req_inB[i] = floo_req_iB[i].req;
    assign req_inC[i] = floo_req_iC[i].req;
    assign floo_rsp_oA[i].valid = rsp_valid_outA[i];
    assign floo_rsp_oB[i].valid = rsp_valid_outB[i];
    assign floo_rsp_oC[i].valid = rsp_valid_outC[i];
    assign rsp_ready_inA[i] = floo_rsp_iA[i].ready;
    assign rsp_ready_inB[i] = floo_rsp_iB[i].ready;
    assign rsp_ready_inC[i] = floo_rsp_iC[i].ready;
    assign floo_rsp_oA[i].rsp = rsp_outA[i];
    assign floo_rsp_oB[i].rsp = rsp_outB[i];
    assign floo_rsp_oC[i].rsp = rsp_outC[i];
  end
for(genvar i = 0; i<NumOutputs; i++)
  begin : gen_chimney_rsp
    assign floo_req_oA[i].valid = req_valid_outA[i];
    assign floo_req_oB[i].valid = req_valid_outB[i];
    assign floo_req_oC[i].valid = req_valid_outC[i];
    assign req_ready_inA[i] = floo_req_iA[i].ready;
    assign req_ready_inB[i] = floo_req_iB[i].ready;
    assign req_ready_inC[i] = floo_req_iC[i].ready;
    assign floo_req_oA[i].req = req_outA[i];
    assign floo_req_oB[i].req = req_outB[i];
    assign floo_req_oC[i].req = req_outC[i];
    assign rsp_valid_inA[i] = floo_rsp_iA[i].valid;
    assign rsp_valid_inB[i] = floo_rsp_iB[i].valid;
    assign rsp_valid_inC[i] = floo_rsp_iC[i].valid;
    assign floo_rsp_oA[i].ready = rsp_ready_outA[i];
    assign floo_rsp_oB[i].ready = rsp_ready_outB[i];
    assign floo_rsp_oC[i].ready = rsp_ready_outC[i];
    assign rsp_inA[i] = floo_rsp_iA[i].rsp;
    assign rsp_inB[i] = floo_rsp_iB[i].rsp;
    assign rsp_inC[i] = floo_rsp_iC[i].rsp;
  end
for(genvar i = 0; i<NumRoutes; i++)
  begin : gen_chimney_wide
    assign wide_valid_inA[i] = floo_wide_iA[i].valid;
    assign wide_valid_inB[i] = floo_wide_iB[i].valid;
    assign wide_valid_inC[i] = floo_wide_iC[i].valid;
    assign floo_wide_oA[i].ready = wide_ready_outA[i];
    assign floo_wide_oB[i].ready = wide_ready_outB[i];
    assign floo_wide_oC[i].ready = wide_ready_outC[i];
    assign wide_inA[i] = floo_wide_iA[i].wide;
    assign wide_inB[i] = floo_wide_iB[i].wide;
    assign wide_inC[i] = floo_wide_iC[i].wide;
    assign floo_wide_oA[i].valid = wide_valid_outA[i];
    assign floo_wide_oB[i].valid = wide_valid_outB[i];
    assign floo_wide_oC[i].valid = wide_valid_outC[i];
    assign wide_ready_inA[i] = floo_wide_iA[i].ready;
    assign wide_ready_inB[i] = floo_wide_iB[i].ready;
    assign wide_ready_inC[i] = floo_wide_iC[i].ready;
    assign floo_wide_oA[i].wide = wide_outA[i];
    assign floo_wide_oB[i].wide = wide_outB[i];
    assign floo_wide_oC[i].wide = wide_outC[i];
  end

floo_routerTMR #(.NumInput(NumInputs), .NumOutput(NumOutputs), .NumPhysChannels(1), .NumVirtChannels(1), .InFifoDepth(InFifoDepth), .OutFifoDepth(OutFifoDepth), .RouteAlgo(RouteAlgo), .XYRouteOpt(XYRouteOpt), .NumAddrRules(NumAddrRules), .NoLoopback(1'b1), .EnMultiCast(EnMultiCast), .EnReduction(1'b0), .id_t(id_t), .addr_rule_t(addr_rule_t), .flit_t(floo_req_generic_flit_t)) i_req_floo_router (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .test_enable_iA(test_enable_iA),
    .test_enable_iB(test_enable_iB),
    .test_enable_iC(test_enable_iC),
    .xy_id_iA(id_iA),
    .xy_id_iB(id_iB),
    .xy_id_iC(id_iC),
    .id_route_map_iA(id_route_map_iA),
    .id_route_map_iB(id_route_map_iB),
    .id_route_map_iC(id_route_map_iC),
    .valid_iA(req_valid_inA),
    .valid_iB(req_valid_inB),
    .valid_iC(req_valid_inC),
    .ready_oA(req_ready_outA),
    .ready_oB(req_ready_outB),
    .ready_oC(req_ready_outC),
    .data_iA(req_inA),
    .data_iB(req_inB),
    .data_iC(req_inC),
    .valid_oA(req_valid_outA),
    .valid_oB(req_valid_outB),
    .valid_oC(req_valid_outC),
    .ready_iA(req_ready_inA),
    .ready_iB(req_ready_inB),
    .ready_iC(req_ready_inC),
    .data_oA(req_outA),
    .data_oB(req_outB),
    .data_oC(req_outC),
    .tmrErrorA(i_req_floo_routertmrErrorA),
    .tmrErrorB(i_req_floo_routertmrErrorB),
    .tmrErrorC(i_req_floo_routertmrErrorC)
  );

floo_routerTMR #(.NumInput(NumInputs), .NumOutput(NumOutputs), .NumPhysChannels(1), .NumVirtChannels(1), .InFifoDepth(InFifoDepth), .OutFifoDepth(OutFifoDepth), .RouteAlgo(RouteAlgo), .XYRouteOpt(XYRouteOpt), .NumAddrRules(NumAddrRules), .NoLoopback(1'b1), .EnMultiCast(1'b0), .EnReduction(EnMultiCast), .id_t(id_t), .addr_rule_t(addr_rule_t), .flit_t(floo_rsp_generic_flit_t), .payload_t(floo_rsp_payload_t), .NarrowRspMask(floo_rsp_generic_flit_t' (NarrowBFlitMask.payload) ), .WideRspMask(floo_rsp_generic_flit_t' (WideBFlitMask.payload) )) i_rsp_floo_router (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .test_enable_iA(test_enable_iA),
    .test_enable_iB(test_enable_iB),
    .test_enable_iC(test_enable_iC),
    .xy_id_iA(id_iA),
    .xy_id_iB(id_iB),
    .xy_id_iC(id_iC),
    .id_route_map_iA(id_route_map_iA),
    .id_route_map_iB(id_route_map_iB),
    .id_route_map_iC(id_route_map_iC),
    .valid_iA(rsp_valid_inA),
    .valid_iB(rsp_valid_inB),
    .valid_iC(rsp_valid_inC),
    .ready_oA(rsp_ready_outA),
    .ready_oB(rsp_ready_outB),
    .ready_oC(rsp_ready_outC),
    .data_iA(rsp_inA),
    .data_iB(rsp_inB),
    .data_iC(rsp_inC),
    .valid_oA(rsp_valid_outA),
    .valid_oB(rsp_valid_outB),
    .valid_oC(rsp_valid_outC),
    .ready_iA(rsp_ready_inA),
    .ready_iB(rsp_ready_inB),
    .ready_iC(rsp_ready_inC),
    .data_oA(rsp_outA),
    .data_oB(rsp_outB),
    .data_oC(rsp_outC),
    .tmrErrorA(i_rsp_floo_routertmrErrorA),
    .tmrErrorB(i_rsp_floo_routertmrErrorB),
    .tmrErrorC(i_rsp_floo_routertmrErrorC)
  );

floo_routerTMR #(.NumRoutes(NumRoutes), .NumPhysChannels(1), .NumVirtChannels(1), .InFifoDepth(InFifoDepth), .OutFifoDepth(OutFifoDepth), .RouteAlgo(RouteAlgo), .XYRouteOpt(XYRouteOpt), .NumAddrRules(NumAddrRules), .NoLoopback(1'b1), .EnMultiCast(EnMultiCast), .EnReduction(1'b0), .id_t(id_t), .addr_rule_t(addr_rule_t), .flit_t(floo_wide_generic_flit_t)) i_wide_req_floo_router (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .test_enable_iA(test_enable_iA),
    .test_enable_iB(test_enable_iB),
    .test_enable_iC(test_enable_iC),
    .xy_id_iA(id_iA),
    .xy_id_iB(id_iB),
    .xy_id_iC(id_iC),
    .id_route_map_iA(id_route_map_iA),
    .id_route_map_iB(id_route_map_iB),
    .id_route_map_iC(id_route_map_iC),
    .valid_iA(wide_valid_inA),
    .valid_iB(wide_valid_inB),
    .valid_iC(wide_valid_inC),
    .ready_oA(wide_ready_outA),
    .ready_oB(wide_ready_outB),
    .ready_oC(wide_ready_outC),
    .data_iA(wide_inA),
    .data_iB(wide_inB),
    .data_iC(wide_inC),
    .valid_oA(wide_valid_outA),
    .valid_oB(wide_valid_outB),
    .valid_oC(wide_valid_outC),
    .ready_iA(wide_ready_inA),
    .ready_iB(wide_ready_inB),
    .ready_iC(wide_ready_inC),
    .data_oA(wide_outA),
    .data_oB(wide_outB),
    .data_oC(wide_outC),
    .tmrErrorA(i_wide_req_floo_routertmrErrorA),
    .tmrErrorB(i_wide_req_floo_routertmrErrorB),
    .tmrErrorC(i_wide_req_floo_routertmrErrorC)
  );
assign tmrErrorA = i_req_floo_routertmrErrorA|i_rsp_floo_routertmrErrorA|i_wide_req_floo_routertmrErrorA;
assign tmrErrorB = i_req_floo_routertmrErrorB|i_rsp_floo_routertmrErrorB|i_wide_req_floo_routertmrErrorB;
assign tmrErrorC = i_req_floo_routertmrErrorC|i_rsp_floo_routertmrErrorC|i_wide_req_floo_routertmrErrorC;
endmodule



// /scratch/chenwu/tmrg/tmrg/../common/voter.v
module majorityVoter #(
  parameter WIDTH = 1
)(
  input wire  [WIDTH-1:0] inA,
  input wire  [WIDTH-1:0] inB,
  input wire  [WIDTH-1:0] inC,
  output wire [WIDTH-1:0] out,
  output reg              tmrErr
);
  assign out = (inA&inB) | (inA&inC) | (inB&inC);
  always @(inA or inB or inC) begin
    if (inA!=inB || inA!=inC || inB!=inC)
      tmrErr = 1;
    else
      tmrErr = 0;
  end
endmodule
