/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/floo_wormhole_arbiterTMR.sv                                            *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:43                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/floo_wormhole_arbiter.sv                                                 *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912                           *
 *           Modification time : 2025-12-30 17:13:37.407882                                         *
 *           File Size         : 2740                                                               *
 *           MD5 hash          : 74931236999772468b0068e57eb7deee                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_wormhole_arbiterTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 1,
  parameter type         flit_t     = logic
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic [NumRoutes - 1:0] valid_iA,
  input logic [NumRoutes - 1:0] valid_iB,
  input logic [NumRoutes - 1:0] valid_iC,
  output logic [NumRoutes - 1:0] ready_oA,
  output logic [NumRoutes - 1:0] ready_oB,
  output logic [NumRoutes - 1:0] ready_oC,
  input flit_t [NumRoutes - 1:0] data_iA,
  input flit_t [NumRoutes - 1:0] data_iB,
  input flit_t [NumRoutes - 1:0] data_iC,
  output logic valid_oA,
  output logic valid_oB,
  output logic valid_oC,
  input logic ready_iA,
  input logic ready_iB,
  input logic ready_iC,
  output flit_t data_oA,
  output flit_t data_oB,
  output flit_t data_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
typedef logic [cf_math_pkg::idx_width(NumRoutes) - 1:0] arb_idx_t;
wire valid_qTmrErrorC;
wire last_qTmrErrorC;
wire i_rr_arb_packetstmrErrorC;
wire valid_qTmrErrorB;
wire last_qTmrErrorB;
wire i_rr_arb_packetstmrErrorB;
wire valid_qTmrErrorA;
wire last_qTmrErrorA;
wire i_rr_arb_packetstmrErrorA;
logic last_outA;
logic last_outB;
logic last_outC;
logic last_qA;
logic last_qB;
logic last_qC;
logic last_qVotedA;
logic last_qVotedB;
logic last_qVotedC;
arb_idx_t selected_idxA;
arb_idx_t selected_idxB;
arb_idx_t selected_idxC;
arb_idx_t valid_selected_idxA;
arb_idx_t valid_selected_idxB;
arb_idx_t valid_selected_idxC;
logic [NumRoutes - 1:0] valid_dA;
logic [NumRoutes - 1:0] valid_dB;
logic [NumRoutes - 1:0] valid_dC;
logic [NumRoutes - 1:0] valid_qA;
logic [NumRoutes - 1:0] valid_qB;
logic [NumRoutes - 1:0] valid_qC;
logic [NumRoutes - 1:0] valid_qVotedA;
logic [NumRoutes - 1:0] valid_qVotedB;
logic [NumRoutes - 1:0] valid_qVotedC;

rr_arb_treeTMR #(.NumIn(NumRoutes), .ExtPrio(1'b0), .AxiVldRdy(1'b1), .LockIn(1'b1), .FairArb(1'b1)) i_rr_arb_packets (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .flush_iA(1'b0),
    .flush_iB(1'b0),
    .flush_iC(1'b0),
    .rr_iA('0),
    .rr_iB('0),
    .rr_iC('0),
    .req_iA(valid_dA),
    .req_iB(valid_dB),
    .req_iC(valid_dC),
    .gnt_oA(),
    .gnt_oB(),
    .gnt_oC(),
    .data_iA('0),
    .data_iB('0),
    .data_iC('0),
    .req_oA(),
    .req_oB(),
    .req_oC(),
    .gnt_iA(ready_iA&last_outA),
    .gnt_iB(ready_iB&last_outB),
    .gnt_iC(ready_iC&last_outC),
    .data_oA(),
    .data_oB(),
    .data_oC(),
    .idx_oA(selected_idxA),
    .idx_oB(selected_idxB),
    .idx_oC(selected_idxC),
    .tmrErrorA(i_rr_arb_packetstmrErrorA),
    .tmrErrorB(i_rr_arb_packetstmrErrorB),
    .tmrErrorC(i_rr_arb_packetstmrErrorC)
  );
assign valid_selected_idxA = (| valid_iA ) ? selected_idxA : '0;
assign valid_selected_idxB = (| valid_iB ) ? selected_idxB : '0;
assign valid_selected_idxC = (| valid_iC ) ? selected_idxC : '0;
assign valid_oA = valid_iA[valid_selected_idxA];
assign valid_oB = valid_iB[valid_selected_idxB];
assign valid_oC = valid_iC[valid_selected_idxC];
assign data_oA = data_iA[valid_selected_idxA];
assign data_oB = data_iB[valid_selected_idxB];
assign data_oC = data_iC[valid_selected_idxC];

always_comb
  begin : proc_ready_oA
    ready_oA = '0;
    ready_oA[valid_selected_idxA] = (| valid_iA ) ? ready_iA : '0;
  end

always_comb
  begin : proc_ready_oB
    ready_oB = '0;
    ready_oB[valid_selected_idxB] = (| valid_iB ) ? ready_iB : '0;
  end

always_comb
  begin : proc_ready_oC
    ready_oC = '0;
    ready_oC[valid_selected_idxC] = (| valid_iC ) ? ready_iC : '0;
  end
assign last_outA = data_oA.hdr.last&valid_oA;
assign last_outB = data_oB.hdr.last&valid_oB;
assign last_outC = data_oC.hdr.last&valid_oC;

always_comb
  begin : proc_validA
    valid_dA = valid_qVotedA;
    if (valid_qVotedA=='0||last_qVotedA)
      begin
        valid_dA = valid_iA;
      end

  end

always_comb
  begin : proc_validB
    valid_dB = valid_qVotedB;
    if (valid_qVotedB=='0||last_qVotedB)
      begin
        valid_dB = valid_iB;
      end

  end

always_comb
  begin : proc_validC
    valid_dC = valid_qVotedC;
    if (valid_qVotedC=='0||last_qVotedC)
      begin
        valid_dC = valid_iC;
      end

  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        valid_qA <= '0;
      end
    else
      begin
        valid_qA <= valid_dA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        valid_qB <= '0;
      end
    else
      begin
        valid_qB <= valid_dB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        valid_qC <= '0;
      end
    else
      begin
        valid_qC <= valid_dC;
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        last_qA <= '0;
      end
    else
      begin
        last_qA <= last_outA&ready_iA;
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        last_qB <= '0;
      end
    else
      begin
        last_qB <= last_outB&ready_iB;
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        last_qC <= '0;
      end
    else
      begin
        last_qC <= last_outC&ready_iC;
      end
  end

majorityVoter last_qVoterA (
    .inA(last_qA),
    .inB(last_qB),
    .inC(last_qC),
    .out(last_qVotedA),
    .tmrErr(last_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ((((NumRoutes-1)>0) ? (NumRoutes-1) : - ( NumRoutes-1 ) )+1) )) valid_qVoterA (
    .inA(valid_qA),
    .inB(valid_qB),
    .inC(valid_qC),
    .out(valid_qVotedA),
    .tmrErr(valid_qTmrErrorA)
  );
assign tmrErrorA = i_rr_arb_packetstmrErrorA|last_qTmrErrorA|valid_qTmrErrorA;

majorityVoter last_qVoterB (
    .inA(last_qA),
    .inB(last_qB),
    .inC(last_qC),
    .out(last_qVotedB),
    .tmrErr(last_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ((((NumRoutes-1)>0) ? (NumRoutes-1) : - ( NumRoutes-1 ) )+1) )) valid_qVoterB (
    .inA(valid_qA),
    .inB(valid_qB),
    .inC(valid_qC),
    .out(valid_qVotedB),
    .tmrErr(valid_qTmrErrorB)
  );
assign tmrErrorB = i_rr_arb_packetstmrErrorB|last_qTmrErrorB|valid_qTmrErrorB;

majorityVoter last_qVoterC (
    .inA(last_qA),
    .inB(last_qB),
    .inC(last_qC),
    .out(last_qVotedC),
    .tmrErr(last_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ((((NumRoutes-1)>0) ? (NumRoutes-1) : - ( NumRoutes-1 ) )+1) )) valid_qVoterC (
    .inA(valid_qA),
    .inB(valid_qB),
    .inC(valid_qC),
    .out(valid_qVotedC),
    .tmrErr(valid_qTmrErrorC)
  );
assign tmrErrorC = i_rr_arb_packetstmrErrorC|last_qTmrErrorC|valid_qTmrErrorC;
endmodule

