/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/floo_reduction_arbiterTMR.sv                                           *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:43                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/floo_reduction_arbiter.sv                                                *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912                           *
 *           Modification time : 2025-12-30 16:34:44.292836                                         *
 *           File Size         : 3029                                                               *
 *           MD5 hash          : 04c6509dd741ea47422968265e6f9382                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_reduction_arbiterTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 1,
  parameter type         flit_t     = logic,
  parameter type         payload_t  = logic,
  parameter payload_t NarrowRspMask = '0,
  parameter payload_t WideRspMask = '0,
  parameter type         id_t       = logic
) (
  input id_t xy_id_iA,
  input id_t xy_id_iB,
  input id_t xy_id_iC,
  input logic [NumRoutes - 1:0] valid_iA,
  input logic [NumRoutes - 1:0] valid_iB,
  input logic [NumRoutes - 1:0] valid_iC,
  output logic [NumRoutes - 1:0] ready_oA,
  output logic [NumRoutes - 1:0] ready_oB,
  output logic [NumRoutes - 1:0] ready_oC,
  input flit_t [NumRoutes - 1:0] data_iA,
  input flit_t [NumRoutes - 1:0] data_iB,
  input flit_t [NumRoutes - 1:0] data_iC,
  output logic valid_oA,
  output logic valid_oB,
  output logic valid_oC,
  input logic ready_iA,
  input logic ready_iB,
  input logic ready_iC,
  output flit_t data_oA,
  output flit_t data_oB,
  output flit_t data_oC
);
typedef logic [cf_math_pkg::idx_width(NumRoutes) - 1:0] arb_idx_t;
logic [NumRoutes - 1:0] in_route_maskA;
logic [NumRoutes - 1:0] in_route_maskB;
logic [NumRoutes - 1:0] in_route_maskC;
arb_idx_t input_selA;
arb_idx_t input_selB;
arb_idx_t input_selC;

lzc #(.WIDTH(NumRoutes)) i_lzcA (
    .in_i(valid_iA),
    .cnt_o(input_selA),
    .empty_o()
  );

lzc #(.WIDTH(NumRoutes)) i_lzcB (
    .in_i(valid_iB),
    .cnt_o(input_selB),
    .empty_o()
  );

lzc #(.WIDTH(NumRoutes)) i_lzcC (
    .in_i(valid_iC),
    .cnt_o(input_selC),
    .empty_o()
  );

floo_reduction_syncTMR #(.NumRoutes(NumRoutes), .arb_idx_t(arb_idx_t), .flit_t(flit_t), .id_t(id_t)) i_reduction_sync (
    .sel_iA(input_selA),
    .sel_iB(input_selB),
    .sel_iC(input_selC),
    .data_iA(data_iA),
    .data_iB(data_iB),
    .data_iC(data_iC),
    .valid_iA(valid_iA),
    .valid_iB(valid_iB),
    .valid_iC(valid_iC),
    .xy_id_iA(xy_id_iA),
    .xy_id_iB(xy_id_iB),
    .xy_id_iC(xy_id_iC),
    .valid_oA(valid_oA),
    .valid_oB(valid_oB),
    .valid_oC(valid_oC),
    .in_route_mask_oA(in_route_maskA),
    .in_route_mask_oB(in_route_maskB),
    .in_route_mask_oC(in_route_maskC)
  );
payload_t ReduceMaskA;
payload_t ReduceMaskB;
payload_t ReduceMaskC;
assign ReduceMaskA = data_iA[input_selA].hdr.axi_ch==NarrowB ? NarrowRspMask : WideRspMask;
assign ReduceMaskB = data_iB[input_selB].hdr.axi_ch==NarrowB ? NarrowRspMask : WideRspMask;
assign ReduceMaskC = data_iC[input_selC].hdr.axi_ch==NarrowB ? NarrowRspMask : WideRspMask;
logic [1:0] respA;
logic [1:0] respB;
logic [1:0] respC;

always_comb
  begin : gen_reduced_BA
    data_oA = data_iA[input_selA];
    respA = '0;
    for(int i = 0; i<NumRoutes; i++)
    begin
      if (in_route_maskA[i])
        begin
                    automatic int j = 0;

          for(int k = 0; k<$bits(ReduceMaskA); k++)
          begin
            if (ReduceMaskA[k])
              begin
                respA[j] = data_iA[i].payload[k];
                j++;
              end

          end
          if (respA==axi_pkg::RESP_SLVERR)
            begin
              data_oA = data_iA[i];
              break;
            end

        end

    end
  end

always_comb
  begin : gen_reduced_BB
    data_oB = data_iB[input_selB];
    respB = '0;
    for(int i = 0; i<NumRoutes; i++)
    begin
      if (in_route_maskB[i])
        begin
                    automatic int j = 0;

          for(int k = 0; k<$bits(ReduceMaskB); k++)
          begin
            if (ReduceMaskB[k])
              begin
                respB[j] = data_iB[i].payload[k];
                j++;
              end

          end
          if (respB==axi_pkg::RESP_SLVERR)
            begin
              data_oB = data_iB[i];
              break;
            end

        end

    end
  end

always_comb
  begin : gen_reduced_BC
    data_oC = data_iC[input_selC];
    respC = '0;
    for(int i = 0; i<NumRoutes; i++)
    begin
      if (in_route_maskC[i])
        begin
                    automatic int j = 0;

          for(int k = 0; k<$bits(ReduceMaskC); k++)
          begin
            if (ReduceMaskC[k])
              begin
                respC[j] = data_iC[i].payload[k];
                j++;
              end

          end
          if (respC==axi_pkg::RESP_SLVERR)
            begin
              data_oC = data_iC[i];
              break;
            end

        end

    end
  end
assign ready_oA = (ready_iA&valid_oA) ? valid_iA&in_route_maskA : '0;
assign ready_oB = (ready_iB&valid_oB) ? valid_iB&in_route_maskB : '0;
assign ready_oC = (ready_iC&valid_oC) ? valid_iC&in_route_maskC : '0;
endmodule

