/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/spill_register_flushableTMR.sv                                         *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:42                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/spill_register_flushable.sv                                              *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 ( M full/tmrg_src/spill_register_flushable.sv) *
 *           Modification time : 2026-05-01 19:36:03.644110                                         *
 *           File Size         : 4892                                                               *
 *           MD5 hash          : 6f25ada9644eb93f403808c6b79f9479                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module spill_register_flushableTMR #(
  parameter type T      = logic,
  parameter bit Bypass = 1'b0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic valid_iA,
  input logic valid_iB,
  input logic valid_iC,
  input logic flush_iA,
  input logic flush_iB,
  input logic flush_iC,
  output logic ready_oA,
  output logic ready_oB,
  output logic ready_oC,
  input T data_iA,
  input T data_iB,
  input T data_iC,
  output logic valid_oA,
  output logic valid_oB,
  output logic valid_oC,
  input logic ready_iA,
  input logic ready_iB,
  input logic ready_iC,
  output T data_oA,
  output T data_oB,
  output T data_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire b_full_qTmrErrorC;
wire b_data_qTmrErrorC;
wire a_full_qTmrErrorC;
wire a_data_qTmrErrorC;
wire b_full_qTmrErrorB;
wire b_data_qTmrErrorB;
wire a_full_qTmrErrorB;
wire a_data_qTmrErrorB;
wire b_full_qTmrErrorA;
wire b_data_qTmrErrorA;
wire a_full_qTmrErrorA;
wire a_data_qTmrErrorA;
T a_data_qA;
T a_data_qB;
T a_data_qC;
T a_data_qVotedA;
T a_data_qVotedB;
T a_data_qVotedC;
logic a_full_qA;
logic a_full_qB;
logic a_full_qC;
logic a_full_qVotedA;
logic a_full_qVotedB;
logic a_full_qVotedC;
logic a_fillA;
logic a_fillB;
logic a_fillC;
logic a_drainA;
logic a_drainB;
logic a_drainC;
T b_data_qA;
T b_data_qB;
T b_data_qC;
T b_data_qVotedA;
T b_data_qVotedB;
T b_data_qVotedC;
logic b_full_qA;
logic b_full_qB;
logic b_full_qC;
logic b_full_qVotedA;
logic b_full_qVotedB;
logic b_full_qVotedC;
logic b_fillA;
logic b_fillB;
logic b_fillC;
logic b_drainA;
logic b_drainB;
logic b_drainC;
if (Bypass)
  begin : gen_bypass
    assign valid_oA = valid_iA;
    assign valid_oB = valid_iB;
    assign valid_oC = valid_iC;
    assign ready_oA = ready_iA;
    assign ready_oB = ready_iB;
    assign ready_oC = ready_iC;
    assign data_oA = data_iA;
    assign data_oB = data_iB;
    assign data_oC = data_iC;
  end

else
  begin : gen_spill_reg
    wire a_data_enA = a_fillA|a_data_qTmrErrorA;
    wire a_data_enB = a_fillB|a_data_qTmrErrorB;
    wire a_data_enC = a_fillC|a_data_qTmrErrorC;
    wire a_full_enA = a_fillA|a_drainA|a_full_qTmrErrorA;
    wire a_full_enB = a_fillB|a_drainB|a_full_qTmrErrorB;
    wire a_full_enC = a_fillC|a_drainC|a_full_qTmrErrorC;
    wire b_data_enA = b_fillA|b_data_qTmrErrorA;
    wire b_data_enB = b_fillB|b_data_qTmrErrorB;
    wire b_data_enC = b_fillC|b_data_qTmrErrorC;
    wire b_full_enA = b_fillA|b_drainA|b_full_qTmrErrorA;
    wire b_full_enB = b_fillB|b_drainB|b_full_qTmrErrorB;
    wire b_full_enC = b_fillC|b_drainC|b_full_qTmrErrorC;
T a_data_nA;
T a_data_nB;
T a_data_nC;
    assign a_data_nA = a_fillA ? data_iA : a_data_qVotedA;
    assign a_data_nB = a_fillB ? data_iB : a_data_qVotedB;
    assign a_data_nC = a_fillC ? data_iC : a_data_qVotedC;
logic a_full_nA;
logic a_full_nB;
logic a_full_nC;
    assign a_full_nA = (a_fillA||a_drainA) ? a_fillA : a_full_qVotedA;
    assign a_full_nB = (a_fillB||a_drainB) ? a_fillB : a_full_qVotedB;
    assign a_full_nC = (a_fillC||a_drainC) ? a_fillC : a_full_qVotedC;
T b_data_nA;
T b_data_nB;
T b_data_nC;
    assign b_data_nA = b_fillA ? a_data_qVotedA : b_data_qVotedA;
    assign b_data_nB = b_fillB ? a_data_qVotedB : b_data_qVotedB;
    assign b_data_nC = b_fillC ? a_data_qVotedC : b_data_qVotedC;
logic b_full_nA;
logic b_full_nB;
logic b_full_nC;
    assign b_full_nA = (b_fillA||b_drainA) ? b_fillA : b_full_qVotedA;
    assign b_full_nB = (b_fillB||b_drainB) ? b_fillB : b_full_qVotedB;
    assign b_full_nC = (b_fillC||b_drainC) ? b_fillC : b_full_qVotedC;

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_a_dataA
        if (!rst_niA)
          a_data_qA <= T' ('0) ;
        else
          if (a_data_enA)
            a_data_qA <= a_data_nA;

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_a_dataB
        if (!rst_niB)
          a_data_qB <= T' ('0) ;
        else
          if (a_data_enB)
            a_data_qB <= a_data_nB;

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_a_dataC
        if (!rst_niC)
          a_data_qC <= T' ('0) ;
        else
          if (a_data_enC)
            a_data_qC <= a_data_nC;

      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_a_fullA
        if (!rst_niA)
          a_full_qA <= 0;
        else
          if (a_full_enA)
            a_full_qA <= a_full_nA;

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_a_fullB
        if (!rst_niB)
          a_full_qB <= 0;
        else
          if (a_full_enB)
            a_full_qB <= a_full_nB;

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_a_fullC
        if (!rst_niC)
          a_full_qC <= 0;
        else
          if (a_full_enC)
            a_full_qC <= a_full_nC;

      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_b_dataA
        if (!rst_niA)
          b_data_qA <= T' ('0) ;
        else
          if (b_data_enA)
            b_data_qA <= b_data_nA;

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_b_dataB
        if (!rst_niB)
          b_data_qB <= T' ('0) ;
        else
          if (b_data_enB)
            b_data_qB <= b_data_nB;

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_b_dataC
        if (!rst_niC)
          b_data_qC <= T' ('0) ;
        else
          if (b_data_enC)
            b_data_qC <= b_data_nC;

      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_b_fullA
        if (!rst_niA)
          b_full_qA <= 0;
        else
          if (b_full_enA)
            b_full_qA <= b_full_nA;

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_b_fullB
        if (!rst_niB)
          b_full_qB <= 0;
        else
          if (b_full_enB)
            b_full_qB <= b_full_nB;

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_b_fullC
        if (!rst_niC)
          b_full_qC <= 0;
        else
          if (b_full_enC)
            b_full_qC <= b_full_nC;

      end
    assign a_fillA = valid_iA&&ready_oA&& (! flush_iA ) ;
    assign a_fillB = valid_iB&&ready_oB&& (! flush_iB ) ;
    assign a_fillC = valid_iC&&ready_oC&& (! flush_iC ) ;
    assign a_drainA =  (a_full_qVotedA&&!b_full_qVotedA) ||flush_iA;
    assign a_drainB =  (a_full_qVotedB&&!b_full_qVotedB) ||flush_iB;
    assign a_drainC =  (a_full_qVotedC&&!b_full_qVotedC) ||flush_iC;
    assign b_fillA = a_drainA&& (! ready_iA ) && (! flush_iA ) ;
    assign b_fillB = a_drainB&& (! ready_iB ) && (! flush_iB ) ;
    assign b_fillC = a_drainC&& (! ready_iC ) && (! flush_iC ) ;
    assign b_drainA =  (b_full_qVotedA&&ready_iA) ||flush_iA;
    assign b_drainB =  (b_full_qVotedB&&ready_iB) ||flush_iB;
    assign b_drainC =  (b_full_qVotedC&&ready_iC) ||flush_iC;
    assign ready_oA = !a_full_qVotedA||!b_full_qVotedA;
    assign ready_oB = !a_full_qVotedB||!b_full_qVotedB;
    assign ready_oC = !a_full_qVotedC||!b_full_qVotedC;
    assign valid_oA = a_full_qVotedA|b_full_qVotedA;
    assign valid_oB = a_full_qVotedB|b_full_qVotedB;
    assign valid_oC = a_full_qVotedC|b_full_qVotedC;
    assign data_oA = b_full_qVotedA ? b_data_qVotedA : a_data_qVotedA;
    assign data_oB = b_full_qVotedB ? b_data_qVotedB : a_data_qVotedB;
    assign data_oC = b_full_qVotedC ? b_data_qVotedC : a_data_qVotedC;
  end

majorityVoter #(.WIDTH( ($bits(a_data_qVotedA)) )) a_data_qVoterA (
    .inA(a_data_qA),
    .inB(a_data_qB),
    .inC(a_data_qC),
    .out(a_data_qVotedA),
    .tmrErr(a_data_qTmrErrorA)
  );

majorityVoter a_full_qVoterA (
    .inA(a_full_qA),
    .inB(a_full_qB),
    .inC(a_full_qC),
    .out(a_full_qVotedA),
    .tmrErr(a_full_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ($bits(a_data_qVotedA)) )) b_data_qVoterA (
    .inA(b_data_qA),
    .inB(b_data_qB),
    .inC(b_data_qC),
    .out(b_data_qVotedA),
    .tmrErr(b_data_qTmrErrorA)
  );

majorityVoter b_full_qVoterA (
    .inA(b_full_qA),
    .inB(b_full_qB),
    .inC(b_full_qC),
    .out(b_full_qVotedA),
    .tmrErr(b_full_qTmrErrorA)
  );
assign tmrErrorA = a_data_qTmrErrorA|a_full_qTmrErrorA|b_data_qTmrErrorA|b_full_qTmrErrorA;

majorityVoter #(.WIDTH( ($bits(a_data_qVotedA)) )) a_data_qVoterB (
    .inA(a_data_qA),
    .inB(a_data_qB),
    .inC(a_data_qC),
    .out(a_data_qVotedB),
    .tmrErr(a_data_qTmrErrorB)
  );

majorityVoter a_full_qVoterB (
    .inA(a_full_qA),
    .inB(a_full_qB),
    .inC(a_full_qC),
    .out(a_full_qVotedB),
    .tmrErr(a_full_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ($bits(a_data_qVotedA)) )) b_data_qVoterB (
    .inA(b_data_qA),
    .inB(b_data_qB),
    .inC(b_data_qC),
    .out(b_data_qVotedB),
    .tmrErr(b_data_qTmrErrorB)
  );

majorityVoter b_full_qVoterB (
    .inA(b_full_qA),
    .inB(b_full_qB),
    .inC(b_full_qC),
    .out(b_full_qVotedB),
    .tmrErr(b_full_qTmrErrorB)
  );
assign tmrErrorB = a_data_qTmrErrorB|a_full_qTmrErrorB|b_data_qTmrErrorB|b_full_qTmrErrorB;

majorityVoter #(.WIDTH( ($bits(a_data_qVotedA)) )) a_data_qVoterC (
    .inA(a_data_qA),
    .inB(a_data_qB),
    .inC(a_data_qC),
    .out(a_data_qVotedC),
    .tmrErr(a_data_qTmrErrorC)
  );

majorityVoter a_full_qVoterC (
    .inA(a_full_qA),
    .inB(a_full_qB),
    .inC(a_full_qC),
    .out(a_full_qVotedC),
    .tmrErr(a_full_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ($bits(a_data_qVotedA)) )) b_data_qVoterC (
    .inA(b_data_qA),
    .inB(b_data_qB),
    .inC(b_data_qC),
    .out(b_data_qVotedC),
    .tmrErr(b_data_qTmrErrorC)
  );

majorityVoter b_full_qVoterC (
    .inA(b_full_qA),
    .inB(b_full_qB),
    .inC(b_full_qC),
    .out(b_full_qVotedC),
    .tmrErr(b_full_qTmrErrorC)
  );
assign tmrErrorC = a_data_qTmrErrorC|a_full_qTmrErrorC|b_data_qTmrErrorC|b_full_qTmrErrorC;
endmodule

