/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : full/tmrg_files/stream_fifo_optimal_wrapTMR.sv                                         *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 19:41:42                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg full/tmrg_src/floo_nw_router.sv                     *
 *           full/tmrg_src/floo_router.sv full/tmrg_src/stream_fifo_optimal_wrap.sv                 *
 *           full/tmrg_src/spill_register_flushable.sv full/tmrg_src/stream_fifo.sv                 *
 *           full/tmrg_src/fifo_v3.sv full/tmrg_src/floo_route_select.sv                            *
 *           full/tmrg_src/floo_route_xymask.sv full/tmrg_src/addr_decode.sv                        *
 *           full/tmrg_src/addr_decode_dync.sv full/tmrg_src/floo_wormhole_arbiter.sv               *
 *           full/tmrg_src/rr_arb_tree.sv full/tmrg_src/floo_output_arbiter.sv                      *
 *           full/tmrg_src/floo_reduction_arbiter.sv full/tmrg_src/floo_reduction_sync.sv           *
 *           full/tmrg_src/stream_arbiter.sv full/tmrg_src/stream_arbiter_flushable.sv              *
 *           full/tmrg_src/floo_vc_arbiter.sv full/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=full/tmrg_files                                                                    *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: full/tmrg_src/stream_fifo_optimal_wrap.sv                                              *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912                           *
 *           Modification time : 2025-12-30 16:14:02.004141                                         *
 *           File Size         : 4040                                                               *
 *           MD5 hash          : be00696890cd43cb0f14255609225a26                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module stream_fifo_optimal_wrapTMR #(
  parameter int unsigned Depth = 32'd8,
  parameter type type_t = logic,
  parameter bit PrintInfo = 1'b0,
  parameter int unsigned AddrDepth = (Depth>32'd1) ? $clog2(Depth) : 32'd1
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic flush_iA,
  input logic flush_iB,
  input logic flush_iC,
  input logic testmode_iA,
  input logic testmode_iB,
  input logic testmode_iC,
  output logic [AddrDepth - 1:0] usage_oA,
  output logic [AddrDepth - 1:0] usage_oB,
  output logic [AddrDepth - 1:0] usage_oC,
  input type_t data_iA,
  input type_t data_iB,
  input type_t data_iC,
  input logic valid_iA,
  input logic valid_iB,
  input logic valid_iC,
  output logic ready_oA,
  output logic ready_oB,
  output logic ready_oC,
  output type_t data_oA,
  output type_t data_oB,
  output type_t data_oC,
  output logic valid_oA,
  output logic valid_oB,
  output logic valid_oC,
  input logic ready_iA,
  input logic ready_iB,
  input logic ready_iC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire i_stream_fifotmrErrorC;
wire i_spill_register_flushabletmrErrorC;
wire i_stream_fifotmrErrorB;
wire i_spill_register_flushabletmrErrorB;
wire i_stream_fifotmrErrorA;
wire i_spill_register_flushabletmrErrorA;
if (Depth==32'd2)
  begin : gen_spill

    spill_register_flushableTMR #(.T(type_t), .Bypass(1'b0)) i_spill_register_flushable (
        .clk_iA(clk_iA),
        .clk_iB(clk_iB),
        .clk_iC(clk_iC),
        .rst_niA(rst_niA),
        .rst_niB(rst_niB),
        .rst_niC(rst_niC),
        .flush_iA(flush_iA),
        .flush_iB(flush_iB),
        .flush_iC(flush_iC),
        .valid_iA(valid_iA),
        .valid_iB(valid_iB),
        .valid_iC(valid_iC),
        .ready_oA(ready_oA),
        .ready_oB(ready_oB),
        .ready_oC(ready_oC),
        .data_iA(data_iA),
        .data_iB(data_iB),
        .data_iC(data_iC),
        .valid_oA(valid_oA),
        .valid_oB(valid_oB),
        .valid_oC(valid_oC),
        .ready_iA(ready_iA),
        .ready_iB(ready_iB),
        .ready_iC(ready_iC),
        .data_oA(data_oA),
        .data_oB(data_oB),
        .data_oC(data_oC),
        .tmrErrorA(i_spill_register_flushabletmrErrorA),
        .tmrErrorB(i_spill_register_flushabletmrErrorB),
        .tmrErrorC(i_spill_register_flushabletmrErrorC)
      );
    assign usage_oA = 'x;
    assign usage_oB = 'x;
    assign usage_oC = 'x;
    assign i_stream_fifotmrErrorA = 1'b0;
    assign i_stream_fifotmrErrorB = 1'b0;
    assign i_stream_fifotmrErrorC = 1'b0;
  end
if (Depth>32'd2)
  begin : gen_fifo

    stream_fifoTMR #(.DEPTH(Depth), .T(type_t)) i_stream_fifo (
        .clk_iA(clk_iA),
        .clk_iB(clk_iB),
        .clk_iC(clk_iC),
        .rst_niA(rst_niA),
        .rst_niB(rst_niB),
        .rst_niC(rst_niC),
        .flush_iA(flush_iA),
        .flush_iB(flush_iB),
        .flush_iC(flush_iC),
        .testmode_iA(testmode_iA),
        .testmode_iB(testmode_iB),
        .testmode_iC(testmode_iC),
        .usage_oA(usage_oA),
        .usage_oB(usage_oB),
        .usage_oC(usage_oC),
        .data_iA(data_iA),
        .data_iB(data_iB),
        .data_iC(data_iC),
        .valid_iA(valid_iA),
        .valid_iB(valid_iB),
        .valid_iC(valid_iC),
        .ready_oA(ready_oA),
        .ready_oB(ready_oB),
        .ready_oC(ready_oC),
        .data_oA(data_oA),
        .data_oB(data_oB),
        .data_oC(data_oC),
        .valid_oA(valid_oA),
        .valid_oB(valid_oB),
        .valid_oC(valid_oC),
        .ready_iA(ready_iA),
        .ready_iB(ready_iB),
        .ready_iC(ready_iC),
        .tmrErrorA(i_stream_fifotmrErrorA),
        .tmrErrorB(i_stream_fifotmrErrorB),
        .tmrErrorC(i_stream_fifotmrErrorC)
      );
    assign i_spill_register_flushabletmrErrorA = 1'b0;
    assign i_spill_register_flushabletmrErrorB = 1'b0;
    assign i_spill_register_flushabletmrErrorC = 1'b0;
  end
assign tmrErrorA = i_spill_register_flushabletmrErrorA|i_stream_fifotmrErrorA;
assign tmrErrorB = i_spill_register_flushabletmrErrorB|i_stream_fifotmrErrorB;
assign tmrErrorC = i_spill_register_flushabletmrErrorC|i_stream_fifotmrErrorC;
endmodule : stream_fifo_optimal_wrapTMR

