/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/stream_arbiterTMR.sv                                                        *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 30/12/2025 17:23:19                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/floo_nw_router.sv tmrg_src/floo_router.sv  *
 *           tmrg_src/stream_fifo_optimal_wrap.sv tmrg_src/spill_register_flushable.sv              *
 *           tmrg_src/stream_fifo.sv tmrg_src/fifo_v3.sv tmrg_src/floo_route_select.sv              *
 *           tmrg_src/floo_route_xymask.sv tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv     *
 *           tmrg_src/floo_wormhole_arbiter.sv tmrg_src/rr_arb_tree.sv tmrg_src/floo_output_arbiter.sv *
 *           tmrg_src/floo_reduction_arbiter.sv tmrg_src/floo_reduction_sync.sv                     *
 *           tmrg_src/stream_arbiter.sv tmrg_src/stream_arbiter_flushable.sv                        *
 *           tmrg_src/floo_vc_arbiter.sv tmrg_src/lzc.sv --top-module=floo_nw_router --tmr-         *
 *           dir=tmrg_files                                                                         *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/stream_arbiter.sv                                                             *
 *           Git SHA           : File not in git repository!                                        *
 *           Modification time : 2025-12-30 16:35:52.883471                                         *
 *           File Size         : 2115                                                               *
 *           MD5 hash          : 956e4976680b71cc9a810a488172ff27                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module stream_arbiterTMR #(
  parameter type      DATA_T = logic,   // Vivado requires a default value for type parameters.
  parameter integer N_INP =  - 1,
  parameter ARBITER = "rr"
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input DATA_T [N_INP - 1:0] inp_data_iA,
  input DATA_T [N_INP - 1:0] inp_data_iB,
  input DATA_T [N_INP - 1:0] inp_data_iC,
  input logic [N_INP - 1:0] inp_valid_iA,
  input logic [N_INP - 1:0] inp_valid_iB,
  input logic [N_INP - 1:0] inp_valid_iC,
  output logic [N_INP - 1:0] inp_ready_oA,
  output logic [N_INP - 1:0] inp_ready_oB,
  output logic [N_INP - 1:0] inp_ready_oC,
  output DATA_T oup_data_oA,
  output DATA_T oup_data_oB,
  output DATA_T oup_data_oC,
  output logic oup_valid_oA,
  output logic oup_valid_oB,
  output logic oup_valid_oC,
  input logic oup_ready_iA,
  input logic oup_ready_iB,
  input logic oup_ready_iC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire i_arbtmrErrorC;
wire i_arbtmrErrorB;
wire i_arbtmrErrorA;

stream_arbiter_flushableTMR #(.DATA_T(DATA_T), .N_INP(N_INP), .ARBITER(ARBITER)) i_arb (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .flush_iA(1'b0),
    .flush_iB(1'b0),
    .flush_iC(1'b0),
    .inp_data_iA(inp_data_iA),
    .inp_data_iB(inp_data_iB),
    .inp_data_iC(inp_data_iC),
    .inp_valid_iA(inp_valid_iA),
    .inp_valid_iB(inp_valid_iB),
    .inp_valid_iC(inp_valid_iC),
    .inp_ready_oA(inp_ready_oA),
    .inp_ready_oB(inp_ready_oB),
    .inp_ready_oC(inp_ready_oC),
    .oup_data_oA(oup_data_oA),
    .oup_data_oB(oup_data_oB),
    .oup_data_oC(oup_data_oC),
    .oup_valid_oA(oup_valid_oA),
    .oup_valid_oB(oup_valid_oB),
    .oup_valid_oC(oup_valid_oC),
    .oup_ready_iA(oup_ready_iA),
    .oup_ready_iB(oup_ready_iB),
    .oup_ready_iC(oup_ready_iC),
    .tmrErrorA(i_arbtmrErrorA),
    .tmrErrorB(i_arbtmrErrorB),
    .tmrErrorC(i_arbtmrErrorC)
  );
assign tmrErrorA = i_arbtmrErrorA;
assign tmrErrorB = i_arbtmrErrorB;
assign tmrErrorC = i_arbtmrErrorC;
endmodule

