/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/addr_decodeTMR.sv                                                     *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:51                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/addr_decode.sv                                                          *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/addr_decode.sv) *
 *           Modification time : 2026-04-29 05:41:13.094993                                         *
 *           File Size         : 5080                                                               *
 *           MD5 hash          : 59727dabdc9059677e27ff0008ad9505                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module addr_decodeTMR #(
  parameter int unsigned NoIndices = 32'd0,
  parameter int unsigned NoRules = 32'd0,
  parameter type         addr_t    = logic,
  parameter type         rule_t    = logic,
  parameter bit Napot = 0,
  parameter int unsigned IdxWidth = cf_math_pkg::idx_width(NoIndices),
  parameter type         idx_t     = logic [IdxWidth-1:0]
) (
  input addr_t addr_i,
  input rule_t [NoRules - 1:0] addr_map_i,
  output idx_t idx_o,
  output logic dec_valid_o,
  output logic dec_error_o,
  input logic en_default_idx_i,
  input idx_t default_idx_i
);

addr_decode_dyncTMR #(.NoRules(NoRules), .addr_t(addr_t), .rule_t(rule_t), .Napot(Napot), .idx_t(idx_t)) i_addr_decode_dync (
    .addr_i(addr_i),
    .addr_map_i(addr_map_i),
    .idx_o(idx_o),
    .dec_valid_o(dec_valid_o),
    .dec_error_o(dec_error_o),
    .en_default_idx_i(en_default_idx_i),
    .default_idx_i(default_idx_i),
    .config_ongoing_i(1'b0)
  );
endmodule

