/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/fifo_v3TMR.sv                                                         *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:50                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/fifo_v3.sv                                                              *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/fifo_v3.sv) *
 *           Modification time : 2026-05-01 01:36:46.836593                                         *
 *           File Size         : 6565                                                               *
 *           MD5 hash          : 2b3ab6db598054cf17f59e4ccdf2cdea                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module fifo_v3TMR #(
  parameter bit FALL_THROUGH = 1'b0,
  parameter int unsigned DATA_WIDTH = 32,
  parameter int unsigned DEPTH = 8,
  parameter type dtype                = logic [DATA_WIDTH-1:0],
  parameter int unsigned ADDR_DEPTH = (DEPTH>1) ? $clog2(DEPTH) : 1
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic flush_i,
  input logic testmode_i,
  output logic full_o,
  output logic empty_o,
  output logic [ADDR_DEPTH - 1:0] usage_o,
  input dtype data_i,
  input logic push_i,
  output dtype data_o,
  input logic pop_i,
  output tmrError
);
localparam int unsigned FifoDepth = (DEPTH>0) ? DEPTH : 1;
wire [ (ADDR_DEPTH-1) :0] write_pointer_nC;
wire [ (ADDR_DEPTH-1) :0] write_pointer_nB;
wire [ (ADDR_DEPTH-1) :0] write_pointer_nA;
wire [ (ADDR_DEPTH) :0] status_cnt_nC;
wire [ (ADDR_DEPTH) :0] status_cnt_nB;
wire [ (ADDR_DEPTH) :0] status_cnt_nA;
wire [ (ADDR_DEPTH-1) :0] read_pointer_nC;
wire [ (ADDR_DEPTH-1) :0] read_pointer_nB;
wire [ (ADDR_DEPTH-1) :0] read_pointer_nA;
wire dtype [ (FifoDepth-1) :0] mem_nC;
wire dtype [ (FifoDepth-1) :0] mem_nB;
wire dtype [ (FifoDepth-1) :0] mem_nA;
wire gate_clockC;
wire gate_clockB;
wire gate_clockA;
wire flush_iC;
wire flush_iB;
wire flush_iA;
wire write_pointer_qTmrError;
wire status_cnt_qTmrError;
wire read_pointer_qTmrError;
wire mem_qTmrError;
wire [ (ADDR_DEPTH-1) :0] write_pointer_q;
wire [ (ADDR_DEPTH) :0] status_cnt_q;
wire [ (ADDR_DEPTH-1) :0] read_pointer_q;
wire dtype [ (FifoDepth-1) :0] mem_q;
logic gate_clock;
logic [ADDR_DEPTH - 1:0] read_pointer_n;
logic [ADDR_DEPTH - 1:0] write_pointer_n;
logic [ADDR_DEPTH - 1:0] read_pointer_qA;
logic [ADDR_DEPTH - 1:0] read_pointer_qB;
logic [ADDR_DEPTH - 1:0] read_pointer_qC;
logic [ADDR_DEPTH - 1:0] write_pointer_qA;
logic [ADDR_DEPTH - 1:0] write_pointer_qB;
logic [ADDR_DEPTH - 1:0] write_pointer_qC;
logic [ADDR_DEPTH:0] status_cnt_n;
logic [ADDR_DEPTH:0] status_cnt_qA;
logic [ADDR_DEPTH:0] status_cnt_qB;
logic [ADDR_DEPTH:0] status_cnt_qC;
dtype [FifoDepth - 1:0] mem_n;
dtype [FifoDepth - 1:0] mem_qA;
dtype [FifoDepth - 1:0] mem_qB;
dtype [FifoDepth - 1:0] mem_qC;
assign usage_o = status_cnt_q[ADDR_DEPTH - 1:0];
if (DEPTH==0)
  begin : gen_pass_through
    assign empty_o = ~push_i;
    assign full_o = ~pop_i;
  end

else
  begin : gen_fifo
    assign full_o =  (status_cnt_q==FifoDepth[ADDR_DEPTH:0]) ;
    assign empty_o =  (status_cnt_q==0) &~ (FALL_THROUGH&push_i) ;
  end

always_comb
  begin : read_write_comb
    read_pointer_n = read_pointer_q;
    write_pointer_n = write_pointer_q;
    status_cnt_n = status_cnt_q;
    data_o = (DEPTH==0) ? data_i : mem_q[read_pointer_q];
    mem_n = mem_q;
    gate_clock = 1'b1;
    if (push_i&&~full_o)
      begin
        mem_n[write_pointer_q] = data_i;
        gate_clock = 1'b0;
        if (write_pointer_q==FifoDepth[ADDR_DEPTH - 1:0]-1)
          write_pointer_n = '0;
        else
          write_pointer_n = write_pointer_q + 1;
        status_cnt_n = status_cnt_q + 1;
      end

    if (pop_i&&~empty_o)
      begin
        if (read_pointer_n==FifoDepth[ADDR_DEPTH - 1:0]-1)
          read_pointer_n = '0;
        else
          read_pointer_n = read_pointer_q + 1;
        status_cnt_n = status_cnt_q - 1;
      end

    if (push_i&&pop_i&&~full_o&&~empty_o)
      status_cnt_n = status_cnt_q;

    if (FALL_THROUGH&&(status_cnt_q==0)&&push_i)
      begin
        data_o = data_i;
        if (pop_i)
          begin
            status_cnt_n = status_cnt_q;
            read_pointer_n = read_pointer_q;
            write_pointer_n = write_pointer_q;
          end

      end

  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (~rst_niA)
      begin
        read_pointer_qA <= '0;
        write_pointer_qA <= '0;
        status_cnt_qA <= '0;
      end
    else
      begin
        if (flush_iA)
          begin
            read_pointer_qA <= '0;
            write_pointer_qA <= '0;
            status_cnt_qA <= '0;
          end
        else
          begin
            read_pointer_qA <= read_pointer_nA;
            write_pointer_qA <= write_pointer_nA;
            status_cnt_qA <= status_cnt_nA;
          end
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (~rst_niB)
      begin
        read_pointer_qB <= '0;
        write_pointer_qB <= '0;
        status_cnt_qB <= '0;
      end
    else
      begin
        if (flush_iB)
          begin
            read_pointer_qB <= '0;
            write_pointer_qB <= '0;
            status_cnt_qB <= '0;
          end
        else
          begin
            read_pointer_qB <= read_pointer_nB;
            write_pointer_qB <= write_pointer_nB;
            status_cnt_qB <= status_cnt_nB;
          end
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (~rst_niC)
      begin
        read_pointer_qC <= '0;
        write_pointer_qC <= '0;
        status_cnt_qC <= '0;
      end
    else
      begin
        if (flush_iC)
          begin
            read_pointer_qC <= '0;
            write_pointer_qC <= '0;
            status_cnt_qC <= '0;
          end
        else
          begin
            read_pointer_qC <= read_pointer_nC;
            write_pointer_qC <= write_pointer_nC;
            status_cnt_qC <= status_cnt_nC;
          end
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (~rst_niA)
      begin
        mem_qA <= {FifoDepth{dtype' ('0) }};
      end
    else
      if (!gate_clockA||mem_qTmrError)
        begin
          mem_qA <= mem_nA;
        end

  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (~rst_niB)
      begin
        mem_qB <= {FifoDepth{dtype' ('0) }};
      end
    else
      if (!gate_clockB||mem_qTmrError)
        begin
          mem_qB <= mem_nB;
        end

  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (~rst_niC)
      begin
        mem_qC <= {FifoDepth{dtype' ('0) }};
      end
    else
      if (!gate_clockC||mem_qTmrError)
        begin
          mem_qC <= mem_nC;
        end

  end

majorityVoter #(.WIDTH( ($bits(mem_q))  *  ((((FifoDepth-1)>0) ? (FifoDepth-1) : - ( FifoDepth-1 ) )+1) )) mem_qVoter (
    .inA(mem_qA),
    .inB(mem_qB),
    .inC(mem_qC),
    .out(mem_q),
    .tmrErr(mem_qTmrError)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH-1)>0) ? (ADDR_DEPTH-1) : - ( ADDR_DEPTH-1 ) )+1) )) read_pointer_qVoter (
    .inA(read_pointer_qA),
    .inB(read_pointer_qB),
    .inC(read_pointer_qC),
    .out(read_pointer_q),
    .tmrErr(read_pointer_qTmrError)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH)>0) ? (ADDR_DEPTH) : - ( ADDR_DEPTH ) )+1) )) status_cnt_qVoter (
    .inA(status_cnt_qA),
    .inB(status_cnt_qB),
    .inC(status_cnt_qC),
    .out(status_cnt_q),
    .tmrErr(status_cnt_qTmrError)
  );

majorityVoter #(.WIDTH( ((((ADDR_DEPTH-1)>0) ? (ADDR_DEPTH-1) : - ( ADDR_DEPTH-1 ) )+1) )) write_pointer_qVoter (
    .inA(write_pointer_qA),
    .inB(write_pointer_qB),
    .inC(write_pointer_qC),
    .out(write_pointer_q),
    .tmrErr(write_pointer_qTmrError)
  );
assign tmrError = mem_qTmrError|read_pointer_qTmrError|status_cnt_qTmrError|write_pointer_qTmrError;

fanout flush_iFanout (
    .in(flush_i),
    .outA(flush_iA),
    .outB(flush_iB),
    .outC(flush_iC)
  );

fanout gate_clockFanout (
    .in(gate_clock),
    .outA(gate_clockA),
    .outB(gate_clockB),
    .outC(gate_clockC)
  );

fanout #(.WIDTH( ($bits(mem_q))  *  ((((FifoDepth-1)>0) ? (FifoDepth-1) : - ( FifoDepth-1 ) )+1) )) mem_nFanout (
    .in(mem_n),
    .outA(mem_nA),
    .outB(mem_nB),
    .outC(mem_nC)
  );

fanout #(.WIDTH( ((((ADDR_DEPTH-1)>0) ? (ADDR_DEPTH-1) : - ( ADDR_DEPTH-1 ) )+1) )) read_pointer_nFanout (
    .in(read_pointer_n),
    .outA(read_pointer_nA),
    .outB(read_pointer_nB),
    .outC(read_pointer_nC)
  );

fanout #(.WIDTH( ((((ADDR_DEPTH)>0) ? (ADDR_DEPTH) : - ( ADDR_DEPTH ) )+1) )) status_cnt_nFanout (
    .in(status_cnt_n),
    .outA(status_cnt_nA),
    .outB(status_cnt_nB),
    .outC(status_cnt_nC)
  );

fanout #(.WIDTH( ((((ADDR_DEPTH-1)>0) ? (ADDR_DEPTH-1) : - ( ADDR_DEPTH-1 ) )+1) )) write_pointer_nFanout (
    .in(write_pointer_n),
    .outA(write_pointer_nA),
    .outB(write_pointer_nB),
    .outC(write_pointer_nC)
  );
endmodule

