/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/floo_wormhole_arbiterTMR.sv                                           *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:51                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/floo_wormhole_arbiter.sv                                                *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/floo_wormhole_arbiter.sv) *
 *           Modification time : 2026-04-29 14:49:38.791286                                         *
 *           File Size         : 2586                                                               *
 *           MD5 hash          : f6babc36750dfbe90daac429dd17e9d1                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_wormhole_arbiterTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 1,
  parameter type         flit_t     = logic
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic [NumRoutes - 1:0] valid_i,
  output logic [NumRoutes - 1:0] ready_o,
  input flit_t [NumRoutes - 1:0] data_i,
  output logic valid_o,
  input logic ready_i,
  output flit_t data_o,
  output tmrError
);
typedef logic [cf_math_pkg::idx_width(NumRoutes) - 1:0] arb_idx_t;
wire [ (NumRoutes-1) :0] valid_dC;
wire [ (NumRoutes-1) :0] valid_dB;
wire [ (NumRoutes-1) :0] valid_dA;
wire ready_iC;
wire ready_iB;
wire ready_iA;
wire last_outC;
wire last_outB;
wire last_outA;
wire i_rr_arb_packetstmrError;
wire valid_qTmrError;
wire last_qTmrError;
wire [ (NumRoutes-1) :0] valid_q;
wire last_q;
logic last_out;
logic last_qA;
logic last_qB;
logic last_qC;
arb_idx_t selected_idx;
arb_idx_t valid_selected_idx;
logic [NumRoutes - 1:0] valid_d;
logic [NumRoutes - 1:0] valid_qA;
logic [NumRoutes - 1:0] valid_qB;
logic [NumRoutes - 1:0] valid_qC;

rr_arb_treeTMR #(.NumIn(NumRoutes), .ExtPrio(1'b0), .AxiVldRdy(1'b1), .LockIn(1'b1), .FairArb(1'b1)) i_rr_arb_packets (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .flush_i(1'b0),
    .rr_i('0),
    .req_i(valid_d),
    .gnt_o(),
    .data_i('0),
    .req_o(),
    .gnt_i(ready_i&last_out),
    .data_o(),
    .idx_o(selected_idx),
    .tmrError(i_rr_arb_packetstmrError)
  );
assign valid_selected_idx = (| valid_i ) ? selected_idx : '0;
assign valid_o = valid_i[valid_selected_idx];
assign data_o = data_i[valid_selected_idx];

always_comb
  begin : proc_ready_o
    ready_o = '0;
    ready_o[valid_selected_idx] = (| valid_i ) ? ready_i : '0;
  end
assign last_out = data_o.hdr.last&valid_o;

always_comb
  begin : proc_valid
    valid_d = valid_q;
    if (valid_q=='0||last_q)
      begin
        valid_d = valid_i;
      end

  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin : ps_valid_qA
    if (!rst_niA)
      valid_qA <= '0;
    else
      valid_qA <= valid_dA;
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin : ps_valid_qB
    if (!rst_niB)
      valid_qB <= '0;
    else
      valid_qB <= valid_dB;
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin : ps_valid_qC
    if (!rst_niC)
      valid_qC <= '0;
    else
      valid_qC <= valid_dC;
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin : ps_last_qA
    if (!rst_niA)
      last_qA <= '0;
    else
      last_qA <= last_outA&ready_iA;
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin : ps_last_qB
    if (!rst_niB)
      last_qB <= '0;
    else
      last_qB <= last_outB&ready_iB;
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin : ps_last_qC
    if (!rst_niC)
      last_qC <= '0;
    else
      last_qC <= last_outC&ready_iC;
  end

majorityVoter last_qVoter (
    .inA(last_qA),
    .inB(last_qB),
    .inC(last_qC),
    .out(last_q),
    .tmrErr(last_qTmrError)
  );

majorityVoter #(.WIDTH( ((((NumRoutes-1)>0) ? (NumRoutes-1) : - ( NumRoutes-1 ) )+1) )) valid_qVoter (
    .inA(valid_qA),
    .inB(valid_qB),
    .inC(valid_qC),
    .out(valid_q),
    .tmrErr(valid_qTmrError)
  );
assign tmrError = last_qTmrError|valid_qTmrError | i_rr_arb_packetstmrError;

fanout last_outFanout (
    .in(last_out),
    .outA(last_outA),
    .outB(last_outB),
    .outC(last_outC)
  );

fanout ready_iFanout (
    .in(ready_i),
    .outA(ready_iA),
    .outB(ready_iB),
    .outC(ready_iC)
  );

fanout #(.WIDTH( ((((NumRoutes-1)>0) ? (NumRoutes-1) : - ( NumRoutes-1 ) )+1) )) valid_dFanout (
    .in(valid_d),
    .outA(valid_dA),
    .outB(valid_dB),
    .outC(valid_dC)
  );
endmodule

