/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/floo_route_xymaskTMR.sv                                               *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:51                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/floo_route_xymask.sv                                                    *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/floo_route_xymask.sv) *
 *           Modification time : 2026-04-29 05:41:20.133057                                         *
 *           File Size         : 4590                                                               *
 *           MD5 hash          : 0b3cb79775955f982de553041ef1af6e                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_route_xymaskTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 0,
  parameter bit FwdMode = 1'b1,
  parameter type         flit_t        = logic,
  parameter type         id_t          = logic
) (
  input flit_t channel_i,
  input id_t xy_id_i,
  output logic [NumRoutes - 1:0] route_sel_o
);
logic [NumRoutes - 1:0] route_sel;
id_t dst_id;
id_t mask_in;
id_t src_id;
id_t dst_id_max;
id_t dst_id_min;
logic x_matched;
logic y_matched;
assign dst_id = (FwdMode) ? channel_i.hdr.dst_id : channel_i.hdr.src_id;
assign src_id = (FwdMode) ? channel_i.hdr.src_id : channel_i.hdr.dst_id;
assign mask_in = (FwdMode&&channel_i.hdr.commtype==ParallelReduction) ? '0 : channel_i.hdr.mask;
assign dst_id_max.x = dst_id.x|mask_in.x;
assign dst_id_max.y = dst_id.y|mask_in.y;
assign dst_id_min.x = dst_id.x& (~ mask_in.x ) ;
assign dst_id_min.y = dst_id.y& (~ mask_in.y ) ;
assign x_matched = & (mask_in.x|~(xy_id_i.x^dst_id.x)) ;
assign y_matched = & (mask_in.y|~(xy_id_i.y^dst_id.y)) ;

always_comb
  begin
    route_sel = '0;
    if (FwdMode)
      begin : gen_out_mask
        if (x_matched&&y_matched)
          begin
            route_sel[Eject] = 1;
          end

        if (xy_id_i.y==src_id.y)
          begin
            if (xy_id_i.x>=src_id.x&&xy_id_i.x<dst_id_max.x)
              begin
                route_sel[East] = 1;
              end

            if (xy_id_i.x<=src_id.x&&xy_id_i.x>dst_id_min.x)
              begin
                route_sel[West] = 1;
              end

          end

        if (x_matched)
          begin
            if (xy_id_i.y>=src_id.y&&xy_id_i.y<dst_id_max.y)
              begin
                route_sel[North] = 1;
              end

            if (xy_id_i.y<=src_id.y&&xy_id_i.y>dst_id_min.y)
              begin
                route_sel[South] = 1;
              end

          end

      end
    else
      begin : gen_in_mask
        if (x_matched&&y_matched)
          begin
            route_sel[Eject] = 1;
          end

        if (xy_id_i.x==src_id.x)
          begin
            if (xy_id_i.y>=src_id.y&&xy_id_i.y<dst_id_max.y)
              begin
                route_sel[North] = 1;
              end

            if (xy_id_i.y<=src_id.y&&xy_id_i.y>dst_id_min.y)
              begin
                route_sel[South] = 1;
              end

          end

        if (y_matched)
          begin
            if (xy_id_i.x>=src_id.x&&xy_id_i.x<dst_id_max.x)
              begin
                route_sel[East] = 1;
              end

            if (xy_id_i.x<=src_id.x&&xy_id_i.x>dst_id_min.x)
              begin
                route_sel[West] = 1;
              end

          end

      end
  end
assign route_sel_o = route_sel;
endmodule

