/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/floo_reduction_syncTMR.sv                                             *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:51                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/floo_reduction_sync.sv                                                  *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/floo_reduction_sync.sv) *
 *           Modification time : 2026-04-29 05:41:18.517042                                         *
 *           File Size         : 2490                                                               *
 *           MD5 hash          : 6a9c24a06f59308954f580304dfe0c67                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_reduction_syncTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 1,
  parameter type         arb_idx_t  = logic,
  parameter type         flit_t     = logic,
  parameter type         id_t       = logic
) (
  input arb_idx_t sel_i,
  input flit_t [NumRoutes - 1:0] data_i,
  input logic [NumRoutes - 1:0] valid_i,
  input id_t xy_id_i,
  output logic valid_o,
  output logic [NumRoutes - 1:0] in_route_mask_o
);
logic [NumRoutes - 1:0] compare_same;
logic [NumRoutes - 1:0] same_and_valid;
logic all_reduction_srcs_valid;

floo_route_xymaskTMR #(.NumRoutes(NumRoutes), .flit_t(flit_t), .id_t(id_t), .FwdMode(0)) i_route_xymask (
    .channel_i(data_i[sel_i]),
    .xy_id_i(xy_id_i),
    .route_sel_o(in_route_mask_o)
  );
for(genvar in = 0; in<NumRoutes; in++)
  begin : gen_routes
    assign compare_same[in] =  ((data_i[in].hdr.mask==data_i[sel_i].hdr.mask)&&(data_i[in].hdr.dst_id==data_i[sel_i].hdr.dst_id)) ;
    assign same_and_valid[in] =  (data_i[sel_i].hdr.dst_id==xy_id_i&&in==Eject) || (compare_same[in]&valid_i[in]) ;
  end
assign all_reduction_srcs_valid = & (same_and_valid|~in_route_mask_o) ;
assign valid_o = (in_route_mask_o=='0) ? 1'b0 : (| valid_i & all_reduction_srcs_valid );
endmodule

