/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/floo_vc_arbiterTMR.sv                                                 *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:51                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/floo_vc_arbiter.sv                                                      *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/floo_vc_arbiter.sv) *
 *           Modification time : 2026-04-29 14:49:48.574374                                         *
 *           File Size         : 2795                                                               *
 *           MD5 hash          : 59a3ba67d56971038b1190003badcdbe                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_vc_arbiterTMR import floo_pkg::*; #(
  parameter int unsigned NumVirtChannels = 1,
  parameter type         flit_t          = logic,
  parameter int unsigned NumPhysChannels = 1
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic [NumVirtChannels - 1:0] valid_i,
  output logic [NumVirtChannels - 1:0] ready_o,
  input flit_t [NumVirtChannels - 1:0] data_i,
  input logic [NumVirtChannels - 1:0] ready_i,
  output logic [NumVirtChannels - 1:0] valid_o,
  output flit_t [NumPhysChannels - 1:0] data_o,
  output tmrError
);
wor i_rr_vc_arbitertmrError;
assign i_rr_vc_arbitertmrError = 1'b0;
if (NumVirtChannels==NumPhysChannels)
  begin : gen_virt_eq_phys
    assign valid_o = valid_i;
    assign ready_o = ready_i;
    assign data_o = data_i;
  end

else
  if (NumPhysChannels==1)
      begin : gen_single_phys
      typedef logic [$clog2(NumVirtChannels) - 1:0] arb_idx_t;
arb_idx_t vc_arb_idx;
logic [NumVirtChannels - 1:0] vc_arb_req_in;
logic vc_arb_req_out;
logic vc_arb_gnt_in;
      assign vc_arb_req_in = valid_i&ready_i;
      assign vc_arb_gnt_in = ready_i[vc_arb_idx];

      always_comb
        begin
          valid_o = '0;
          valid_o[vc_arb_idx] = vc_arb_req_out;
        end

      rr_arb_treeTMR #(.NumIn(NumVirtChannels), .DataType(flit_t), .AxiVldRdy(1'b0), .LockIn(1'b0)) i_rr_vc_arbiter (
          .clk_iA(clk_iA),
          .clk_iB(clk_iB),
          .clk_iC(clk_iC),
          .rst_niA(rst_niA),
          .rst_niB(rst_niB),
          .rst_niC(rst_niC),
          .flush_i(1'b0),
          .rr_i('0),
          .req_i(vc_arb_req_in),
          .gnt_o(ready_o),
          .data_i(data_i),
          .req_o(vc_arb_req_out),
          .gnt_i(vc_arb_gnt_in),
          .data_o(data_o),
          .idx_o(vc_arb_idx),
          .tmrError(i_rr_vc_arbitertmrError)
        );
    end
assign tmrError = i_rr_vc_arbitertmrError;
endmodule

