/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/floo_route_selectTMR.sv                                               *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:50                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/floo_route_select.sv                                                    *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/floo_route_select.sv) *
 *           Modification time : 2026-04-29 14:49:36.758267                                         *
 *           File Size         : 6800                                                               *
 *           MD5 hash          : 1958a8cbe848744008bc8a7dd7586547                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_route_selectTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 0,
  parameter route_algo_e RouteAlgo = IdTable,
  parameter bit LockRouting = 1'b1,
  parameter int unsigned IdWidth = 0,
  parameter int unsigned NumAddrRules = 0,
  parameter int unsigned RouteSelWidth = $clog2(NumRoutes),
  parameter bit EnMultiCast = 1'b0,
  parameter type         flit_t           = logic,
  parameter type         addr_rule_t      = logic,
  parameter type         id_t             = logic[IdWidth-1:0]
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic test_enable_i,
  input id_t xy_id_i,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_i,
  input flit_t channel_i,
  input logic valid_i,
  input logic ready_i,
  output flit_t channel_o,
  output logic [NumRoutes - 1:0] route_sel_o,
  output logic [RouteSelWidth - 1:0] route_sel_id_o,
  output tmrError
);
wire [ (RouteSelWidth-1) :0] route_sel_idC;
wire [ (RouteSelWidth-1) :0] route_sel_idB;
wire [ (RouteSelWidth-1) :0] route_sel_idA;
wire [ (NumRoutes-1) :0] route_selC;
wire [ (NumRoutes-1) :0] route_selB;
wire [ (NumRoutes-1) :0] route_selA;
wire locked_route_dC;
wire locked_route_dB;
wire locked_route_dA;
wor route_sel_qTmrError;
wor route_sel_id_qTmrError;
wor locked_route_qTmrError;
wire [ (NumRoutes-1) :0] route_sel_q;
wire [ (RouteSelWidth-1) :0] route_sel_id_q;
wire locked_route_q;
logic [NumRoutes - 1:0] route_sel;
logic [RouteSelWidth - 1:0] route_sel_id;
if (RouteAlgo==IdTable)
  begin : gen_id_table
logic [RouteSelWidth - 1:0] id_table_result;
    assign channel_o = channel_i;

    addr_decodeTMR #(.NoIndices(NumRoutes), .NoRules(NumAddrRules), .addr_t(id_t), .rule_t(addr_rule_t), .Napot(0)) i_id_decode (
        .addr_i(channel_i.hdr.dst_id),
        .addr_map_i(id_route_map_i),
        .idx_o(id_table_result),
        .dec_valid_o(),
        .dec_error_o(),
        .default_idx_i('0),
        .en_default_idx_i('0)
      );

    always_comb
      begin : proc_route_sel
        route_sel_id = id_table_result;
        route_sel = '0;
        route_sel[id_table_result] = 1'b1;
      end
  end

else
  if (RouteAlgo==SourceRouting)
      begin : gen_consumption

      always_comb
        begin : proc_route_sel
          route_sel_id = channel_i.hdr.dst_id[RouteSelWidth - 1:0];
          route_sel = '0;
          route_sel[route_sel_id] = 1'b1;
          channel_o = channel_i;
          channel_o.hdr.dst_id = channel_i.hdr.dst_id>>RouteSelWidth;
        end
    end

  else
      if (RouteAlgo==XYRouting)
          begin : gen_xy_routing
        if (EnMultiCast)
                  begin : gen_mcast_route_sel

            floo_route_xymaskTMR #(.NumRoutes(NumRoutes), .flit_t(flit_t), .id_t(id_t), .FwdMode(1)) i_route_xymask (
                .channel_i(channel_i),
                .xy_id_i(xy_id_i),
                .route_sel_o(route_sel)
              );
            assign route_sel_id = '0;
          end

        else
                  begin : gen_route_sel
id_t id_in;
            assign id_in = id_t' (channel_i.hdr.dst_id) ;

            always_comb
              begin
                route_sel_id = East;
                if (id_in.x==xy_id_i.x&&id_in.y==xy_id_i.y)
                  begin
                    route_sel_id = Eject + channel_i.hdr.dst_id.port_id;
                  end
                else
                  if (id_in.x==xy_id_i.x)
                    begin
                      if (id_in.y<xy_id_i.y)
                        begin
                          route_sel_id = South;
                        end
                      else
                        begin
                          route_sel_id = North;
                        end
                    end
                  else
                    begin
                      if (id_in.x<xy_id_i.x)
                        begin
                          route_sel_id = West;
                        end
                      else
                        begin
                          route_sel_id = East;
                        end
                    end
                route_sel = '0;
                route_sel[route_sel_id] = 1'b1;
              end
          end
        assign channel_o = channel_i;
      end

    else
          begin : gen_err
initial
  begin
            $fatal(1, "Routing algorithm unknown");
          end
      end
if (LockRouting)
  begin : gen_lock
logic locked_route_d;
logic locked_route_qA;
logic locked_route_qB;
logic locked_route_qC;

    always_comb
      begin
        locked_route_d = locked_route_q;
        if (ready_i&&valid_i)
          begin
            locked_route_d = ~channel_i.hdr.last;
          end

      end
logic [NumRoutes - 1:0] route_sel_qA;
logic [NumRoutes - 1:0] route_sel_qB;
logic [NumRoutes - 1:0] route_sel_qC;
logic [RouteSelWidth - 1:0] route_sel_id_qA;
logic [RouteSelWidth - 1:0] route_sel_id_qB;
logic [RouteSelWidth - 1:0] route_sel_id_qC;
    assign route_sel_o = locked_route_q ? route_sel_q : route_sel;
    assign route_sel_id_o = locked_route_q ? route_sel_id_q : route_sel_id;

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_locked_route_qA
        if (!rst_niA)
          locked_route_qA <= '0;
        else
          locked_route_qA <= locked_route_dA;
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_locked_route_qB
        if (!rst_niB)
          locked_route_qB <= '0;
        else
          locked_route_qB <= locked_route_dB;
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_locked_route_qC
        if (!rst_niC)
          locked_route_qC <= '0;
        else
          locked_route_qC <= locked_route_dC;
      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_route_sel_qA
        if (!rst_niA)
          route_sel_qA <= '0;
        else
          if (~locked_route_qA)
            route_sel_qA <= route_selA;

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_route_sel_qB
        if (!rst_niB)
          route_sel_qB <= '0;
        else
          if (~locked_route_qB)
            route_sel_qB <= route_selB;

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_route_sel_qC
        if (!rst_niC)
          route_sel_qC <= '0;
        else
          if (~locked_route_qC)
            route_sel_qC <= route_selC;

      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_route_sel_id_qA
        if (!rst_niA)
          route_sel_id_qA <= '0;
        else
          if (~locked_route_qA)
            route_sel_id_qA <= route_sel_idA;

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_route_sel_id_qB
        if (!rst_niB)
          route_sel_id_qB <= '0;
        else
          if (~locked_route_qB)
            route_sel_id_qB <= route_sel_idB;

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_route_sel_id_qC
        if (!rst_niC)
          route_sel_id_qC <= '0;
        else
          if (~locked_route_qC)
            route_sel_id_qC <= route_sel_idC;

      end
`ifndef TARGET_SYNTHESIS

    always @( posedge clk_iA )
      begin
        if (ready_i&&valid_i&&locked_route_q&&((route_sel_id_q!=route_sel_id)||(route_sel_q!=route_sel)))
          $warning("Mismatch in route selection!");

      end
`endif

majorityVoter locked_route_qVoter (
    .inA(locked_route_qA),
    .inB(locked_route_qB),
    .inC(locked_route_qC),
    .out(locked_route_q),
    .tmrErr(locked_route_qTmrError)
  );

majorityVoter #(.WIDTH( ((((RouteSelWidth-1)>0) ? (RouteSelWidth-1) : - ( RouteSelWidth-1 ) )+1) )) route_sel_id_qVoter (
    .inA(route_sel_id_qA),
    .inB(route_sel_id_qB),
    .inC(route_sel_id_qC),
    .out(route_sel_id_q),
    .tmrErr(route_sel_id_qTmrError)
  );

majorityVoter #(.WIDTH( ((((NumRoutes-1)>0) ? (NumRoutes-1) : - ( NumRoutes-1 ) )+1) )) route_sel_qVoter (
    .inA(route_sel_qA),
    .inB(route_sel_qB),
    .inC(route_sel_qC),
    .out(route_sel_q),
    .tmrErr(route_sel_qTmrError)
  );

fanout locked_route_dFanout (
    .in(locked_route_d),
    .outA(locked_route_dA),
    .outB(locked_route_dB),
    .outC(locked_route_dC)
  );
  end

else
  begin : gen_no_lock
    assign route_sel_o = route_sel;
    assign route_sel_id_o = route_sel_id;
    assign locked_route_qTmrError = 1'b0;
    assign route_sel_id_qTmrError = 1'b0;
    assign route_sel_qTmrError = 1'b0;
  end
assign tmrError = locked_route_qTmrError|route_sel_id_qTmrError|route_sel_qTmrError;

fanout #(.WIDTH( ((((NumRoutes-1)>0) ? (NumRoutes-1) : - ( NumRoutes-1 ) )+1) )) route_selFanout (
    .in(route_sel),
    .outA(route_selA),
    .outB(route_selB),
    .outC(route_selC)
  );

fanout #(.WIDTH( ((((RouteSelWidth-1)>0) ? (RouteSelWidth-1) : - ( RouteSelWidth-1 ) )+1) )) route_sel_idFanout (
    .in(route_sel_id),
    .outA(route_sel_idA),
    .outB(route_sel_idB),
    .outC(route_sel_idC)
  );
endmodule

