/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/floo_routerTMR.sv                                                     *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:50                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/floo_router.sv                                                          *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/floo_router.sv) *
 *           Modification time : 2026-04-29 14:49:34.466247                                         *
 *           File Size         : 12328                                                              *
 *           MD5 hash          : b70131447ee0b9c5196969a003530c17                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_routerTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 0,
  parameter int unsigned NumInput = NumRoutes,
  parameter int unsigned NumOutput = NumRoutes,
  parameter int unsigned NumVirtChannels = 0,
  parameter int unsigned NumPhysChannels = 1,
  parameter int unsigned InFifoDepth = 0,
  parameter int unsigned OutFifoDepth = 0,
  parameter route_algo_e RouteAlgo = IdTable,
  parameter int unsigned IdWidth = 0,
  parameter type         id_t             = logic[IdWidth-1:0],
  parameter int unsigned NumAddrRules = 1,
  parameter bit XYRouteOpt = 1'b1,
  parameter bit NoLoopback = 1'b1,
  parameter bit EnMultiCast = 1'b0,
  parameter bit EnReduction = 1'b0,
  parameter type         addr_rule_t      = logic,
  parameter type         flit_t           = logic,
  parameter type         payload_t        = logic,
  parameter payload_t NarrowRspMask = '0,
  parameter payload_t WideRspMask = '0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic test_enable_i,
  input id_t xy_id_i,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_i,
  input logic [NumInput - 1:0] [NumVirtChannels - 1:0] valid_i,
  output logic [NumInput - 1:0] [NumVirtChannels - 1:0] ready_o,
  input flit_t [NumInput - 1:0] [NumPhysChannels - 1:0] data_i,
  output logic [NumOutput - 1:0] [NumVirtChannels - 1:0] valid_o,
  input logic [NumOutput - 1:0] [NumVirtChannels - 1:0] ready_i,
  output flit_t [NumOutput - 1:0] [NumPhysChannels - 1:0] data_o,
  output tmrError
);
wire [ (NumInput-1) :0] [ (NumVirtChannels-1) :0] [ (NumOutput-1) :0] past_handshakes_dC;
wire [ (NumInput-1) :0] [ (NumVirtChannels-1) :0] [ (NumOutput-1) :0] past_handshakes_dB;
wire [ (NumInput-1) :0] [ (NumVirtChannels-1) :0] [ (NumOutput-1) :0] past_handshakes_dA;
wor i_wormhole_arbitertmrError;
wor i_vc_arbitertmrError;
wor i_stream_fifotmrError;
wor i_route_selecttmrError;
wor i_output_arbitertmrError;
assign i_wormhole_arbitertmrError = 1'b0;
assign i_vc_arbitertmrError       = 1'b0;
assign i_stream_fifotmrError      = 1'b0;
assign i_route_selecttmrError     = 1'b0;
assign i_output_arbitertmrError   = 1'b0;
wor past_handshakes_qTmrError;
wire [ (NumInput-1) :0] [ (NumVirtChannels-1) :0] [ (NumOutput-1) :0] past_handshakes_q;
flit_t [NumInput - 1:0] [NumVirtChannels - 1:0] in_data;
flit_t [NumInput - 1:0] [NumVirtChannels - 1:0] in_routed_data;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] in_valid;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] in_ready;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] route_mask;
for(genvar in = 0; in<NumInput; in++)
  begin : gen_input
    for(genvar v = 0; v<NumVirtChannels; v++)
          begin : gen_virt_input
logic [cf_math_pkg::idx_width(NumPhysChannels) - 1:0] in_p;
        if (NumPhysChannels==1)
                  begin : gen_single_phys
            assign in_p = '0;
          end

        else
                  if (NumPhysChannels==NumVirtChannels)
                      begin : gen_virt_eq_phys
              assign in_p = v;
            end

          else
                      begin : gen_odd_phys
            end

        (* ungroup *) stream_fifo_optimal_wrapTMR #(.Depth(InFifoDepth), .type_t(flit_t)) i_stream_fifo (
            .clk_iA(clk_iA),
            .clk_iB(clk_iB),
            .clk_iC(clk_iC),
            .rst_niA(rst_niA),
            .rst_niB(rst_niB),
            .rst_niC(rst_niC),
            .testmode_i(test_enable_i),
            .flush_i(1'b0),
            .usage_o(),
            .data_i(data_i[in][in_p]),
            .valid_i(valid_i[in][v]),
            .ready_o(ready_o[in][v]),
            .data_o(in_data[in][v]),
            .valid_o(in_valid[in][v]),
            .ready_i(in_ready[in][v]),
            .tmrError(i_stream_fifotmrError)
          );

        floo_route_selectTMR #(.NumRoutes(NumOutput), .flit_t(flit_t), .RouteAlgo(RouteAlgo), .IdWidth(IdWidth), .id_t(id_t), .NumAddrRules(NumAddrRules), .addr_rule_t(addr_rule_t), .EnMultiCast(EnMultiCast)) i_route_select (
            .clk_iA(clk_iA),
            .clk_iB(clk_iB),
            .clk_iC(clk_iC),
            .rst_niA(rst_niA),
            .rst_niB(rst_niB),
            .rst_niC(rst_niC),
            .test_enable_i(test_enable_i),
            .xy_id_i(xy_id_i),
            .id_route_map_i(id_route_map_i),
            .channel_i(in_data[in][v]),
            .valid_i(in_valid[in][v]),
            .ready_i(in_ready[in][v]),
            .channel_o(in_routed_data[in][v]),
            .route_sel_o(route_mask[in][v]),
            .route_sel_id_o(),
            .tmrError(i_route_selecttmrError)
          );
      end
  end
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_valid;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_ready;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] masked_valid_transposed;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] masked_ready_transposed;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_d;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_qA;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_qB;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] past_handshakes_qC;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] current_handshakes;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] all_handshakes;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] ignore_routes;
logic [NumInput - 1:0] [NumVirtChannels - 1:0] [NumOutput - 1:0] expected_handshakes;
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] [NumInput - 1:0] masked_data;
for(genvar in = 0; in<NumInput; in++)
  begin : gen_hs_input
    for(genvar v = 0; v<NumVirtChannels; v++)
          begin : gen_hs_virt
        for(genvar out = 0; out<NumOutput; out++)
                  begin : gen_hs_output
            if ((NoLoopback&&(in==out))||((RouteAlgo==XYRouting)&&XYRouteOpt&&(in==South||in==North)&&(out==East||out==West)))
                          begin : gen_no_conn
                assign masked_ready_transposed[in][v][out] = '0;
                assign masked_valid[out][v][in] = '0;
                assign masked_data[out][v][in] = '0;
              end

            else
                          begin : gen_conn
                assign masked_ready_transposed[in][v][out] = masked_ready[out][v][in];
                assign masked_valid[out][v][in] = in_valid[in][v]&route_mask[in][v][out]& (! EnMultiCast || ~ past_handshakes_q[in][v][out] ) ;
                assign masked_data[out][v][in] = in_routed_data[in][v];
              end
            assign masked_valid_transposed[in][v][out] = masked_valid[out][v][in];
          end
        if (!EnMultiCast)
                  begin : gen_unicast
            assign in_ready[in][v] = | (masked_ready_transposed[in][v]&route_mask[in][v]) ;
          end

        else
                  begin : gen_multicast
            assign current_handshakes[in][v] = masked_valid_transposed[in][v]&masked_ready_transposed[in][v];
            assign past_handshakes_d[in][v] = (in_ready[in][v]&in_valid[in][v]) ? '0 : (past_handshakes_q[in][v]|current_handshakes[in][v]);
            assign all_handshakes[in][v] = past_handshakes_q[in][v]|current_handshakes[in][v];
            assign ignore_routes[in][v] = NoLoopback ? (1<<in) : '0;
            assign expected_handshakes[in][v] = route_mask[in][v]&~ignore_routes[in][v];
            assign in_ready[in][v] = & (all_handshakes[in][v]|~expected_handshakes[in][v]) ;
          end
      end
  end

always_ff @( posedge clk_iA or negedge rst_niA )
  begin : ps_past_handshakes_qA
    if (!rst_niA)
      past_handshakes_qA <= '0;
    else
      past_handshakes_qA <= past_handshakes_dA;
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin : ps_past_handshakes_qB
    if (!rst_niB)
      past_handshakes_qB <= '0;
    else
      past_handshakes_qB <= past_handshakes_dB;
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin : ps_past_handshakes_qC
    if (!rst_niC)
      past_handshakes_qC <= '0;
    else
      past_handshakes_qC <= past_handshakes_dC;
  end
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] out_data;
flit_t [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_data;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_valid;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_ready;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_valid;
logic [NumOutput - 1:0] [NumVirtChannels - 1:0] out_buffered_ready;
for(genvar out = 0; out<NumOutput; out++)
  begin : gen_output
    for(genvar v = 0; v<NumVirtChannels; v++)
          begin : gen_virt_output
        if (!EnReduction)
                  begin : gen_wh_arb

            floo_wormhole_arbiterTMR #(.NumRoutes(NumInput), .flit_t(flit_t)) i_wormhole_arbiter (
                .clk_iA(clk_iA),
                .clk_iB(clk_iB),
                .clk_iC(clk_iC),
                .rst_niA(rst_niA),
                .rst_niB(rst_niB),
                .rst_niC(rst_niC),
                .valid_i(masked_valid[out][v]),
                .ready_o(masked_ready[out][v]),
                .data_i(masked_data[out][v]),
                .valid_o(out_valid[out][v]),
                .ready_i(out_ready[out][v]),
                .data_o(out_data[out][v]),
                .tmrError(i_wormhole_arbitertmrError)
              );
          end

        else
                  begin : gen_red_arb

            floo_output_arbiterTMR #(.NumRoutes(NumInput), .flit_t(flit_t), .payload_t(payload_t), .NarrowRspMask(NarrowRspMask), .WideRspMask(WideRspMask), .id_t(id_t)) i_output_arbiter (
                .clk_iA(clk_iA),
                .clk_iB(clk_iB),
                .clk_iC(clk_iC),
                .rst_niA(rst_niA),
                .rst_niB(rst_niB),
                .rst_niC(rst_niC),
                .valid_i(masked_valid[out][v]),
                .ready_o(masked_ready[out][v]),
                .data_i(masked_data[out][v]),
                .xy_id_i(xy_id_i),
                .valid_o(out_valid[out][v]),
                .ready_i(out_ready[out][v]),
                .data_o(out_data[out][v]),
                .tmrError(i_output_arbitertmrError)
              );
          end
        if (OutFifoDepth>0)
                  begin : gen_out_fifo

            (* ungroup *) stream_fifo_optimal_wrapTMR #(.Depth(OutFifoDepth), .type_t(flit_t)) i_stream_fifo (
                .clk_iA(clk_iA),
                .clk_iB(clk_iB),
                .clk_iC(clk_iC),
                .rst_niA(rst_niA),
                .rst_niB(rst_niB),
                .rst_niC(rst_niC),
                .testmode_i(test_enable_i),
                .flush_i(1'b0),
                .usage_o(),
                .data_i(out_data[out][v]),
                .valid_i(out_valid[out][v]),
                .ready_o(out_ready[out][v]),
                .data_o(out_buffered_data[out][v]),
                .valid_o(out_buffered_valid[out][v]),
                .ready_i(out_buffered_ready[out][v]),
                .tmrError(i_stream_fifotmrError)
              );
          end

        else
                  begin : gen_no_out_fifo
            assign out_buffered_data[out][v] = out_data[out][v];
            assign out_buffered_valid[out][v] = out_valid[out][v];
            assign out_ready[out][v] = out_buffered_ready[out][v];
          end
      end

    floo_vc_arbiterTMR #(.NumVirtChannels(NumVirtChannels), .flit_t(flit_t), .NumPhysChannels(NumPhysChannels)) i_vc_arbiter (
        .clk_iA(clk_iA),
        .clk_iB(clk_iB),
        .clk_iC(clk_iC),
        .rst_niA(rst_niA),
        .rst_niB(rst_niB),
        .rst_niC(rst_niC),
        .valid_i(out_buffered_valid[out]),
        .ready_o(out_buffered_ready[out]),
        .data_i(out_buffered_data[out]),
        .ready_i(ready_i[out]),
        .valid_o(valid_o[out]),
        .data_o(data_o[out]),
        .tmrError(i_vc_arbitertmrError)
      );
  end

majorityVoter #(.WIDTH( ((((NumInput-1)>0) ? (NumInput-1) : - ( NumInput-1 ) )+1)  *  ((((NumVirtChannels-1)>0) ? (NumVirtChannels-1) : - ( NumVirtChannels-1 ) )+1)  *  ((((NumOutput-1)>0) ? (NumOutput-1) : - ( NumOutput-1 ) )+1) )) past_handshakes_qVoter (
    .inA(past_handshakes_qA),
    .inB(past_handshakes_qB),
    .inC(past_handshakes_qC),
    .out(past_handshakes_q),
    .tmrErr(past_handshakes_qTmrError)
  );
assign tmrError = past_handshakes_qTmrError | i_output_arbitertmrError|i_route_selecttmrError|i_stream_fifotmrError|i_vc_arbitertmrError|i_wormhole_arbitertmrError;

fanout #(.WIDTH( ((((NumInput-1)>0) ? (NumInput-1) : - ( NumInput-1 ) )+1)  *  ((((NumVirtChannels-1)>0) ? (NumVirtChannels-1) : - ( NumVirtChannels-1 ) )+1)  *  ((((NumOutput-1)>0) ? (NumOutput-1) : - ( NumOutput-1 ) )+1) )) past_handshakes_dFanout (
    .in(past_handshakes_d),
    .outA(past_handshakes_dA),
    .outB(past_handshakes_dB),
    .outC(past_handshakes_dC)
  );
endmodule

