/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/floo_reduction_arbiterTMR.sv                                          *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:51                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/floo_reduction_arbiter.sv                                               *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/floo_reduction_arbiter.sv) *
 *           Modification time : 2026-04-29 05:41:16.611025                                         *
 *           File Size         : 3036                                                               *
 *           MD5 hash          : 3b4d83f5a8f976f13f539984df7f662a                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_reduction_arbiterTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 1,
  parameter type         flit_t     = logic,
  parameter type         payload_t  = logic,
  parameter payload_t NarrowRspMask = '0,
  parameter payload_t WideRspMask = '0,
  parameter type         id_t       = logic
) (
  input id_t xy_id_i,
  input logic [NumRoutes - 1:0] valid_i,
  output logic [NumRoutes - 1:0] ready_o,
  input flit_t [NumRoutes - 1:0] data_i,
  output logic valid_o,
  input logic ready_i,
  output flit_t data_o
);
typedef logic [cf_math_pkg::idx_width(NumRoutes) - 1:0] arb_idx_t;
logic [NumRoutes - 1:0] in_route_mask;
arb_idx_t input_sel;

lzc #(.WIDTH(NumRoutes)) i_lzc (
    .in_i(valid_i),
    .cnt_o(input_sel),
    .empty_o()
  );

floo_reduction_syncTMR #(.NumRoutes(NumRoutes), .arb_idx_t(arb_idx_t), .flit_t(flit_t), .id_t(id_t)) i_reduction_sync (
    .sel_i(input_sel),
    .data_i(data_i),
    .valid_i(valid_i),
    .xy_id_i(xy_id_i),
    .valid_o(valid_o),
    .in_route_mask_o(in_route_mask)
  );
payload_t ReduceMask;
assign ReduceMask = data_i[input_sel].hdr.axi_ch==NarrowB ? NarrowRspMask : WideRspMask;
logic [1:0] resp;

always_comb
  begin : gen_reduced_B
    data_o = data_i[input_sel];
    resp = '0;
    for(int i = 0; i<NumRoutes; i++)
    begin
      if (in_route_mask[i])
        begin
                    automatic int j = 0;

          for(int k = 0; k<$bits(ReduceMask); k++)
          begin
            if (ReduceMask[k])
              begin
                resp[j] = data_i[i].payload[k];
                j++;
              end

          end
          if (resp==axi_pkg::RESP_SLVERR)
            begin
              data_o = data_i[i];
              break;
            end

        end

    end
  end
assign ready_o = (ready_i&valid_o) ? valid_i&in_route_mask : '0;
endmodule

