/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/floo_nw_routerTMR.sv                                                  *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:50                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/floo_nw_router.sv                                                       *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/floo_nw_router.sv) *
 *           Modification time : 2026-04-29 14:49:33.061234                                         *
 *           File Size         : 9980                                                               *
 *           MD5 hash          : f7df9fbed379ae1badd3a1a1c1cc8f36                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`include "axi/typedef.svh"
`include "floo_noc/typedef.svh"
`include "common_cells/registers.svh"
module floo_nw_routerTMR #(
  parameter floo_pkg::axi_cfg_t AxiCfgN = '0,
  parameter floo_pkg::axi_cfg_t AxiCfgW = '0,
  parameter floo_pkg::route_algo_e RouteAlgo = floo_pkg::XYRouting,
  parameter int unsigned NumRoutes = 0,
  parameter int unsigned NumInputs = NumRoutes,
  parameter int unsigned NumOutputs = NumRoutes,
  parameter int unsigned InFifoDepth = 0,
  parameter int unsigned OutFifoDepth = 0,
  parameter bit XYRouteOpt = 1'b1,
  parameter bit EnMultiCast = 1'b0,
  parameter int unsigned NumAddrRules = 1,
  parameter type id_t                         = logic,
  parameter type hdr_t                        = logic,
  parameter type addr_rule_t                  = logic,
  parameter type floo_req_t                   = logic,
  parameter type floo_rsp_t                   = logic,
  parameter type floo_wide_t                  = logic
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic test_enable_i,
  input id_t id_i,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_i,
  input floo_req_t [NumInputs - 1:0] floo_req_i,
  input floo_rsp_t [NumOutputs - 1:0] floo_rsp_i,
  output floo_req_t [NumOutputs - 1:0] floo_req_o,
  output floo_rsp_t [NumInputs - 1:0] floo_rsp_o,
  input floo_wide_t [NumRoutes - 1:0] floo_wide_i,
  output floo_wide_t [NumRoutes - 1:0] floo_wide_o,
  output tmrError
);
typedef logic [AxiCfgN.AddrWidth - 1:0] axi_addr_t;
typedef logic [AxiCfgN.InIdWidth - 1:0] axi_narrow_in_id_t;
typedef logic [AxiCfgN.UserWidth - 1:0] axi_narrow_user_t;
typedef logic [AxiCfgN.DataWidth - 1:0] axi_narrow_data_t;
typedef logic [AxiCfgN.DataWidth / 8 - 1:0] axi_narrow_strb_t;
typedef logic [AxiCfgW.InIdWidth - 1:0] axi_wide_in_id_t;
typedef logic [AxiCfgW.UserWidth - 1:0] axi_wide_user_t;
typedef logic [AxiCfgW.DataWidth - 1:0] axi_wide_data_t;
typedef logic [AxiCfgW.DataWidth / 8 - 1:0] axi_wide_strb_t;
  `AXI_TYPEDEF_ALL_CT(axi_narrow, axi_narrow_req_t, axi_narrow_rsp_t, axi_addr_t,
      axi_narrow_in_id_t, axi_narrow_data_t, axi_narrow_strb_t, axi_narrow_user_t)
  `AXI_TYPEDEF_ALL_CT(axi_wide, axi_wide_req_t, axi_wide_rsp_t, axi_addr_t,
      axi_wide_in_id_t, axi_wide_data_t, axi_wide_strb_t, axi_wide_user_t)
  `FLOO_TYPEDEF_NW_CHAN_ALL(axi, req, rsp, wide, axi_narrow, axi_wide, AxiCfgN, AxiCfgW, hdr_t)
localparam axi_narrow_b_chan_t NarrowBMask = '{resp: 2'b11, default: '0};
localparam floo_axi_narrow_b_flit_t NarrowBFlitMask = '{payload: NarrowBMask, hdr: '0, rsvd: '0};
localparam axi_narrow_b_chan_t WideBMask = '{resp: 2'b11, default: '0};
localparam floo_axi_wide_b_flit_t WideBFlitMask = '{payload: WideBMask, hdr: '0, rsvd: '0};
wire i_wide_req_floo_routertmrError;
wire i_rsp_floo_routertmrError;
wire i_req_floo_routertmrError;
floo_req_chan_t [NumInputs - 1:0] req_in;
floo_rsp_chan_t [NumInputs - 1:0] rsp_out;
floo_req_chan_t [NumOutputs - 1:0] req_out;
floo_rsp_chan_t [NumOutputs - 1:0] rsp_in;
floo_wide_chan_t [NumRoutes - 1:0] wide_in;
floo_wide_chan_t [NumRoutes - 1:0] wide_out;
logic [NumInputs - 1:0] req_valid_in;
logic [NumInputs - 1:0] req_ready_out;
logic [NumInputs - 1:0] rsp_valid_out;
logic [NumInputs - 1:0] rsp_ready_in;
logic [NumOutputs - 1:0] req_valid_out;
logic [NumOutputs - 1:0] req_ready_in;
logic [NumOutputs - 1:0] rsp_valid_in;
logic [NumOutputs - 1:0] rsp_ready_out;
logic [NumRoutes - 1:0] wide_valid_in;
logic [NumRoutes - 1:0] wide_valid_out;
logic [NumRoutes - 1:0] wide_ready_in;
logic [NumRoutes - 1:0] wide_ready_out;
for(genvar i = 0; i<NumInputs; i++)
  begin : gen_chimney_req
    assign req_valid_in[i] = floo_req_i[i].valid;
    assign floo_req_o[i].ready = req_ready_out[i];
    assign req_in[i] = floo_req_i[i].req;
    assign floo_rsp_o[i].valid = rsp_valid_out[i];
    assign rsp_ready_in[i] = floo_rsp_i[i].ready;
    assign floo_rsp_o[i].rsp = rsp_out[i];
  end
for(genvar i = 0; i<NumOutputs; i++)
  begin : gen_chimney_rsp
    assign floo_req_o[i].valid = req_valid_out[i];
    assign req_ready_in[i] = floo_req_i[i].ready;
    assign floo_req_o[i].req = req_out[i];
    assign rsp_valid_in[i] = floo_rsp_i[i].valid;
    assign floo_rsp_o[i].ready = rsp_ready_out[i];
    assign rsp_in[i] = floo_rsp_i[i].rsp;
  end
for(genvar i = 0; i<NumRoutes; i++)
  begin : gen_chimney_wide
    assign wide_valid_in[i] = floo_wide_i[i].valid;
    assign floo_wide_o[i].ready = wide_ready_out[i];
    assign wide_in[i] = floo_wide_i[i].wide;
    assign floo_wide_o[i].valid = wide_valid_out[i];
    assign wide_ready_in[i] = floo_wide_i[i].ready;
    assign floo_wide_o[i].wide = wide_out[i];
  end

floo_routerTMR #(.NumInput(NumInputs), .NumOutput(NumOutputs), .NumPhysChannels(1), .NumVirtChannels(1), .InFifoDepth(InFifoDepth), .OutFifoDepth(OutFifoDepth), .RouteAlgo(RouteAlgo), .XYRouteOpt(XYRouteOpt), .NumAddrRules(NumAddrRules), .NoLoopback(1'b1), .EnMultiCast(EnMultiCast), .EnReduction(1'b0), .id_t(id_t), .addr_rule_t(addr_rule_t), .flit_t(floo_req_generic_flit_t)) i_req_floo_router (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .test_enable_i(test_enable_i),
    .xy_id_i(id_i),
    .id_route_map_i(id_route_map_i),
    .valid_i(req_valid_in),
    .ready_o(req_ready_out),
    .data_i(req_in),
    .valid_o(req_valid_out),
    .ready_i(req_ready_in),
    .data_o(req_out),
    .tmrError(i_req_floo_routertmrError)
  );

floo_routerTMR #(.NumInput(NumInputs), .NumOutput(NumOutputs), .NumPhysChannels(1), .NumVirtChannels(1), .InFifoDepth(InFifoDepth), .OutFifoDepth(OutFifoDepth), .RouteAlgo(RouteAlgo), .XYRouteOpt(XYRouteOpt), .NumAddrRules(NumAddrRules), .NoLoopback(1'b1), .EnMultiCast(1'b0), .EnReduction(EnMultiCast), .id_t(id_t), .addr_rule_t(addr_rule_t), .flit_t(floo_rsp_generic_flit_t), .payload_t(floo_rsp_payload_t), .NarrowRspMask(floo_rsp_generic_flit_t' (NarrowBFlitMask.payload) ), .WideRspMask(floo_rsp_generic_flit_t' (WideBFlitMask.payload) )) i_rsp_floo_router (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .test_enable_i(test_enable_i),
    .xy_id_i(id_i),
    .id_route_map_i(id_route_map_i),
    .valid_i(rsp_valid_in),
    .ready_o(rsp_ready_out),
    .data_i(rsp_in),
    .valid_o(rsp_valid_out),
    .ready_i(rsp_ready_in),
    .data_o(rsp_out),
    .tmrError(i_rsp_floo_routertmrError)
  );

floo_routerTMR #(.NumRoutes(NumRoutes), .NumPhysChannels(1), .NumVirtChannels(1), .InFifoDepth(InFifoDepth), .OutFifoDepth(OutFifoDepth), .RouteAlgo(RouteAlgo), .XYRouteOpt(XYRouteOpt), .NumAddrRules(NumAddrRules), .NoLoopback(1'b1), .EnMultiCast(EnMultiCast), .EnReduction(1'b0), .id_t(id_t), .addr_rule_t(addr_rule_t), .flit_t(floo_wide_generic_flit_t)) i_wide_req_floo_router (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .test_enable_i(test_enable_i),
    .xy_id_i(id_i),
    .id_route_map_i(id_route_map_i),
    .valid_i(wide_valid_in),
    .ready_o(wide_ready_out),
    .data_i(wide_in),
    .valid_o(wide_valid_out),
    .ready_i(wide_ready_in),
    .data_o(wide_out),
    .tmrError(i_wide_req_floo_routertmrError)
  );
assign tmrError = i_req_floo_routertmrError|i_rsp_floo_routertmrError|i_wide_req_floo_routertmrError;
endmodule


module majorityVoter #(
  parameter WIDTH = 1
)(
  input wire  [WIDTH-1:0] inA,
  input wire  [WIDTH-1:0] inB,
  input wire  [WIDTH-1:0] inC,
  output wire [WIDTH-1:0] out,
  output wire             tmrErr
);
  assign out    = (inA&inB) | (inA&inC) | (inB&inC);
  assign tmrErr = (inA !== inB) || (inB !== inC);
endmodule


// /scratch/chenwu/tmrg/tmrg/../common/fanout.v
module fanout #(
  parameter WIDTH = 1
)(
  input wire  [WIDTH-1:0] in,
  output wire [WIDTH-1:0] outA,
  output wire [WIDTH-1:0] outB,
  output wire [WIDTH-1:0] outC
);
  assign outA = in;
  assign outB = in;
  assign outC = in;
endmodule
