/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/floo_output_arbiterTMR.sv                                             *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:51                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/floo_output_arbiter.sv                                                  *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/floo_output_arbiter.sv) *
 *           Modification time : 2026-04-29 14:49:47.088361                                         *
 *           File Size         : 3292                                                               *
 *           MD5 hash          : 3067dcf62a1150fc65006d105ef8137b                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module floo_output_arbiterTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 1,
  parameter type         flit_t     = logic,
  parameter type         payload_t  = logic,
  parameter payload_t NarrowRspMask = '0,
  parameter payload_t WideRspMask = '0,
  parameter type         id_t       = logic
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input id_t xy_id_i,
  input logic [NumRoutes - 1:0] valid_i,
  output logic [NumRoutes - 1:0] ready_o,
  input flit_t [NumRoutes - 1:0] data_i,
  output logic valid_o,
  input logic ready_i,
  output flit_t data_o,
  output tmrError
);
wire i_wormhole_arbitertmrError;
wire i_stream_arbitertmrError;
flit_t reduce_data_out;
flit_t unicast_data_out;
logic [NumRoutes - 1:0] reduce_valid_in;
logic [NumRoutes - 1:0] unicast_valid_in;
logic [NumRoutes - 1:0] reduce_ready_out;
logic [NumRoutes - 1:0] unicast_ready_out;
logic reduce_valid_out;
logic unicast_valid_out;
logic reduce_ready_in;
logic unicast_ready_in;
logic [NumRoutes - 1:0] reduce_mask;
for(genvar i = 0; i<NumRoutes; i++)
  begin : gen_reduce_mask
    assign reduce_mask[i] =  (data_i[i].hdr.commtype==ParallelReduction) ;
  end
assign unicast_valid_in = valid_i&~reduce_mask;

floo_wormhole_arbiterTMR #(.NumRoutes(NumRoutes), .flit_t(flit_t)) i_wormhole_arbiter (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .data_i(data_i),
    .valid_i(unicast_valid_in),
    .ready_o(unicast_ready_out),
    .valid_o(unicast_valid_out),
    .ready_i(unicast_ready_in),
    .data_o(unicast_data_out),
    .tmrError(i_wormhole_arbitertmrError)
  );
assign reduce_valid_in = valid_i&reduce_mask;

floo_reduction_arbiterTMR #(.NumRoutes(NumRoutes), .flit_t(flit_t), .payload_t(payload_t), .id_t(id_t), .NarrowRspMask(NarrowRspMask), .WideRspMask(WideRspMask)) i_reduction_arbiter (
    .xy_id_i(xy_id_i),
    .data_i(data_i),
    .valid_i(reduce_valid_in),
    .ready_o(reduce_ready_out),
    .valid_o(reduce_valid_out),
    .ready_i(reduce_ready_in),
    .data_o(reduce_data_out)
  );

stream_arbiterTMR #(.N_INP(2), .ARBITER("prio"), .DATA_T(flit_t)) i_stream_arbiter (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .inp_data_i({unicast_data_out, reduce_data_out}),
    .inp_valid_i({unicast_valid_out, reduce_valid_out}),
    .inp_ready_o({unicast_ready_in, reduce_ready_in}),
    .oup_data_o(data_o),
    .oup_valid_o(valid_o),
    .oup_ready_i(ready_i),
    .tmrError(i_stream_arbitertmrError)
  );
assign ready_o = (reduce_valid_out) ? reduce_ready_out : unicast_ready_out;
assign tmrError = i_stream_arbitertmrError|i_wormhole_arbitertmrError;
endmodule

