/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/rr_arb_treeTMR.sv                                                     *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:51                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/rr_arb_tree.sv                                                          *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/rr_arb_tree.sv) *
 *           Modification time : 2026-04-29 14:49:43.389327                                         *
 *           File Size         : 13257                                                              *
 *           MD5 hash          : 4c12172bf8e817f1517cf569f4b6728e                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module rr_arb_treeTMR #(
  parameter int unsigned NumIn = 64,
  parameter int unsigned DataWidth = 32,
  parameter type         DataType   = logic [DataWidth-1:0],
  parameter bit ExtPrio = 1'b0,
  parameter bit AxiVldRdy = 1'b0,
  parameter bit LockIn = 1'b0,
  parameter bit FairArb = 1'b1,
  parameter int unsigned IdxWidth = (NumIn>32'd1) ? unsigned ' ( $clog2(NumIn) )  : 32'd1,
  parameter type         idx_t      = logic [IdxWidth-1:0]
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic flush_i,
  input idx_t rr_i,
  input logic [NumIn - 1:0] req_i,
  output logic [NumIn - 1:0] gnt_o,
  input DataType [NumIn - 1:0] data_i,
  output logic req_o,
  input logic gnt_i,
  output DataType data_o,
  output idx_t idx_o,
  output tmrError
);
wire idx_t rr_iC;
wire idx_t rr_iB;
wire idx_t rr_iA;
wire idx_t rr_dC;
wire idx_t rr_dB;
wire idx_t rr_dA;
wire [ (NumIn-1) :0] req_dC;
wire [ (NumIn-1) :0] req_dB;
wire [ (NumIn-1) :0] req_dA;
wire lock_dC;
wire lock_dB;
wire lock_dA;
wire flush_iC;
wire flush_iB;
wire flush_iA;
wire rr_qTmrError;
wire req_qTmrError;
wire lock_qTmrError;
wire idx_t rr_q;
wire [ (NumIn-1) :0] req_q;
wire lock_q;
if (NumIn==unsigned'(1))
  begin : gen_pass_through
    assign req_o = req_i[0];
    assign gnt_o[0] = gnt_i;
    assign data_o = data_i[0];
    assign idx_o = '0;
    assign lock_qTmrError = 1'b0;
    assign req_qTmrError = 1'b0;
    assign rr_qTmrError = 1'b0;
  end

else
  begin : gen_arbiter
localparam int unsigned NumLevels = unsigned' ($clog2(NumIn)) ;
idx_t [2**NumLevels - 2:0] index_nodes;
DataType [2**NumLevels - 2:0] data_nodes;
logic [2**NumLevels - 2:0] gnt_nodes;
logic [2**NumLevels - 2:0] req_nodes;
idx_t rr_qA;
idx_t rr_qB;
idx_t rr_qC;
logic [NumIn - 1:0] req_d;
    assign req_o = req_nodes[0];
    assign data_o = data_nodes[0];
    assign idx_o = index_nodes[0];
    if (ExtPrio)
          begin : gen_ext_rr
        assign rr_q = rr_i;
        assign req_d = req_i;
        assign rr_qTmrError = 1'b0;
        assign req_qTmrError = 1'b0;
        assign lock_qTmrError = 1'b0;
        fanout #(.WIDTH( ($bits(rr_q)) )) rr_iFanout (
            .in(rr_i),
            .outA(rr_iA),
            .outB(rr_iB),
            .outC(rr_iC)
          );
      end

    else
          begin : gen_int_rr
idx_t rr_d;
        if (LockIn)
                  begin : gen_lock
logic lock_d;
logic lock_qA;
logic lock_qB;
logic lock_qC;
logic [NumIn - 1:0] req_qA;
logic [NumIn - 1:0] req_qB;
logic [NumIn - 1:0] req_qC;
            assign lock_d = req_o&~gnt_i;
            assign req_d = (lock_q) ? req_q : req_i;

            always_ff @( posedge clk_iA or negedge rst_niA )
              begin : p_lock_regA
                if (!rst_niA)
                  begin
                    lock_qA <= '0;
                  end
                else
                  begin
                    if (flush_iA)
                      begin
                        lock_qA <= '0;
                      end
                    else
                      begin
                        lock_qA <= lock_dA;
                      end
                  end
              end

            always_ff @( posedge clk_iB or negedge rst_niB )
              begin : p_lock_regB
                if (!rst_niB)
                  begin
                    lock_qB <= '0;
                  end
                else
                  begin
                    if (flush_iB)
                      begin
                        lock_qB <= '0;
                      end
                    else
                      begin
                        lock_qB <= lock_dB;
                      end
                  end
              end

            always_ff @( posedge clk_iC or negedge rst_niC )
              begin : p_lock_regC
                if (!rst_niC)
                  begin
                    lock_qC <= '0;
                  end
                else
                  begin
                    if (flush_iC)
                      begin
                        lock_qC <= '0;
                      end
                    else
                      begin
                        lock_qC <= lock_dC;
                      end
                  end
              end

            always_ff @( posedge clk_iA or negedge rst_niA )
              begin : p_req_regsA
                if (!rst_niA)
                  begin
                    req_qA <= '0;
                  end
                else
                  begin
                    if (flush_iA)
                      begin
                        req_qA <= '0;
                      end
                    else
                      begin
                        req_qA <= req_dA;
                      end
                  end
              end

            always_ff @( posedge clk_iB or negedge rst_niB )
              begin : p_req_regsB
                if (!rst_niB)
                  begin
                    req_qB <= '0;
                  end
                else
                  begin
                    if (flush_iB)
                      begin
                        req_qB <= '0;
                      end
                    else
                      begin
                        req_qB <= req_dB;
                      end
                  end
              end

            always_ff @( posedge clk_iC or negedge rst_niC )
              begin : p_req_regsC
                if (!rst_niC)
                  begin
                    req_qC <= '0;
                  end
                else
                  begin
                    if (flush_iC)
                      begin
                        req_qC <= '0;
                      end
                    else
                      begin
                        req_qC <= req_dC;
                      end
                  end
              end

            majorityVoter lock_qVoter (
                .inA(lock_qA),
                .inB(lock_qB),
                .inC(lock_qC),
                .out(lock_q),
                .tmrErr(lock_qTmrError)
              );

            majorityVoter #(.WIDTH( ((((NumIn-1)>0) ? (NumIn-1) : - ( NumIn-1 ) )+1) )) req_qVoter (
                .inA(req_qA),
                .inB(req_qB),
                .inC(req_qC),
                .out(req_q),
                .tmrErr(req_qTmrError)
              );

            fanout lock_dFanout (
                .in(lock_d),
                .outA(lock_dA),
                .outB(lock_dB),
                .outC(lock_dC)
              );
            fanout #(.WIDTH( ((((NumIn-1)>0) ? (NumIn-1) : - ( NumIn-1 ) )+1) )) req_dFanout (
                .in(req_d),
                .outA(req_dA),
                .outB(req_dB),
                .outC(req_dC)
              );
          end

        else
                  begin : gen_no_lock
            assign req_d = req_i;
            assign lock_qTmrError = 1'b0;
            assign req_qTmrError = 1'b0;
          end
        if (FairArb)
                  begin : gen_fair_arb
logic [NumIn - 1:0] upper_mask;
logic [NumIn - 1:0] lower_mask;
idx_t upper_idx;
idx_t lower_idx;
idx_t next_idx;
logic upper_empty;
logic lower_empty;
            for(genvar i = 0; i<NumIn; i++)
                          begin : gen_mask
                assign upper_mask[i] = (i>rr_q) ? req_d[i] : 1'b0;
                assign lower_mask[i] = (i<=rr_q) ? req_d[i] : 1'b0;
              end

            lzc #(.WIDTH(NumIn), .MODE(1'b0)) i_lzc_upper (
                .in_i(upper_mask),
                .cnt_o(upper_idx),
                .empty_o(upper_empty)
              );

            lzc #(.WIDTH(NumIn), .MODE(1'b0)) i_lzc_lower (
                .in_i(lower_mask),
                .cnt_o(lower_idx),
                .empty_o()
              );
            assign next_idx = upper_empty ? lower_idx : upper_idx;
            assign rr_d = (gnt_i&&req_o) ? next_idx : rr_q;
          end

        else
                  begin : gen_unfair_arb
            assign rr_d = (gnt_i&&req_o) ? ((rr_q==idx_t'(NumIn-1)) ? '0 : rr_q+1'b1) : rr_q;
          end

        always_ff @( posedge clk_iA or negedge rst_niA )
          begin : p_rr_regsA
            if (!rst_niA)
              begin
                rr_qA <= '0;
              end
            else
              begin
                if (flush_iA)
                  begin
                    rr_qA <= '0;
                  end
                else
                  begin
                    rr_qA <= rr_dA;
                  end
              end
          end

        always_ff @( posedge clk_iB or negedge rst_niB )
          begin : p_rr_regsB
            if (!rst_niB)
              begin
                rr_qB <= '0;
              end
            else
              begin
                if (flush_iB)
                  begin
                    rr_qB <= '0;
                  end
                else
                  begin
                    rr_qB <= rr_dB;
                  end
              end
          end

        always_ff @( posedge clk_iC or negedge rst_niC )
          begin : p_rr_regsC
            if (!rst_niC)
              begin
                rr_qC <= '0;
              end
            else
              begin
                if (flush_iC)
                  begin
                    rr_qC <= '0;
                  end
                else
                  begin
                    rr_qC <= rr_dC;
                  end
              end
          end

        majorityVoter #(.WIDTH( ($bits(rr_q)) )) rr_qVoter (
          .inA(rr_qA),
          .inB(rr_qB),
          .inC(rr_qC),
          .out(rr_q),
          .tmrErr(rr_qTmrError)
        );

        fanout #(.WIDTH( ($bits(rr_q)) )) rr_dFanout (
          .in(rr_d),
          .outA(rr_dA),
          .outB(rr_dB),
          .outC(rr_dC)
        );

        fanout flush_iFanout (
          .in(flush_i),
          .outA(flush_iA),
          .outB(flush_iB),
          .outC(flush_iC)
        );
      end
    assign gnt_nodes[0] = gnt_i;
    for(genvar level = 0; unsigned' (level) <NumLevels; level++)
          begin : gen_levels
        for(genvar l = 0; l<2**level; l++)
                  begin : gen_level
logic sel;
localparam int unsigned Idx0 = 2**level - 1 + l;
localparam int unsigned Idx1 = 2** (level+1)  - 1 + l * 2;
            if (unsigned'(level)==NumLevels-1)
                          begin : gen_first_level
                if (unsigned'(l)*2<NumIn-1)
                                  begin : gen_reduce
                    assign req_nodes[Idx0] = req_d[l*2]|req_d[l*2+1];
                    assign sel = ~req_d[l*2]|req_d[l*2+1]&rr_q[NumLevels-1-level];
                    assign index_nodes[Idx0] = idx_t' (sel) ;
                    assign data_nodes[Idx0] = (sel) ? data_i[l*2+1] : data_i[l*2];
                    assign gnt_o[l*2] = gnt_nodes[Idx0]& (AxiVldRdy|req_d[l*2]) &~sel;
                    assign gnt_o[l*2+1] = gnt_nodes[Idx0]& (AxiVldRdy|req_d[l*2+1]) &sel;
                  end
                if (unsigned'(l)*2==NumIn-1)
                                  begin : gen_first
                    assign req_nodes[Idx0] = req_d[l*2];
                    assign index_nodes[Idx0] = '0;
                    assign data_nodes[Idx0] = data_i[l*2];
                    assign gnt_o[l*2] = gnt_nodes[Idx0]& (AxiVldRdy|req_d[l*2]) ;
                  end
                if (unsigned'(l)*2>NumIn-1)
                                  begin : gen_out_of_range
                    assign req_nodes[Idx0] = 1'b0;
                    assign index_nodes[Idx0] = idx_t' ('0) ;
                    assign data_nodes[Idx0] = DataType' ('0) ;
                  end
              end

            else
                          begin : gen_other_levels
                assign req_nodes[Idx0] = req_nodes[Idx1]|req_nodes[Idx1+1];
                assign sel = ~req_nodes[Idx1]|req_nodes[Idx1+1]&rr_q[NumLevels-1-level];
                assign index_nodes[Idx0] = (sel) ? idx_t ' ( {1'b1, index_nodes[Idx1+1][NumLevels - unsigned' (level)  - 2:0]} )  : idx_t ' ( {1'b0, index_nodes[Idx1][NumLevels - unsigned' (level)  - 2:0]} ) ;
                assign data_nodes[Idx0] = (sel) ? data_nodes[Idx1+1] : data_nodes[Idx1];
                assign gnt_nodes[Idx1] = gnt_nodes[Idx0]&~sel;
                assign gnt_nodes[Idx1+1] = gnt_nodes[Idx0]&sel;
              end
          end
      end

  end
assign tmrError = lock_qTmrError|req_qTmrError|rr_qTmrError;

endmodule : rr_arb_treeTMR

