/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/spill_register_flushableTMR.sv                                        *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:50                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/spill_register_flushable.sv                                             *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/spill_register_flushable.sv) *
 *           Modification time : 2026-05-01 01:52:17.916082                                         *
 *           File Size         : 4767                                                               *
 *           MD5 hash          : a53667c9e00ffd9ba5a47c1dfcf64d74                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module spill_register_flushableTMR #(
  parameter type T      = logic,
  parameter bit Bypass = 1'b0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic valid_i,
  input logic flush_i,
  output logic ready_o,
  input T data_i,
  output logic valid_o,
  input logic ready_i,
  output T data_o,
  output tmrError
);
wire b_full_nC;
wire b_full_nB;
wire b_full_nA;
wire b_full_enC;
wire b_full_enB;
wire b_full_enA;
wire T b_data_nC;
wire T b_data_nB;
wire T b_data_nA;
wire b_data_enC;
wire b_data_enB;
wire b_data_enA;
wire a_full_nC;
wire a_full_nB;
wire a_full_nA;
wire a_full_enC;
wire a_full_enB;
wire a_full_enA;
wire T a_data_nC;
wire T a_data_nB;
wire T a_data_nA;
wire a_data_enC;
wire a_data_enB;
wire a_data_enA;
wor b_full_qTmrError;
wor b_data_qTmrError;
wor a_full_qTmrError;
wor a_data_qTmrError;
wire b_full_q;
wire T b_data_q;
wire a_full_q;
wire T a_data_q;
T a_data_qA;
T a_data_qB;
T a_data_qC;
logic a_full_qA;
logic a_full_qB;
logic a_full_qC;
logic a_fill;
logic a_drain;
T b_data_qA;
T b_data_qB;
T b_data_qC;
logic b_full_qA;
logic b_full_qB;
logic b_full_qC;
logic b_fill;
logic b_drain;
if (Bypass)
  begin : gen_bypass
    assign valid_o = valid_i;
    assign ready_o = ready_i;
    assign data_o = data_i;
  end

else
  begin : gen_spill_reg
    wire a_data_en = a_fill|tmrError;
    wire a_full_en = a_fill|a_drain|tmrError;
    wire b_data_en = b_fill|tmrError;
    wire b_full_en = b_fill|b_drain|tmrError;
T a_data_n;
    assign a_data_n = a_fill ? data_i : a_data_q;
logic a_full_n;
    assign a_full_n = (a_fill||a_drain) ? a_fill : a_full_q;
T b_data_n;
    assign b_data_n = b_fill ? a_data_q : b_data_q;
logic b_full_n;
    assign b_full_n = (b_fill||b_drain) ? b_fill : b_full_q;

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_a_dataA
        if (!rst_niA)
          a_data_qA <= T' ('0) ;
        else
          if (a_data_enA)
            a_data_qA <= a_data_nA;

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_a_dataB
        if (!rst_niB)
          a_data_qB <= T' ('0) ;
        else
          if (a_data_enB)
            a_data_qB <= a_data_nB;

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_a_dataC
        if (!rst_niC)
          a_data_qC <= T' ('0) ;
        else
          if (a_data_enC)
            a_data_qC <= a_data_nC;

      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_a_fullA
        if (!rst_niA)
          a_full_qA <= 0;
        else
          if (a_full_enA)
            a_full_qA <= a_full_nA;

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_a_fullB
        if (!rst_niB)
          a_full_qB <= 0;
        else
          if (a_full_enB)
            a_full_qB <= a_full_nB;

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_a_fullC
        if (!rst_niC)
          a_full_qC <= 0;
        else
          if (a_full_enC)
            a_full_qC <= a_full_nC;

      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_b_dataA
        if (!rst_niA)
          b_data_qA <= T' ('0) ;
        else
          if (b_data_enA)
            b_data_qA <= b_data_nA;

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_b_dataB
        if (!rst_niB)
          b_data_qB <= T' ('0) ;
        else
          if (b_data_enB)
            b_data_qB <= b_data_nB;

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_b_dataC
        if (!rst_niC)
          b_data_qC <= T' ('0) ;
        else
          if (b_data_enC)
            b_data_qC <= b_data_nC;

      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_b_fullA
        if (!rst_niA)
          b_full_qA <= 0;
        else
          if (b_full_enA)
            b_full_qA <= b_full_nA;

      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_b_fullB
        if (!rst_niB)
          b_full_qB <= 0;
        else
          if (b_full_enB)
            b_full_qB <= b_full_nB;

      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_b_fullC
        if (!rst_niC)
          b_full_qC <= 0;
        else
          if (b_full_enC)
            b_full_qC <= b_full_nC;

      end
    assign a_fill = valid_i&&ready_o&& (! flush_i ) ;
    assign a_drain =  (a_full_q&&!b_full_q) ||flush_i;
    assign b_fill = a_drain&& (! ready_i ) && (! flush_i ) ;
    assign b_drain =  (b_full_q&&ready_i) ||flush_i;
    assign ready_o = !a_full_q||!b_full_q;
    assign valid_o = a_full_q|b_full_q;
    assign data_o = b_full_q ? b_data_q : a_data_q;

    fanout a_data_enFanout (
        .in(a_data_en),
        .outA(a_data_enA),
        .outB(a_data_enB),
        .outC(a_data_enC)
      );

    fanout #(.WIDTH( ($bits(a_data_q)) )) a_data_nFanout (
        .in(a_data_n),
        .outA(a_data_nA),
        .outB(a_data_nB),
        .outC(a_data_nC)
      );

    fanout a_full_enFanout (
        .in(a_full_en),
        .outA(a_full_enA),
        .outB(a_full_enB),
        .outC(a_full_enC)
      );

    fanout a_full_nFanout (
        .in(a_full_n),
        .outA(a_full_nA),
        .outB(a_full_nB),
        .outC(a_full_nC)
      );

    fanout b_data_enFanout (
        .in(b_data_en),
        .outA(b_data_enA),
        .outB(b_data_enB),
        .outC(b_data_enC)
      );

    fanout #(.WIDTH( ($bits(a_data_q)) )) b_data_nFanout (
        .in(b_data_n),
        .outA(b_data_nA),
        .outB(b_data_nB),
        .outC(b_data_nC)
      );

    fanout b_full_enFanout (
        .in(b_full_en),
        .outA(b_full_enA),
        .outB(b_full_enB),
        .outC(b_full_enC)
      );

    fanout b_full_nFanout (
        .in(b_full_n),
        .outA(b_full_nA),
        .outB(b_full_nB),
        .outC(b_full_nC)
      );
  end

majorityVoter #(.WIDTH( ($bits(a_data_q)) )) a_data_qVoter (
    .inA(a_data_qA),
    .inB(a_data_qB),
    .inC(a_data_qC),
    .out(a_data_q),
    .tmrErr(a_data_qTmrError)
  );

majorityVoter a_full_qVoter (
    .inA(a_full_qA),
    .inB(a_full_qB),
    .inC(a_full_qC),
    .out(a_full_q),
    .tmrErr(a_full_qTmrError)
  );

majorityVoter #(.WIDTH( ($bits(a_data_q)) )) b_data_qVoter (
    .inA(b_data_qA),
    .inB(b_data_qB),
    .inC(b_data_qC),
    .out(b_data_q),
    .tmrErr(b_data_qTmrError)
  );

majorityVoter b_full_qVoter (
    .inA(b_full_qA),
    .inB(b_full_qB),
    .inC(b_full_qC),
    .out(b_full_q),
    .tmrErr(b_full_qTmrError)
  );
assign tmrError = a_data_qTmrError|a_full_qTmrError|b_data_qTmrError|b_full_qTmrError;
endmodule

