/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/stream_arbiter_flushableTMR.sv                                        *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:51                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/stream_arbiter_flushable.sv                                             *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/stream_arbiter_flushable.sv) *
 *           Modification time : 2026-04-29 14:49:51.364399                                         *
 *           File Size         : 2917                                                               *
 *           MD5 hash          : a112e9e9b559c1aad4afca992e76fdb8                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module stream_arbiter_flushableTMR #(
  parameter type      DATA_T = logic,
  parameter integer N_INP =  - 1,
  parameter ARBITER = "rr"
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic flush_i,
  input DATA_T [N_INP - 1:0] inp_data_i,
  input logic [N_INP - 1:0] inp_valid_i,
  output logic [N_INP - 1:0] inp_ready_o,
  output DATA_T oup_data_o,
  output logic oup_valid_o,
  input logic oup_ready_i,
  output tmrError
);
wire i_arbitertmrError;
if (ARBITER=="rr")
  begin : gen_rr_arb

    rr_arb_treeTMR #(.NumIn(N_INP), .DataType(DATA_T), .ExtPrio(1'b0), .AxiVldRdy(1'b1), .LockIn(1'b1)) i_arbiter (
        .clk_iA(clk_iA),
        .clk_iB(clk_iB),
        .clk_iC(clk_iC),
        .rst_niA(rst_niA),
        .rst_niB(rst_niB),
        .rst_niC(rst_niC),
        .flush_i(flush_i),
        .rr_i('0),
        .req_i(inp_valid_i),
        .gnt_o(inp_ready_o),
        .data_i(inp_data_i),
        .gnt_i(oup_ready_i),
        .req_o(oup_valid_o),
        .data_o(oup_data_o),
        .idx_o(),
        .tmrError(i_arbitertmrError)
      );
  end

else
  if (ARBITER=="prio")
      begin : gen_prio_arb

      rr_arb_treeTMR #(.NumIn(N_INP), .DataType(DATA_T), .ExtPrio(1'b1), .AxiVldRdy(1'b1), .LockIn(1'b0)) i_arbiter (
          .clk_iA(clk_iA),
          .clk_iB(clk_iB),
          .clk_iC(clk_iC),
          .rst_niA(rst_niA),
          .rst_niB(rst_niB),
          .rst_niC(rst_niC),
          .flush_i(flush_i),
          .rr_i('0),
          .req_i(inp_valid_i),
          .gnt_o(inp_ready_o),
          .data_i(inp_data_i),
          .gnt_i(oup_ready_i),
          .req_o(oup_valid_o),
          .data_o(oup_data_o),
          .idx_o(),
          .tmrError(i_arbitertmrError)
        );
    end

  else
      begin : gen_arb_error
    end
assign tmrError = i_arbitertmrError;
endmodule

