/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/stream_arbiterTMR.sv                                                  *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:51                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/stream_arbiter.sv                                                       *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/stream_arbiter.sv) *
 *           Modification time : 2026-04-29 14:49:49.879385                                         *
 *           File Size         : 2115                                                               *
 *           MD5 hash          : 2a5c8ca38ef707bde09e8109009cfda9                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module stream_arbiterTMR #(
  parameter type      DATA_T = logic,
  parameter integer N_INP =  - 1,
  parameter ARBITER = "rr"
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input DATA_T [N_INP - 1:0] inp_data_i,
  input logic [N_INP - 1:0] inp_valid_i,
  output logic [N_INP - 1:0] inp_ready_o,
  output DATA_T oup_data_o,
  output logic oup_valid_o,
  input logic oup_ready_i,
  output tmrError
);
wire i_arbtmrError;

stream_arbiter_flushableTMR #(.DATA_T(DATA_T), .N_INP(N_INP), .ARBITER(ARBITER)) i_arb (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .flush_i(1'b0),
    .inp_data_i(inp_data_i),
    .inp_valid_i(inp_valid_i),
    .inp_ready_o(inp_ready_o),
    .oup_data_o(oup_data_o),
    .oup_valid_o(oup_valid_o),
    .oup_ready_i(oup_ready_i),
    .tmrError(i_arbtmrError)
  );
assign tmrError = i_arbtmrError;
endmodule

