/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : state/tmrg_files/stream_fifo_optimal_wrapTMR.sv                                        *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 01/05/2026 01:55:50                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg state/tmrg_src/floo_nw_router.sv                    *
 *           state/tmrg_src/floo_router.sv state/tmrg_src/stream_fifo_optimal_wrap.sv               *
 *           state/tmrg_src/spill_register_flushable.sv state/tmrg_src/stream_fifo.sv               *
 *           state/tmrg_src/fifo_v3.sv state/tmrg_src/floo_route_select.sv                          *
 *           state/tmrg_src/floo_route_xymask.sv state/tmrg_src/addr_decode.sv                      *
 *           state/tmrg_src/addr_decode_dync.sv state/tmrg_src/floo_wormhole_arbiter.sv             *
 *           state/tmrg_src/rr_arb_tree.sv state/tmrg_src/floo_output_arbiter.sv                    *
 *           state/tmrg_src/floo_reduction_arbiter.sv state/tmrg_src/floo_reduction_sync.sv         *
 *           state/tmrg_src/stream_arbiter.sv state/tmrg_src/stream_arbiter_flushable.sv            *
 *           state/tmrg_src/floo_vc_arbiter.sv state/tmrg_src/lzc.sv --top-module=floo_nw_router --tmr- *
 *           dir=state/tmrg_files                                                                   *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: state/tmrg_src/stream_fifo_optimal_wrap.sv                                             *
 *           Git SHA           : 8c951dd63852ddc11eabf7b11cbcb1318fe89912 (?? state/tmrg_src/stream_fifo_optimal_wrap.sv) *
 *           Modification time : 2026-04-29 14:49:53.814421                                         *
 *           File Size         : 4113                                                               *
 *           MD5 hash          : cc1aa2f6f8a03df162962092b4af0349                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module stream_fifo_optimal_wrapTMR #(
  parameter int unsigned Depth = 32'd8,
  parameter type type_t = logic,
  parameter bit PrintInfo = 1'b0,
  parameter int unsigned AddrDepth = (Depth>32'd1) ? $clog2(Depth) : 32'd1
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic flush_i,
  input logic testmode_i,
  output logic [AddrDepth - 1:0] usage_o,
  input type_t data_i,
  input logic valid_i,
  output logic ready_o,
  output type_t data_o,
  output logic valid_o,
  input logic ready_i,
  output tmrError
);
// TMRG bug: only one of {gen_spill, gen_fifo} is active for any given Depth,
// but both i_*tmrError signals are OR'd into the output. The inactive branch
// leaves its wire undriven (X/Z), poisoning tmrError. wor + ground-tie below
// fixes both branches.
wire i_stream_fifotmrError;
wire i_spill_register_flushabletmrError;
if (Depth==32'd2)
  begin : gen_spill
`ifndef SYNTHESIS
    if (PrintInfo)
          begin : gen_info
initial
  begin
            $display("[%m] Instantiate spill register (of depth %d)", Depth);
          end
      end
`endif

    spill_register_flushableTMR #(.T(type_t), .Bypass(1'b0)) i_spill_register_flushable (
        .clk_iA(clk_iA),
        .clk_iB(clk_iB),
        .clk_iC(clk_iC),
        .rst_niA(rst_niA),
        .rst_niB(rst_niB),
        .rst_niC(rst_niC),
        .flush_i(flush_i),
        .valid_i(valid_i),
        .ready_o(ready_o),
        .data_i(data_i),
        .valid_o(valid_o),
        .ready_i(ready_i),
        .data_o(data_o),
        .tmrError(i_spill_register_flushabletmrError)
      );
    assign usage_o = 'x;
    assign i_stream_fifotmrError = 1'b0;
  end
if (Depth>32'd2)
  begin : gen_fifo
`ifndef SYNTHESIS
    if (PrintInfo)
          begin : gen_info
initial
  begin
            $info("[%m] Instantiate stream FIFO of depth %d", Depth);
          end
      end
`endif

    stream_fifoTMR #(.DEPTH(Depth), .T(type_t)) i_stream_fifo (
        .clk_iA(clk_iA),
        .clk_iB(clk_iB),
        .clk_iC(clk_iC),
        .rst_niA(rst_niA),
        .rst_niB(rst_niB),
        .rst_niC(rst_niC),
        .flush_i(flush_i),
        .testmode_i(testmode_i),
        .usage_o(usage_o),
        .data_i(data_i),
        .valid_i(valid_i),
        .ready_o(ready_o),
        .data_o(data_o),
        .valid_o(valid_o),
        .ready_i(ready_i),
        .tmrError(i_stream_fifotmrError)
      );
    assign i_spill_register_flushabletmrError = 1'b0;
  end
assign tmrError = i_spill_register_flushabletmrError|i_stream_fifotmrError;
endmodule : stream_fifo_optimal_wrapTMR

