/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/addr_decode_dyncTMR.sv                                                      *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 30/12/2025 17:23:19                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/floo_nw_router.sv tmrg_src/floo_router.sv  *
 *           tmrg_src/stream_fifo_optimal_wrap.sv tmrg_src/spill_register_flushable.sv              *
 *           tmrg_src/stream_fifo.sv tmrg_src/fifo_v3.sv tmrg_src/floo_route_select.sv              *
 *           tmrg_src/floo_route_xymask.sv tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv     *
 *           tmrg_src/floo_wormhole_arbiter.sv tmrg_src/rr_arb_tree.sv tmrg_src/floo_output_arbiter.sv *
 *           tmrg_src/floo_reduction_arbiter.sv tmrg_src/floo_reduction_sync.sv                     *
 *           tmrg_src/stream_arbiter.sv tmrg_src/stream_arbiter_flushable.sv                        *
 *           tmrg_src/floo_vc_arbiter.sv tmrg_src/lzc.sv --top-module=floo_nw_router --tmr-         *
 *           dir=tmrg_files                                                                         *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/addr_decode_dync.sv                                                           *
 *           Git SHA           : File not in git repository!                                        *
 *           Modification time : 2025-12-30 15:56:09.818726                                         *
 *           File Size         : 5661                                                               *
 *           MD5 hash          : 2d37fa469918113ab216b324d1a42214                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module addr_decode_dyncTMR #(
  parameter int unsigned NoIndices = 32'd0,
  parameter int unsigned NoRules = 32'd0,
  parameter type addr_t = logic,
  parameter type rule_t = logic,
  parameter bit Napot = 0,
  parameter int unsigned IdxWidth = cf_math_pkg::idx_width(NoIndices),
  parameter type idx_t = logic [IdxWidth-1:0]
) (
  input addr_t addr_iA,
  input addr_t addr_iB,
  input addr_t addr_iC,
  input rule_t [NoRules - 1:0] addr_map_iA,
  input rule_t [NoRules - 1:0] addr_map_iB,
  input rule_t [NoRules - 1:0] addr_map_iC,
  output idx_t idx_oA,
  output idx_t idx_oB,
  output idx_t idx_oC,
  output logic dec_valid_oA,
  output logic dec_valid_oB,
  output logic dec_valid_oC,
  output logic dec_error_oA,
  output logic dec_error_oB,
  output logic dec_error_oC,
  input logic en_default_idx_iA,
  input logic en_default_idx_iB,
  input logic en_default_idx_iC,
  input idx_t default_idx_iA,
  input idx_t default_idx_iB,
  input idx_t default_idx_iC,
  input logic config_ongoing_iA,
  input logic config_ongoing_iB,
  input logic config_ongoing_iC
);
logic [NoRules - 1:0] matched_rulesA;
logic [NoRules - 1:0] matched_rulesB;
logic [NoRules - 1:0] matched_rulesC;

always_comb
  begin
    matched_rulesA = '0;
    dec_valid_oA = 1'b0;
    dec_error_oA = (en_default_idx_iA) ? 1'b0 : 1'b1;
    idx_oA = (en_default_idx_iA) ? default_idx_iA : '0;
    for(int unsigned i = 0; i<NoRules; i++)
    begin
      if (!Napot&&(addr_iA>=addr_map_iA[i].start_addr)&&((addr_iA<addr_map_iA[i].end_addr)||(addr_map_iA[i].end_addr=='0))||Napot&&(addr_map_iA[i].start_addr&addr_map_iA[i].end_addr)==(addr_iA&addr_map_iA[i].end_addr))
        begin
          matched_rulesA[i] = ~config_ongoing_iA;
          dec_valid_oA = ~config_ongoing_iA;
          dec_error_oA = 1'b0;
          idx_oA = config_ongoing_iA ? default_idx_iA : idx_t ' ( addr_map_iA[i].idx ) ;
        end

    end
  end

always_comb
  begin
    matched_rulesB = '0;
    dec_valid_oB = 1'b0;
    dec_error_oB = (en_default_idx_iB) ? 1'b0 : 1'b1;
    idx_oB = (en_default_idx_iB) ? default_idx_iB : '0;
    for(int unsigned i = 0; i<NoRules; i++)
    begin
      if (!Napot&&(addr_iB>=addr_map_iB[i].start_addr)&&((addr_iB<addr_map_iB[i].end_addr)||(addr_map_iB[i].end_addr=='0))||Napot&&(addr_map_iB[i].start_addr&addr_map_iB[i].end_addr)==(addr_iB&addr_map_iB[i].end_addr))
        begin
          matched_rulesB[i] = ~config_ongoing_iB;
          dec_valid_oB = ~config_ongoing_iB;
          dec_error_oB = 1'b0;
          idx_oB = config_ongoing_iB ? default_idx_iB : idx_t ' ( addr_map_iB[i].idx ) ;
        end

    end
  end

always_comb
  begin
    matched_rulesC = '0;
    dec_valid_oC = 1'b0;
    dec_error_oC = (en_default_idx_iC) ? 1'b0 : 1'b1;
    idx_oC = (en_default_idx_iC) ? default_idx_iC : '0;
    for(int unsigned i = 0; i<NoRules; i++)
    begin
      if (!Napot&&(addr_iC>=addr_map_iC[i].start_addr)&&((addr_iC<addr_map_iC[i].end_addr)||(addr_map_iC[i].end_addr=='0))||Napot&&(addr_map_iC[i].start_addr&addr_map_iC[i].end_addr)==(addr_iC&addr_map_iC[i].end_addr))
        begin
          matched_rulesC[i] = ~config_ongoing_iC;
          dec_valid_oC = ~config_ongoing_iC;
          dec_error_oC = 1'b0;
          idx_oC = config_ongoing_iC ? default_idx_iC : idx_t ' ( addr_map_iC[i].idx ) ;
        end

    end
  end
endmodule

