/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/floo_route_selectTMR.sv                                                     *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 30/12/2025 17:23:19                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/floo_nw_router.sv tmrg_src/floo_router.sv  *
 *           tmrg_src/stream_fifo_optimal_wrap.sv tmrg_src/spill_register_flushable.sv              *
 *           tmrg_src/stream_fifo.sv tmrg_src/fifo_v3.sv tmrg_src/floo_route_select.sv              *
 *           tmrg_src/floo_route_xymask.sv tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv     *
 *           tmrg_src/floo_wormhole_arbiter.sv tmrg_src/rr_arb_tree.sv tmrg_src/floo_output_arbiter.sv *
 *           tmrg_src/floo_reduction_arbiter.sv tmrg_src/floo_reduction_sync.sv                     *
 *           tmrg_src/stream_arbiter.sv tmrg_src/stream_arbiter_flushable.sv                        *
 *           tmrg_src/floo_vc_arbiter.sv tmrg_src/lzc.sv --top-module=floo_nw_router --tmr-         *
 *           dir=tmrg_files                                                                         *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/floo_route_select.sv                                                          *
 *           Git SHA           : File not in git repository!                                        *
 *           Modification time : 2025-12-30 16:48:36.836715                                         *
 *           File Size         : 6995                                                               *
 *           MD5 hash          : 2652aa47216a26c9323739d81b903fd6                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`include "common_cells/registers.svh"
module floo_route_selectTMR import floo_pkg::*; #(
  parameter int unsigned NumRoutes = 0,
  parameter route_algo_e RouteAlgo = IdTable,
  parameter bit LockRouting = 1'b1,
  parameter int unsigned IdWidth = 0,
  parameter int unsigned NumAddrRules = 0,
  parameter int unsigned RouteSelWidth = $clog2(NumRoutes),
  parameter bit EnMultiCast = 1'b0,
  parameter type         flit_t           = logic,
  parameter type         addr_rule_t      = logic,
  parameter type         id_t             = logic[IdWidth-1:0]
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic test_enable_iA,
  input logic test_enable_iB,
  input logic test_enable_iC,
  input id_t xy_id_iA,
  input id_t xy_id_iB,
  input id_t xy_id_iC,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_iA,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_iB,
  input addr_rule_t [NumAddrRules - 1:0] id_route_map_iC,
  input flit_t channel_iA,
  input flit_t channel_iB,
  input flit_t channel_iC,
  input logic valid_iA,
  input logic valid_iB,
  input logic valid_iC,
  input logic ready_iA,
  input logic ready_iB,
  input logic ready_iC,
  output flit_t channel_oA,
  output flit_t channel_oB,
  output flit_t channel_oC,
  output logic [NumRoutes - 1:0] route_sel_oA,
  output logic [NumRoutes - 1:0] route_sel_oB,
  output logic [NumRoutes - 1:0] route_sel_oC,
  output logic [RouteSelWidth - 1:0] route_sel_id_oA,
  output logic [RouteSelWidth - 1:0] route_sel_id_oB,
  output logic [RouteSelWidth - 1:0] route_sel_id_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire route_sel_qTmrErrorC;
wire route_sel_id_qTmrErrorC;
wire locked_route_qTmrErrorC;
wire route_sel_qTmrErrorB;
wire route_sel_id_qTmrErrorB;
wire locked_route_qTmrErrorB;
wire route_sel_qTmrErrorA;
wire route_sel_id_qTmrErrorA;
wire locked_route_qTmrErrorA;
logic [NumRoutes - 1:0] route_selA;
logic [NumRoutes - 1:0] route_selB;
logic [NumRoutes - 1:0] route_selC;
logic [RouteSelWidth - 1:0] route_sel_idA;
logic [RouteSelWidth - 1:0] route_sel_idB;
logic [RouteSelWidth - 1:0] route_sel_idC;
if (RouteAlgo==IdTable)
  begin : gen_id_table
logic [RouteSelWidth - 1:0] id_table_resultA;
logic [RouteSelWidth - 1:0] id_table_resultB;
logic [RouteSelWidth - 1:0] id_table_resultC;
    assign channel_oA = channel_iA;
    assign channel_oB = channel_iB;
    assign channel_oC = channel_iC;

    addr_decodeTMR #(.NoIndices(NumRoutes), .NoRules(NumAddrRules), .addr_t(id_t), .rule_t(addr_rule_t), .Napot(0)) i_id_decode (
        .addr_iA(channel_iA.hdr.dst_id),
        .addr_iB(channel_iB.hdr.dst_id),
        .addr_iC(channel_iC.hdr.dst_id),
        .addr_map_iA(id_route_map_iA),
        .addr_map_iB(id_route_map_iB),
        .addr_map_iC(id_route_map_iC),
        .idx_oA(id_table_resultA),
        .idx_oB(id_table_resultB),
        .idx_oC(id_table_resultC),
        .dec_valid_oA(),
        .dec_valid_oB(),
        .dec_valid_oC(),
        .dec_error_oA(),
        .dec_error_oB(),
        .dec_error_oC(),
        .default_idx_iA('0),
        .default_idx_iB('0),
        .default_idx_iC('0),
        .en_default_idx_iA('0),
        .en_default_idx_iB('0),
        .en_default_idx_iC('0)
      );

    always_comb
      begin : proc_route_selA
        route_sel_idA = id_table_resultA;
        route_selA = '0;
        route_selA[id_table_resultA] = 1'b1;
      end

    always_comb
      begin : proc_route_selB
        route_sel_idB = id_table_resultB;
        route_selB = '0;
        route_selB[id_table_resultB] = 1'b1;
      end

    always_comb
      begin : proc_route_selC
        route_sel_idC = id_table_resultC;
        route_selC = '0;
        route_selC[id_table_resultC] = 1'b1;
      end
  end

else
  if (RouteAlgo==SourceRouting)
      begin : gen_consumption

      always_comb
        begin : proc_route_selA
          route_sel_idA = channel_iA.hdr.dst_id[RouteSelWidth - 1:0];
          route_selA = '0;
          route_selA[route_sel_idA] = 1'b1;
          channel_oA = channel_iA;
          channel_oA.hdr.dst_id = channel_iA.hdr.dst_id>>RouteSelWidth;
        end

      always_comb
        begin : proc_route_selB
          route_sel_idB = channel_iB.hdr.dst_id[RouteSelWidth - 1:0];
          route_selB = '0;
          route_selB[route_sel_idB] = 1'b1;
          channel_oB = channel_iB;
          channel_oB.hdr.dst_id = channel_iB.hdr.dst_id>>RouteSelWidth;
        end

      always_comb
        begin : proc_route_selC
          route_sel_idC = channel_iC.hdr.dst_id[RouteSelWidth - 1:0];
          route_selC = '0;
          route_selC[route_sel_idC] = 1'b1;
          channel_oC = channel_iC;
          channel_oC.hdr.dst_id = channel_iC.hdr.dst_id>>RouteSelWidth;
        end
    end

  else
      if (RouteAlgo==XYRouting)
          begin : gen_xy_routing
        if (EnMultiCast)
                  begin : gen_mcast_route_sel

            floo_route_xymaskTMR #(.NumRoutes(NumRoutes), .flit_t(flit_t), .id_t(id_t), .FwdMode(1)) i_route_xymask (
                .channel_iA(channel_iA),
                .channel_iB(channel_iB),
                .channel_iC(channel_iC),
                .xy_id_iA(xy_id_iA),
                .xy_id_iB(xy_id_iB),
                .xy_id_iC(xy_id_iC),
                .route_sel_oA(route_selA),
                .route_sel_oB(route_selB),
                .route_sel_oC(route_selC)
              );
            assign route_sel_idA = '0;
            assign route_sel_idB = '0;
            assign route_sel_idC = '0;
          end

        else
                  begin : gen_route_sel
id_t id_inA;
id_t id_inB;
id_t id_inC;
            assign id_inA = id_t' (channel_iA.hdr.dst_id) ;
            assign id_inB = id_t' (channel_iB.hdr.dst_id) ;
            assign id_inC = id_t' (channel_iC.hdr.dst_id) ;

            always_comb
              begin
                route_sel_idA = East;
                if (id_inA.x==xy_id_iA.x&&id_inA.y==xy_id_iA.y)
                  begin
                    route_sel_idA = Eject + channel_iA.hdr.dst_id.port_id;
                  end
                else
                  if (id_inA.x==xy_id_iA.x)
                    begin
                      if (id_inA.y<xy_id_iA.y)
                        begin
                          route_sel_idA = South;
                        end
                      else
                        begin
                          route_sel_idA = North;
                        end
                    end
                  else
                    begin
                      if (id_inA.x<xy_id_iA.x)
                        begin
                          route_sel_idA = West;
                        end
                      else
                        begin
                          route_sel_idA = East;
                        end
                    end
                route_selA = '0;
                route_selA[route_sel_idA] = 1'b1;
              end

            always_comb
              begin
                route_sel_idB = East;
                if (id_inB.x==xy_id_iB.x&&id_inB.y==xy_id_iB.y)
                  begin
                    route_sel_idB = Eject + channel_iB.hdr.dst_id.port_id;
                  end
                else
                  if (id_inB.x==xy_id_iB.x)
                    begin
                      if (id_inB.y<xy_id_iB.y)
                        begin
                          route_sel_idB = South;
                        end
                      else
                        begin
                          route_sel_idB = North;
                        end
                    end
                  else
                    begin
                      if (id_inB.x<xy_id_iB.x)
                        begin
                          route_sel_idB = West;
                        end
                      else
                        begin
                          route_sel_idB = East;
                        end
                    end
                route_selB = '0;
                route_selB[route_sel_idB] = 1'b1;
              end

            always_comb
              begin
                route_sel_idC = East;
                if (id_inC.x==xy_id_iC.x&&id_inC.y==xy_id_iC.y)
                  begin
                    route_sel_idC = Eject + channel_iC.hdr.dst_id.port_id;
                  end
                else
                  if (id_inC.x==xy_id_iC.x)
                    begin
                      if (id_inC.y<xy_id_iC.y)
                        begin
                          route_sel_idC = South;
                        end
                      else
                        begin
                          route_sel_idC = North;
                        end
                    end
                  else
                    begin
                      if (id_inC.x<xy_id_iC.x)
                        begin
                          route_sel_idC = West;
                        end
                      else
                        begin
                          route_sel_idC = East;
                        end
                    end
                route_selC = '0;
                route_selC[route_sel_idC] = 1'b1;
              end
          end
        assign channel_oA = channel_iA;
        assign channel_oB = channel_iB;
        assign channel_oC = channel_iC;
      end

    else
          begin : gen_err
initial
  begin
            $fatal(1, "Routing algorithm unknown");
          end
      end
if (LockRouting)
  begin : gen_lock
logic locked_route_dA;
logic locked_route_dB;
logic locked_route_dC;
logic locked_route_qA;
logic locked_route_qB;
logic locked_route_qC;
logic locked_route_qVotedA;
logic locked_route_qVotedB;
logic locked_route_qVotedC;

    always_comb
      begin
        locked_route_dA = locked_route_qVotedA;
        if (ready_iA&&valid_iA)
          begin
            locked_route_dA = ~channel_iA.hdr.last;
          end

      end

    always_comb
      begin
        locked_route_dB = locked_route_qVotedB;
        if (ready_iB&&valid_iB)
          begin
            locked_route_dB = ~channel_iB.hdr.last;
          end

      end

    always_comb
      begin
        locked_route_dC = locked_route_qVotedC;
        if (ready_iC&&valid_iC)
          begin
            locked_route_dC = ~channel_iC.hdr.last;
          end

      end
logic [NumRoutes - 1:0] route_sel_qA;
logic [NumRoutes - 1:0] route_sel_qB;
logic [NumRoutes - 1:0] route_sel_qC;
logic [NumRoutes - 1:0] route_sel_qVotedA;
logic [NumRoutes - 1:0] route_sel_qVotedB;
logic [NumRoutes - 1:0] route_sel_qVotedC;
logic [RouteSelWidth - 1:0] route_sel_id_qA;
logic [RouteSelWidth - 1:0] route_sel_id_qB;
logic [RouteSelWidth - 1:0] route_sel_id_qC;
logic [RouteSelWidth - 1:0] route_sel_id_qVotedA;
logic [RouteSelWidth - 1:0] route_sel_id_qVotedB;
logic [RouteSelWidth - 1:0] route_sel_id_qVotedC;
    assign route_sel_oA = locked_route_qVotedA ? route_sel_qVotedA : route_selA;
    assign route_sel_oB = locked_route_qVotedB ? route_sel_qVotedB : route_selB;
    assign route_sel_oC = locked_route_qVotedC ? route_sel_qVotedC : route_selC;
    assign route_sel_id_oA = locked_route_qVotedA ? route_sel_id_qVotedA : route_sel_idA;
    assign route_sel_id_oB = locked_route_qVotedB ? route_sel_id_qVotedB : route_sel_idB;
    assign route_sel_id_oC = locked_route_qVotedC ? route_sel_id_qVotedC : route_sel_idC;

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin
        if (!rst_niA)
          begin
            locked_route_qA <= '0;
          end
        else
          begin
            locked_route_qA <= locked_route_dA;
          end
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin
        if (!rst_niB)
          begin
            locked_route_qB <= '0;
          end
        else
          begin
            locked_route_qB <= locked_route_dB;
          end
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin
        if (!rst_niC)
          begin
            locked_route_qC <= '0;
          end
        else
          begin
            locked_route_qC <= locked_route_dC;
          end
      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin
        if (!rst_niA)
          begin
            route_sel_qA <= '0;
          end
        else
          begin
            if (~locked_route_qVotedA)
              begin
                route_sel_qA <= route_selA;
              end

          end
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin
        if (!rst_niB)
          begin
            route_sel_qB <= '0;
          end
        else
          begin
            if (~locked_route_qVotedB)
              begin
                route_sel_qB <= route_selB;
              end

          end
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin
        if (!rst_niC)
          begin
            route_sel_qC <= '0;
          end
        else
          begin
            if (~locked_route_qVotedC)
              begin
                route_sel_qC <= route_selC;
              end

          end
      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin
        if (!rst_niA)
          begin
            route_sel_id_qA <= '0;
          end
        else
          begin
            if (~locked_route_qVotedA)
              begin
                route_sel_id_qA <= route_sel_idA;
              end

          end
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin
        if (!rst_niB)
          begin
            route_sel_id_qB <= '0;
          end
        else
          begin
            if (~locked_route_qVotedB)
              begin
                route_sel_id_qB <= route_sel_idB;
              end

          end
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin
        if (!rst_niC)
          begin
            route_sel_id_qC <= '0;
          end
        else
          begin
            if (~locked_route_qVotedC)
              begin
                route_sel_id_qC <= route_sel_idC;
              end

          end
      end

    majorityVoter locked_route_qVoterA (
        .inA(locked_route_qA),
        .inB(locked_route_qB),
        .inC(locked_route_qC),
        .out(locked_route_qVotedA),
        .tmrErr(locked_route_qTmrErrorA)
      );

    majorityVoter #(.WIDTH( ((((RouteSelWidth-1)>0) ? (RouteSelWidth-1) : - ( RouteSelWidth-1 ) )+1) )) route_sel_id_qVoterA (
        .inA(route_sel_id_qA),
        .inB(route_sel_id_qB),
        .inC(route_sel_id_qC),
        .out(route_sel_id_qVotedA),
        .tmrErr(route_sel_id_qTmrErrorA)
      );

    majorityVoter #(.WIDTH( ((((NumRoutes-1)>0) ? (NumRoutes-1) : - ( NumRoutes-1 ) )+1) )) route_sel_qVoterA (
        .inA(route_sel_qA),
        .inB(route_sel_qB),
        .inC(route_sel_qC),
        .out(route_sel_qVotedA),
        .tmrErr(route_sel_qTmrErrorA)
      );
    assign tmrErrorA = locked_route_qTmrErrorA|route_sel_id_qTmrErrorA|route_sel_qTmrErrorA;

    majorityVoter locked_route_qVoterB (
        .inA(locked_route_qA),
        .inB(locked_route_qB),
        .inC(locked_route_qC),
        .out(locked_route_qVotedB),
        .tmrErr(locked_route_qTmrErrorB)
      );

    majorityVoter #(.WIDTH( ((((RouteSelWidth-1)>0) ? (RouteSelWidth-1) : - ( RouteSelWidth-1 ) )+1) )) route_sel_id_qVoterB (
        .inA(route_sel_id_qA),
        .inB(route_sel_id_qB),
        .inC(route_sel_id_qC),
        .out(route_sel_id_qVotedB),
        .tmrErr(route_sel_id_qTmrErrorB)
      );

    majorityVoter #(.WIDTH( ((((NumRoutes-1)>0) ? (NumRoutes-1) : - ( NumRoutes-1 ) )+1) )) route_sel_qVoterB (
        .inA(route_sel_qA),
        .inB(route_sel_qB),
        .inC(route_sel_qC),
        .out(route_sel_qVotedB),
        .tmrErr(route_sel_qTmrErrorB)
      );
    assign tmrErrorB = locked_route_qTmrErrorB|route_sel_id_qTmrErrorB|route_sel_qTmrErrorB;

    majorityVoter locked_route_qVoterC (
        .inA(locked_route_qA),
        .inB(locked_route_qB),
        .inC(locked_route_qC),
        .out(locked_route_qVotedC),
        .tmrErr(locked_route_qTmrErrorC)
      );

    majorityVoter #(.WIDTH( ((((RouteSelWidth-1)>0) ? (RouteSelWidth-1) : - ( RouteSelWidth-1 ) )+1) )) route_sel_id_qVoterC (
        .inA(route_sel_id_qA),
        .inB(route_sel_id_qB),
        .inC(route_sel_id_qC),
        .out(route_sel_id_qVotedC),
        .tmrErr(route_sel_id_qTmrErrorC)
      );

    majorityVoter #(.WIDTH( ((((NumRoutes-1)>0) ? (NumRoutes-1) : - ( NumRoutes-1 ) )+1) )) route_sel_qVoterC (
        .inA(route_sel_qA),
        .inB(route_sel_qB),
        .inC(route_sel_qC),
        .out(route_sel_qVotedC),
        .tmrErr(route_sel_qTmrErrorC)
      );
    assign tmrErrorC = locked_route_qTmrErrorC|route_sel_id_qTmrErrorC|route_sel_qTmrErrorC;
  end

else
  begin : gen_no_lock
    assign route_sel_oA = route_selA;
    assign route_sel_oB = route_selB;
    assign route_sel_oC = route_selC;
    assign route_sel_id_oA = route_sel_idA;
    assign route_sel_id_oB = route_sel_idB;
    assign route_sel_id_oC = route_sel_idC;
    assign tmrErrorA = 1'b0;
    assign tmrErrorB = 1'b0;
    assign tmrErrorC = 1'b0;
  end
endmodule

