/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/spill_register_flushableTMR.sv                                              *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 30/12/2025 17:23:18                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/floo_nw_router.sv tmrg_src/floo_router.sv  *
 *           tmrg_src/stream_fifo_optimal_wrap.sv tmrg_src/spill_register_flushable.sv              *
 *           tmrg_src/stream_fifo.sv tmrg_src/fifo_v3.sv tmrg_src/floo_route_select.sv              *
 *           tmrg_src/floo_route_xymask.sv tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv     *
 *           tmrg_src/floo_wormhole_arbiter.sv tmrg_src/rr_arb_tree.sv tmrg_src/floo_output_arbiter.sv *
 *           tmrg_src/floo_reduction_arbiter.sv tmrg_src/floo_reduction_sync.sv                     *
 *           tmrg_src/stream_arbiter.sv tmrg_src/stream_arbiter_flushable.sv                        *
 *           tmrg_src/floo_vc_arbiter.sv tmrg_src/lzc.sv --top-module=floo_nw_router --tmr-         *
 *           dir=tmrg_files                                                                         *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/spill_register_flushable.sv                                                   *
 *           Git SHA           : File not in git repository!                                        *
 *           Modification time : 2025-12-30 15:55:23.820268                                         *
 *           File Size         : 3840                                                               *
 *           MD5 hash          : 94e9b61fd79d00c449706fc60c68b7e5                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module spill_register_flushableTMR #(
  parameter type T      = logic,
  parameter bit Bypass = 1'b0
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic valid_iA,
  input logic valid_iB,
  input logic valid_iC,
  input logic flush_iA,
  input logic flush_iB,
  input logic flush_iC,
  output logic ready_oA,
  output logic ready_oB,
  output logic ready_oC,
  input T data_iA,
  input T data_iB,
  input T data_iC,
  output logic valid_oA,
  output logic valid_oB,
  output logic valid_oC,
  input logic ready_iA,
  input logic ready_iB,
  input logic ready_iC,
  output T data_oA,
  output T data_oB,
  output T data_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire b_full_qTmrErrorC;
wire b_data_qTmrErrorC;
wire a_full_qTmrErrorC;
wire a_data_qTmrErrorC;
wire b_full_qTmrErrorB;
wire b_data_qTmrErrorB;
wire a_full_qTmrErrorB;
wire a_data_qTmrErrorB;
wire b_full_qTmrErrorA;
wire b_data_qTmrErrorA;
wire a_full_qTmrErrorA;
wire a_data_qTmrErrorA;
T a_data_qA;
T a_data_qB;
T a_data_qC;
T a_data_qVotedA;
T a_data_qVotedB;
T a_data_qVotedC;
logic a_full_qA;
logic a_full_qB;
logic a_full_qC;
logic a_full_qVotedA;
logic a_full_qVotedB;
logic a_full_qVotedC;
logic a_fillA;
logic a_fillB;
logic a_fillC;
logic a_drainA;
logic a_drainB;
logic a_drainC;
T b_data_qA;
T b_data_qB;
T b_data_qC;
T b_data_qVotedA;
T b_data_qVotedB;
T b_data_qVotedC;
logic b_full_qA;
logic b_full_qB;
logic b_full_qC;
logic b_full_qVotedA;
logic b_full_qVotedB;
logic b_full_qVotedC;
logic b_fillA;
logic b_fillB;
logic b_fillC;
logic b_drainA;
logic b_drainB;
logic b_drainC;
if (Bypass)
  begin : gen_bypass
    assign valid_oA = valid_iA;
    assign valid_oB = valid_iB;
    assign valid_oC = valid_iC;
    assign ready_oA = ready_iA;
    assign ready_oB = ready_iB;
    assign ready_oC = ready_iC;
    assign data_oA = data_iA;
    assign data_oB = data_iB;
    assign data_oC = data_iC;
  end

else
  begin : gen_spill_reg

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_a_dataA
        if (!rst_niA)
          a_data_qA <= T' ('0) ;
        else
          if (a_fillA)
            a_data_qA <= data_iA;
          else
            a_data_qA <= a_data_qVotedA;
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_a_dataB
        if (!rst_niB)
          a_data_qB <= T' ('0) ;
        else
          if (a_fillB)
            a_data_qB <= data_iB;
          else
            a_data_qB <= a_data_qVotedB;
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_a_dataC
        if (!rst_niC)
          a_data_qC <= T' ('0) ;
        else
          if (a_fillC)
            a_data_qC <= data_iC;
          else
            a_data_qC <= a_data_qVotedC;
      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_a_fullA
        if (!rst_niA)
          a_full_qA <= 0;
        else
          if (a_fillA||a_drainA)
            a_full_qA <= a_fillA;
          else
            a_full_qA <= a_full_qVotedA;
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_a_fullB
        if (!rst_niB)
          a_full_qB <= 0;
        else
          if (a_fillB||a_drainB)
            a_full_qB <= a_fillB;
          else
            a_full_qB <= a_full_qVotedB;
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_a_fullC
        if (!rst_niC)
          a_full_qC <= 0;
        else
          if (a_fillC||a_drainC)
            a_full_qC <= a_fillC;
          else
            a_full_qC <= a_full_qVotedC;
      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_b_dataA
        if (!rst_niA)
          b_data_qA <= T' ('0) ;
        else
          if (b_fillA)
            b_data_qA <= a_data_qVotedA;
          else
            b_data_qA <= b_data_qVotedA;
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_b_dataB
        if (!rst_niB)
          b_data_qB <= T' ('0) ;
        else
          if (b_fillB)
            b_data_qB <= a_data_qVotedB;
          else
            b_data_qB <= b_data_qVotedB;
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_b_dataC
        if (!rst_niC)
          b_data_qC <= T' ('0) ;
        else
          if (b_fillC)
            b_data_qC <= a_data_qVotedC;
          else
            b_data_qC <= b_data_qVotedC;
      end

    always_ff @( posedge clk_iA or negedge rst_niA )
      begin : ps_b_fullA
        if (!rst_niA)
          b_full_qA <= 0;
        else
          if (b_fillA||b_drainA)
            b_full_qA <= b_fillA;
          else
            b_full_qA <= b_full_qVotedA;
      end

    always_ff @( posedge clk_iB or negedge rst_niB )
      begin : ps_b_fullB
        if (!rst_niB)
          b_full_qB <= 0;
        else
          if (b_fillB||b_drainB)
            b_full_qB <= b_fillB;
          else
            b_full_qB <= b_full_qVotedB;
      end

    always_ff @( posedge clk_iC or negedge rst_niC )
      begin : ps_b_fullC
        if (!rst_niC)
          b_full_qC <= 0;
        else
          if (b_fillC||b_drainC)
            b_full_qC <= b_fillC;
          else
            b_full_qC <= b_full_qVotedC;
      end
    assign a_fillA = valid_iA&&ready_oA&& (! flush_iA ) ;
    assign a_fillB = valid_iB&&ready_oB&& (! flush_iB ) ;
    assign a_fillC = valid_iC&&ready_oC&& (! flush_iC ) ;
    assign a_drainA =  (a_full_qVotedA&&!b_full_qVotedA) ||flush_iA;
    assign a_drainB =  (a_full_qVotedB&&!b_full_qVotedB) ||flush_iB;
    assign a_drainC =  (a_full_qVotedC&&!b_full_qVotedC) ||flush_iC;
    assign b_fillA = a_drainA&& (! ready_iA ) && (! flush_iA ) ;
    assign b_fillB = a_drainB&& (! ready_iB ) && (! flush_iB ) ;
    assign b_fillC = a_drainC&& (! ready_iC ) && (! flush_iC ) ;
    assign b_drainA =  (b_full_qVotedA&&ready_iA) ||flush_iA;
    assign b_drainB =  (b_full_qVotedB&&ready_iB) ||flush_iB;
    assign b_drainC =  (b_full_qVotedC&&ready_iC) ||flush_iC;
    assign ready_oA = !a_full_qVotedA||!b_full_qVotedA;
    assign ready_oB = !a_full_qVotedB||!b_full_qVotedB;
    assign ready_oC = !a_full_qVotedC||!b_full_qVotedC;
    assign valid_oA = a_full_qVotedA|b_full_qVotedA;
    assign valid_oB = a_full_qVotedB|b_full_qVotedB;
    assign valid_oC = a_full_qVotedC|b_full_qVotedC;
    assign data_oA = b_full_qVotedA ? b_data_qVotedA : a_data_qVotedA;
    assign data_oB = b_full_qVotedB ? b_data_qVotedB : a_data_qVotedB;
    assign data_oC = b_full_qVotedC ? b_data_qVotedC : a_data_qVotedC;
  end

majorityVoter #(.WIDTH( ($size(a_data_qVotedA)) )) a_data_qVoterA (
    .inA(a_data_qA),
    .inB(a_data_qB),
    .inC(a_data_qC),
    .out(a_data_qVotedA),
    .tmrErr(a_data_qTmrErrorA)
  );

majorityVoter a_full_qVoterA (
    .inA(a_full_qA),
    .inB(a_full_qB),
    .inC(a_full_qC),
    .out(a_full_qVotedA),
    .tmrErr(a_full_qTmrErrorA)
  );

majorityVoter #(.WIDTH( ($size(a_data_qVotedA)) )) b_data_qVoterA (
    .inA(b_data_qA),
    .inB(b_data_qB),
    .inC(b_data_qC),
    .out(b_data_qVotedA),
    .tmrErr(b_data_qTmrErrorA)
  );

majorityVoter b_full_qVoterA (
    .inA(b_full_qA),
    .inB(b_full_qB),
    .inC(b_full_qC),
    .out(b_full_qVotedA),
    .tmrErr(b_full_qTmrErrorA)
  );
assign tmrErrorA = a_data_qTmrErrorA|a_full_qTmrErrorA|b_data_qTmrErrorA|b_full_qTmrErrorA;

majorityVoter #(.WIDTH( ($size(a_data_qVotedA)) )) a_data_qVoterB (
    .inA(a_data_qA),
    .inB(a_data_qB),
    .inC(a_data_qC),
    .out(a_data_qVotedB),
    .tmrErr(a_data_qTmrErrorB)
  );

majorityVoter a_full_qVoterB (
    .inA(a_full_qA),
    .inB(a_full_qB),
    .inC(a_full_qC),
    .out(a_full_qVotedB),
    .tmrErr(a_full_qTmrErrorB)
  );

majorityVoter #(.WIDTH( ($size(a_data_qVotedA)) )) b_data_qVoterB (
    .inA(b_data_qA),
    .inB(b_data_qB),
    .inC(b_data_qC),
    .out(b_data_qVotedB),
    .tmrErr(b_data_qTmrErrorB)
  );

majorityVoter b_full_qVoterB (
    .inA(b_full_qA),
    .inB(b_full_qB),
    .inC(b_full_qC),
    .out(b_full_qVotedB),
    .tmrErr(b_full_qTmrErrorB)
  );
assign tmrErrorB = a_data_qTmrErrorB|a_full_qTmrErrorB|b_data_qTmrErrorB|b_full_qTmrErrorB;

majorityVoter #(.WIDTH( ($size(a_data_qVotedA)) )) a_data_qVoterC (
    .inA(a_data_qA),
    .inB(a_data_qB),
    .inC(a_data_qC),
    .out(a_data_qVotedC),
    .tmrErr(a_data_qTmrErrorC)
  );

majorityVoter a_full_qVoterC (
    .inA(a_full_qA),
    .inB(a_full_qB),
    .inC(a_full_qC),
    .out(a_full_qVotedC),
    .tmrErr(a_full_qTmrErrorC)
  );

majorityVoter #(.WIDTH( ($size(a_data_qVotedA)) )) b_data_qVoterC (
    .inA(b_data_qA),
    .inB(b_data_qB),
    .inC(b_data_qC),
    .out(b_data_qVotedC),
    .tmrErr(b_data_qTmrErrorC)
  );

majorityVoter b_full_qVoterC (
    .inA(b_full_qA),
    .inB(b_full_qB),
    .inC(b_full_qC),
    .out(b_full_qVotedC),
    .tmrErr(b_full_qTmrErrorC)
  );
assign tmrErrorC = a_data_qTmrErrorC|a_full_qTmrErrorC|b_data_qTmrErrorC|b_full_qTmrErrorC;
endmodule

