/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : tmrg_files/stream_fifoTMR.sv                                                           *
 *                                                                                                  *
 * user    : chenwu                                                                                 *
 * host    : badwater.ee.ethz.ch                                                                    *
 * date    : 30/12/2025 17:23:18                                                                    *
 *                                                                                                  *
 * workdir : /scratch/chenwu/relnoc/tmrg_floonoc                                                    *
 * cmd     : /scratch/chenwu/tmrg/venv/bin/tmrg tmrg_src/floo_nw_router.sv tmrg_src/floo_router.sv  *
 *           tmrg_src/stream_fifo_optimal_wrap.sv tmrg_src/spill_register_flushable.sv              *
 *           tmrg_src/stream_fifo.sv tmrg_src/fifo_v3.sv tmrg_src/floo_route_select.sv              *
 *           tmrg_src/floo_route_xymask.sv tmrg_src/addr_decode.sv tmrg_src/addr_decode_dync.sv     *
 *           tmrg_src/floo_wormhole_arbiter.sv tmrg_src/rr_arb_tree.sv tmrg_src/floo_output_arbiter.sv *
 *           tmrg_src/floo_reduction_arbiter.sv tmrg_src/floo_reduction_sync.sv                     *
 *           tmrg_src/stream_arbiter.sv tmrg_src/stream_arbiter_flushable.sv                        *
 *           tmrg_src/floo_vc_arbiter.sv tmrg_src/lzc.sv --top-module=floo_nw_router --tmr-         *
 *           dir=tmrg_files                                                                         *
 * tmrg rev: b94addac7490a9efad5a56e12a3ab232d01f4c92                                               *
 *                                                                                                  *
 * src file: tmrg_src/stream_fifo.sv                                                                *
 *           Git SHA           : File not in git repository!                                        *
 *           Modification time : 2025-12-30 16:11:45.462819                                         *
 *           File Size         : 2707                                                               *
 *           MD5 hash          : d081e719dff15fbf9575af65bdf16d2d                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module stream_fifoTMR #(
  parameter bit FALL_THROUGH = 1'b0,
  parameter int unsigned DATA_WIDTH = 32,
  parameter int unsigned DEPTH = 8,
  parameter type         T            = logic [DATA_WIDTH-1:0],
  parameter int unsigned ADDR_DEPTH = (DEPTH>1) ? $clog2(DEPTH) : 1
) (
  input logic clk_iA,
  input logic clk_iB,
  input logic clk_iC,
  input logic rst_niA,
  input logic rst_niB,
  input logic rst_niC,
  input logic flush_iA,
  input logic flush_iB,
  input logic flush_iC,
  input logic testmode_iA,
  input logic testmode_iB,
  input logic testmode_iC,
  output logic [ADDR_DEPTH - 1:0] usage_oA,
  output logic [ADDR_DEPTH - 1:0] usage_oB,
  output logic [ADDR_DEPTH - 1:0] usage_oC,
  input T data_iA,
  input T data_iB,
  input T data_iC,
  input logic valid_iA,
  input logic valid_iB,
  input logic valid_iC,
  output logic ready_oA,
  output logic ready_oB,
  output logic ready_oC,
  output T data_oA,
  output T data_oB,
  output T data_oC,
  output logic valid_oA,
  output logic valid_oB,
  output logic valid_oC,
  input logic ready_iA,
  input logic ready_iB,
  input logic ready_iC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wire fifo_itmrErrorC;
wire fifo_itmrErrorB;
wire fifo_itmrErrorA;
logic pushA;
logic pushB;
logic pushC;
logic popA;
logic popB;
logic popC;
logic emptyA;
logic emptyB;
logic emptyC;
logic fullA;
logic fullB;
logic fullC;
assign pushA = valid_iA&~fullA;
assign pushB = valid_iB&~fullB;
assign pushC = valid_iC&~fullC;
assign popA = ready_iA&~emptyA;
assign popB = ready_iB&~emptyB;
assign popC = ready_iC&~emptyC;
assign ready_oA = ~fullA;
assign ready_oB = ~fullB;
assign ready_oC = ~fullC;
assign valid_oA = ~emptyA;
assign valid_oB = ~emptyB;
assign valid_oC = ~emptyC;

fifo_v3TMR #(.FALL_THROUGH(FALL_THROUGH), .DATA_WIDTH(DATA_WIDTH), .DEPTH(DEPTH), .dtype(T)) fifo_i (
    .clk_iA(clk_iA),
    .clk_iB(clk_iB),
    .clk_iC(clk_iC),
    .rst_niA(rst_niA),
    .rst_niB(rst_niB),
    .rst_niC(rst_niC),
    .flush_iA(flush_iA),
    .flush_iB(flush_iB),
    .flush_iC(flush_iC),
    .testmode_iA(testmode_iA),
    .testmode_iB(testmode_iB),
    .testmode_iC(testmode_iC),
    .full_oA(fullA),
    .full_oB(fullB),
    .full_oC(fullC),
    .empty_oA(emptyA),
    .empty_oB(emptyB),
    .empty_oC(emptyC),
    .usage_oA(usage_oA),
    .usage_oB(usage_oB),
    .usage_oC(usage_oC),
    .data_iA(data_iA),
    .data_iB(data_iB),
    .data_iC(data_iC),
    .push_iA(pushA),
    .push_iB(pushB),
    .push_iC(pushC),
    .data_oA(data_oA),
    .data_oB(data_oB),
    .data_oC(data_oC),
    .pop_iA(popA),
    .pop_iB(popB),
    .pop_iC(popC),
    .tmrErrorA(fifo_itmrErrorA),
    .tmrErrorB(fifo_itmrErrorB),
    .tmrErrorC(fifo_itmrErrorC)
  );
assign tmrErrorA = fifo_itmrErrorA;
assign tmrErrorB = fifo_itmrErrorB;
assign tmrErrorC = fifo_itmrErrorC;
endmodule

